### ISSUE TITLE
Assert: "VARSIZE_EXTERNAL(attre) == sizeof(toast_pointer) + VARHDRSZ_EXTERNAL"

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#106]
specs/test.spec:

```sql
setup
{
 CREATE EXTENSION IF NOT EXISTS orioledb;

  CREATE TABLE o_test_1(
		val_1 int primary key, 
		val_2 text
	)USING orioledb;

  INSERT INTO o_test_1
    SELECT 1, repeat('1', 11) || string_agg(g.i::text || random()::text, '') 
	FROM generate_series(1, 500) g(i);

  INSERT INTO o_test_1
    SELECT 2, repeat('2', 11) || string_agg(g.i::text || random()::text, '') 
	FROM generate_series(1, 500) g(i);	
}

teardown
{
    DROP TABLE IF EXISTS o_test_1;
}

session s1
setup { BEGIN; }
step "lock_row_exclusive_mode_1" { LOCK TABLE o_test_1 in ROW EXCLUSIVE MODE; }
step "lock_share_mode_1" { LOCK TABLE o_test_1 in SHARE MODE; }
step "lock_exclusive_mode_1" { LOCK TABLE o_test_1 in EXCLUSIVE MODE; }
step "insert_1" { INSERT INTO o_test_1
					SELECT 3, repeat('3', 11) || string_agg(g.i::text || random()::text, '') 
					FROM generate_series(1, 500) g(i); }

step "commit_1" { COMMIT; }
step "rollback_1" { ROLLBACK; }

session s2
step "reindex_table_2" { REINDEX TABLE CONCURRENTLY pg_toast.reind_con_toast; }
step "select_2" { SELECT val_1, substr(val_2, 1, 10) 
					FROM o_test_1 ORDER BY val_1; }

#permutation_1
permutation "lock_row_exclusive_mode_1" "insert_1" "reindex_table_2" "commit_1" "select_2"

#permutation_2
permutation "lock_share_mode_1" "insert_1" "reindex_table_2" "commit_1" "select_2"

#permutation_3
permutation "lock_exclusive_mode_1" "insert_1" "reindex_table_2" "commit_1" "select_2"

#permutation_4
permutation "lock_row_exclusive_mode_1" "insert_1" "reindex_table_2" "rollback_1" "select_2"

#permutation_5
permutation "lock_share_mode_1" "insert_1" "reindex_table_2" "rollback_1" "select_2"

#permutation_6
permutation "lock_exclusive_mode_1" "insert_1" "reindex_table_2" "rollback_1" "select_2"
```

**Coredump permutation_1**
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f692d774859 in __GI_abort () at abort.c:79
#2  0x0000564bdff971d8 in ExceptionalCondition (conditionName=conditionName@entry=0x564bdfff6548 "VARSIZE_EXTERNAL(attre) == sizeof(toast_pointer) + VARHDRSZ_EXTERNAL", errorType=errorType@entry=0x564bdfff400b "FailedAssertion", fileName=fileName@entry=0x564bdfff66d4 "detoast.c", lineNumber=lineNumber@entry=229) at assert.c:69
#3  0x0000564bdfafec7c in detoast_attr_slice (attr=<optimized out>, sliceoffset=0, slicelength=44) at detoast.c:229
#4  0x0000564bdffa1979 in pg_detoast_datum_slice (datum=<optimized out>, first=<optimized out>, count=<optimized out>) at fmgr.c:1736
#5  0x0000564bdff70a6a in text_substring (str=94883903409312, start=1, length=<optimized out>, length_not_specified=<optimized out>) at varlena.c:994
#6  0x0000564bdfcc4240 in ExecInterpExpr (state=0x564be15b0fc0, econtext=0x564be15aff30, isnull=<optimized out>) at execExprInterp.c:761
#7  0x0000564bdfcfe782 in ExecEvalExprSwitchContext (isNull=0x7ffda915ebc7, econtext=0x564be15aff30, state=0x564be15b0fc0) at ../../../src/include/executor/executor.h:343
#8  ExecProject (projInfo=0x564be15b0fb8) at ../../../src/include/executor/executor.h:377
#9  ExecResult (pstate=<optimized out>) at nodeResult.c:136
#10 0x0000564bdfcc89b3 in ExecProcNode (node=0x564be15afe18) at ../../../src/include/executor/executor.h:259
#11 ExecutePlan (execute_once=<optimized out>, dest=0x564be15ac8b0, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x564be15afe18, estate=0x564be15afbe0) at execMain.c:1642
#12 standard_ExecutorRun (queryDesc=0x564be1584240, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:363
#13 0x0000564bdfe66eff in PortalRunSelect (portal=0x564be152a0a0, forward=<optimized out>, count=0, dest=<optimized out>) at pquery.c:924
#14 0x0000564bdfe684d1 in PortalRun (portal=portal@entry=0x564be152a0a0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x564be15ac8b0, altdest=altdest@entry=0x564be15ac8b0, qc=0x7ffda915ee60) at pquery.c:768
#15 0x0000564bdfe642d2 in exec_simple_query (query_string=0x564be149f4b0 "SELECT val_1, substr(val_2, 1, 10) \n\t\t\t\t\tFROM o_test_1 ORDER BY val_1;") at postgres.c:1250
#16 0x0000564bdfe6601e in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4544
#17 0x0000564bdfdcd2aa in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4510
#18 BackendStartup (port=<optimized out>) at postmaster.c:4238
#19 ServerLoop () at postmaster.c:1812
#20 0x0000564bdfdce41b in PostmasterMain (argc=<optimized out>, argv=0x564be1499c30) at postmaster.c:1484
#21 0x0000564bdfaef6a0 in main (argc=8, argv=0x564be1499c30) at main.c:202
```

**Coredump permutation_2**
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fe296088859 in __GI_abort () at abort.c:79
#2  0x000055db7e6d91d8 in ExceptionalCondition (conditionName=conditionName@entry=0x55db7e738548 "VARSIZE_EXTERNAL(attre) == sizeof(toast_pointer) + VARHDRSZ_EXTERNAL", errorType=errorType@entry=0x55db7e73600b "FailedAssertion", fileName=fileName@entry=0x55db7e7386d4 "detoast.c", lineNumber=lineNumber@entry=229) at assert.c:69
#3  0x000055db7e240c7c in detoast_attr_slice (attr=<optimized out>, sliceoffset=0, slicelength=44) at detoast.c:229
#4  0x000055db7e6e3979 in pg_detoast_datum_slice (datum=<optimized out>, first=<optimized out>, count=<optimized out>) at fmgr.c:1736
#5  0x000055db7e6b2a6a in text_substring (str=94401213209760, start=1, length=<optimized out>, length_not_specified=<optimized out>) at varlena.c:994
#6  0x000055db7e406240 in ExecInterpExpr (state=0x55db7ec71fc0, econtext=0x55db7ec70f30, isnull=<optimized out>) at execExprInterp.c:761
#7  0x000055db7e440782 in ExecEvalExprSwitchContext (isNull=0x7ffe1924b817, econtext=0x55db7ec70f30, state=0x55db7ec71fc0) at ../../../src/include/executor/executor.h:343
#8  ExecProject (projInfo=0x55db7ec71fb8) at ../../../src/include/executor/executor.h:377
#9  ExecResult (pstate=<optimized out>) at nodeResult.c:136
#10 0x000055db7e40a9b3 in ExecProcNode (node=0x55db7ec70e18) at ../../../src/include/executor/executor.h:259
#11 ExecutePlan (execute_once=<optimized out>, dest=0x55db7ec6d8b0, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x55db7ec70e18, estate=0x55db7ec70be0) at execMain.c:1642
#12 standard_ExecutorRun (queryDesc=0x55db7ec45240, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:363
#13 0x000055db7e5a8eff in PortalRunSelect (portal=0x55db7ebeb0a0, forward=<optimized out>, count=0, dest=<optimized out>) at pquery.c:924
#14 0x000055db7e5aa4d1 in PortalRun (portal=portal@entry=0x55db7ebeb0a0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x55db7ec6d8b0, altdest=altdest@entry=0x55db7ec6d8b0, qc=0x7ffe1924bab0) at pquery.c:768
#15 0x000055db7e5a62d2 in exec_simple_query (query_string=0x55db7eb604b0 "SELECT val_1, substr(val_2, 1, 10) \n\t\t\t\t\tFROM o_test_1 ORDER BY val_1;") at postgres.c:1250
#16 0x000055db7e5a801e in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4544
#17 0x000055db7e50f2aa in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4510
#18 BackendStartup (port=<optimized out>) at postmaster.c:4238
#19 ServerLoop () at postmaster.c:1812
#20 0x000055db7e51041b in PostmasterMain (argc=<optimized out>, argv=0x55db7eb5ac30) at postmaster.c:1484
#21 0x000055db7e2316a0 in main (argc=8, argv=0x55db7eb5ac30) at main.c:202
```

**Coredump permutation_3**
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fd3ea1bf859 in __GI_abort () at abort.c:79
#2  0x00005583287291d8 in ExceptionalCondition (conditionName=conditionName@entry=0x558328788548 "VARSIZE_EXTERNAL(attre) == sizeof(toast_pointer) + VARHDRSZ_EXTERNAL", errorType=errorType@entry=0x55832878600b "FailedAssertion", fileName=fileName@entry=0x5583287886d4 "detoast.c", lineNumber=lineNumber@entry=229) at assert.c:69
#3  0x0000558328290c7c in detoast_attr_slice (attr=<optimized out>, sliceoffset=0, slicelength=44) at detoast.c:229
#4  0x0000558328733979 in pg_detoast_datum_slice (datum=<optimized out>, first=<optimized out>, count=<optimized out>) at fmgr.c:1736
#5  0x0000558328702a6a in text_substring (str=94021843610784, start=1, length=<optimized out>, length_not_specified=<optimized out>) at varlena.c:994
#6  0x0000558328456240 in ExecInterpExpr (state=0x55832a966fc0, econtext=0x55832a965f30, isnull=<optimized out>) at execExprInterp.c:761
#7  0x0000558328490782 in ExecEvalExprSwitchContext (isNull=0x7fffbac2fc37, econtext=0x55832a965f30, state=0x55832a966fc0) at ../../../src/include/executor/executor.h:343
#8  ExecProject (projInfo=0x55832a966fb8) at ../../../src/include/executor/executor.h:377
#9  ExecResult (pstate=<optimized out>) at nodeResult.c:136
#10 0x000055832845a9b3 in ExecProcNode (node=0x55832a965e18) at ../../../src/include/executor/executor.h:259
#11 ExecutePlan (execute_once=<optimized out>, dest=0x55832a9628b0, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x55832a965e18, estate=0x55832a965be0) at execMain.c:1642
#12 standard_ExecutorRun (queryDesc=0x55832a93a240, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:363
#13 0x00005583285f8eff in PortalRunSelect (portal=0x55832a8e00a0, forward=<optimized out>, count=0, dest=<optimized out>) at pquery.c:924
#14 0x00005583285fa4d1 in PortalRun (portal=portal@entry=0x55832a8e00a0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x55832a9628b0, altdest=altdest@entry=0x55832a9628b0, qc=0x7fffbac2fed0) at pquery.c:768
#15 0x00005583285f62d2 in exec_simple_query (query_string=0x55832a8554b0 "SELECT val_1, substr(val_2, 1, 10) \n\t\t\t\t\tFROM o_test_1 ORDER BY val_1;") at postgres.c:1250
#16 0x00005583285f801e in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4544
#17 0x000055832855f2aa in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4510
#18 BackendStartup (port=<optimized out>) at postmaster.c:4238
#19 ServerLoop () at postmaster.c:1812
#20 0x000055832856041b in PostmasterMain (argc=<optimized out>, argv=0x55832a84fc30) at postmaster.c:1484
#21 0x00005583282816a0 in main (argc=8, argv=0x55832a84fc30) at main.c:202
```

**Coredump permutation_4**
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ff1bdf44859 in __GI_abort () at abort.c:79
#2  0x000055de63a0d1d8 in ExceptionalCondition (conditionName=conditionName@entry=0x55de63a6c548 "VARSIZE_EXTERNAL(attre) == sizeof(toast_pointer) + VARHDRSZ_EXTERNAL", errorType=errorType@entry=0x55de63a6a00b "FailedAssertion", fileName=fileName@entry=0x55de63a6c6d4 "detoast.c", lineNumber=lineNumber@entry=229) at assert.c:69
#3  0x000055de63574c7c in detoast_attr_slice (attr=<optimized out>, sliceoffset=0, slicelength=44) at detoast.c:229
#4  0x000055de63a17979 in pg_detoast_datum_slice (datum=<optimized out>, first=<optimized out>, count=<optimized out>) at fmgr.c:1736
#5  0x000055de639e6a6a in text_substring (str=94413658311840, start=1, length=<optimized out>, length_not_specified=<optimized out>) at varlena.c:994
#6  0x000055de6373a240 in ExecInterpExpr (state=0x55de64904fc0, econtext=0x55de64903f30, isnull=<optimized out>) at execExprInterp.c:761
#7  0x000055de63774782 in ExecEvalExprSwitchContext (isNull=0x7ffc0b71f2f7, econtext=0x55de64903f30, state=0x55de64904fc0) at ../../../src/include/executor/executor.h:343
#8  ExecProject (projInfo=0x55de64904fb8) at ../../../src/include/executor/executor.h:377
#9  ExecResult (pstate=<optimized out>) at nodeResult.c:136
#10 0x000055de6373e9b3 in ExecProcNode (node=0x55de64903e18) at ../../../src/include/executor/executor.h:259
#11 ExecutePlan (execute_once=<optimized out>, dest=0x55de649008b0, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x55de64903e18, estate=0x55de64903be0) at execMain.c:1642
#12 standard_ExecutorRun (queryDesc=0x55de648d8240, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:363
#13 0x000055de638dceff in PortalRunSelect (portal=0x55de6487e0a0, forward=<optimized out>, count=0, dest=<optimized out>) at pquery.c:924
#14 0x000055de638de4d1 in PortalRun (portal=portal@entry=0x55de6487e0a0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x55de649008b0, altdest=altdest@entry=0x55de649008b0, qc=0x7ffc0b71f590) at pquery.c:768
#15 0x000055de638da2d2 in exec_simple_query (query_string=0x55de647f34b0 "SELECT val_1, substr(val_2, 1, 10) \n\t\t\t\t\tFROM o_test_1 ORDER BY val_1;") at postgres.c:1250
#16 0x000055de638dc01e in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4544
#17 0x000055de638432aa in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4510
#18 BackendStartup (port=<optimized out>) at postmaster.c:4238
#19 ServerLoop () at postmaster.c:1812
#20 0x000055de6384441b in PostmasterMain (argc=<optimized out>, argv=0x55de647edc30) at postmaster.c:1484
#21 0x000055de635656a0 in main (argc=8, argv=0x55de647edc30) at main.c:202
```

**Coredump permutation_5**
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fc59aec9859 in __GI_abort () at abort.c:79
#2  0x000055613cb021d8 in ExceptionalCondition (conditionName=conditionName@entry=0x55613cb61548 "VARSIZE_EXTERNAL(attre) == sizeof(toast_pointer) + VARHDRSZ_EXTERNAL", errorType=errorType@entry=0x55613cb5f00b "FailedAssertion", fileName=fileName@entry=0x55613cb616d4 "detoast.c", lineNumber=lineNumber@entry=229) at assert.c:69
#3  0x000055613c669c7c in detoast_attr_slice (attr=<optimized out>, sliceoffset=0, slicelength=44) at detoast.c:229
#4  0x000055613cb0c979 in pg_detoast_datum_slice (datum=<optimized out>, first=<optimized out>, count=<optimized out>) at fmgr.c:1736
#5  0x000055613cadba6a in text_substring (str=93876139568288, start=1, length=<optimized out>, length_not_specified=<optimized out>) at varlena.c:994
#6  0x000055613c82f240 in ExecInterpExpr (state=0x55613df32fc0, econtext=0x55613df31f30, isnull=<optimized out>) at execExprInterp.c:761
#7  0x000055613c869782 in ExecEvalExprSwitchContext (isNull=0x7fffd8a0cb77, econtext=0x55613df31f30, state=0x55613df32fc0) at ../../../src/include/executor/executor.h:343
#8  ExecProject (projInfo=0x55613df32fb8) at ../../../src/include/executor/executor.h:377
#9  ExecResult (pstate=<optimized out>) at nodeResult.c:136
#10 0x000055613c8339b3 in ExecProcNode (node=0x55613df31e18) at ../../../src/include/executor/executor.h:259
#11 ExecutePlan (execute_once=<optimized out>, dest=0x55613df2e8b0, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x55613df31e18, estate=0x55613df31be0) at execMain.c:1642
#12 standard_ExecutorRun (queryDesc=0x55613df06240, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:363
#13 0x000055613c9d1eff in PortalRunSelect (portal=0x55613deac0a0, forward=<optimized out>, count=0, dest=<optimized out>) at pquery.c:924
#14 0x000055613c9d34d1 in PortalRun (portal=portal@entry=0x55613deac0a0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x55613df2e8b0, altdest=altdest@entry=0x55613df2e8b0, qc=0x7fffd8a0ce10) at pquery.c:768
#15 0x000055613c9cf2d2 in exec_simple_query (query_string=0x55613de214b0 "SELECT val_1, substr(val_2, 1, 10) \n\t\t\t\t\tFROM o_test_1 ORDER BY val_1;") at postgres.c:1250
#16 0x000055613c9d101e in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4544
#17 0x000055613c9382aa in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4510
#18 BackendStartup (port=<optimized out>) at postmaster.c:4238
#19 ServerLoop () at postmaster.c:1812
#20 0x000055613c93941b in PostmasterMain (argc=<optimized out>, argv=0x55613de1bc30) at postmaster.c:1484
#21 0x000055613c65a6a0 in main (argc=8, argv=0x55613de1bc30) at main.c:202
```

**Coredump permutation_6**
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fbc71bac859 in __GI_abort () at abort.c:79
#2  0x000056392bfc91d8 in ExceptionalCondition (conditionName=conditionName@entry=0x56392c028548 "VARSIZE_EXTERNAL(attre) == sizeof(toast_pointer) + VARHDRSZ_EXTERNAL", errorType=errorType@entry=0x56392c02600b "FailedAssertion", fileName=fileName@entry=0x56392c0286d4 "detoast.c", lineNumber=lineNumber@entry=229) at assert.c:69
#3  0x000056392bb30c7c in detoast_attr_slice (attr=<optimized out>, sliceoffset=0, slicelength=44) at detoast.c:229
#4  0x000056392bfd3979 in pg_detoast_datum_slice (datum=<optimized out>, first=<optimized out>, count=<optimized out>) at fmgr.c:1736
#5  0x000056392bfa2a6a in text_substring (str=94803583061152, start=1, length=<optimized out>, length_not_specified=<optimized out>) at varlena.c:994
#6  0x000056392bcf6240 in ExecInterpExpr (state=0x56392de3cfc0, econtext=0x56392de3bf30, isnull=<optimized out>) at execExprInterp.c:761
#7  0x000056392bd30782 in ExecEvalExprSwitchContext (isNull=0x7ffda3f4a957, econtext=0x56392de3bf30, state=0x56392de3cfc0) at ../../../src/include/executor/executor.h:343
#8  ExecProject (projInfo=0x56392de3cfb8) at ../../../src/include/executor/executor.h:377
#9  ExecResult (pstate=<optimized out>) at nodeResult.c:136
#10 0x000056392bcfa9b3 in ExecProcNode (node=0x56392de3be18) at ../../../src/include/executor/executor.h:259
#11 ExecutePlan (execute_once=<optimized out>, dest=0x56392de388b0, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x56392de3be18, estate=0x56392de3bbe0) at execMain.c:1642
#12 standard_ExecutorRun (queryDesc=0x56392de10240, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:363
#13 0x000056392be98eff in PortalRunSelect (portal=0x56392ddb60a0, forward=<optimized out>, count=0, dest=<optimized out>) at pquery.c:924
#14 0x000056392be9a4d1 in PortalRun (portal=portal@entry=0x56392ddb60a0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x56392de388b0, altdest=altdest@entry=0x56392de388b0, qc=0x7ffda3f4abf0) at pquery.c:768
#15 0x000056392be962d2 in exec_simple_query (query_string=0x56392dd2b4b0 "SELECT val_1, substr(val_2, 1, 10) \n\t\t\t\t\tFROM o_test_1 ORDER BY val_1;") at postgres.c:1250
#16 0x000056392be9801e in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4544
#17 0x000056392bdff2aa in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4510
#18 BackendStartup (port=<optimized out>) at postmaster.c:4238
#19 ServerLoop () at postmaster.c:1812
#20 0x000056392be0041b in PostmasterMain (argc=<optimized out>, argv=0x56392dd25c30) at postmaster.c:1484
#21 0x000056392bb216a0 in main (argc=8, argv=0x56392dd25c30) at main.c:202
```

Run as:
```
make USE_PGXS=1 isolationcheck ISOLATIONCHECKS="test"
```

**Comment by homper** [comment]
Fixed on [main](https://github.com/orioledb/orioledb)
