### ISSUE TITLE
Assert: nextPage->status != OParallelScanPageInProgress

### ISSUE THREAD

**Issue by homper** [orioledb/orioledb#113]
https://github.com/orioledb/orioledb/actions/runs/3420221923/jobs/5694762147

```py
	def test_checkpoint_autonomous_evict_random(self):
		node = self.node
		node.append_conf('postgresql.conf',
						 "log_min_messages = notice\n"
						 "orioledb.main_buffers = 48MB\n"
						 "orioledb.enable_stopevents = true\n")
		node.start()
		node.safe_psql('postgres', "CREATE EXTENSION IF NOT EXISTS orioledb;")
		node.safe_psql('postgres', """CREATE TABLE IF NOT EXISTS o_checkpoint (
										id text NOT NULL,
										PRIMARY KEY (id)
									) USING orioledb;""")
		node.safe_psql('postgres', "INSERT INTO o_checkpoint (SELECT to_char(id, 'fm0000') || repeat('x', 2500) FROM generate_series(3500,7000,100) id);")

		con1 = node.connect()
		con2 = node.connect()
		con3 = node.connect()

		con3.execute("SELECT pg_stopevent_set('checkpoint_step',\n"
											  "'$.action == \"walkUpwards\" && "
											   "$.treeName == \"o_checkpoint_pkey\" && "
											   "($.nextKey.value.id > \"%d\" || $.nextKey.type == \"greatest\")');" % (random.randint(3500, 7000)))

		t1 = ThreadQueryExecutor(con1, "CHECKPOINT;")
		t1.start()
		wait_checkpointer_stopevent(node)

		con2.begin()
		for i in range(3500, 7200, 100):
			con2.execute("INSERT INTO o_checkpoint (SELECT to_char(id, 'fm0000') || repeat('y', 2500) FROM generate_series(%s, %s) id);" % (str(i), str(i + 99)))
		con2.commit()

		con3.execute("SELECT pg_stopevent_reset('checkpoint_step')")
		t1.join()

		con1.close()
		con2.close()
		con3.close()
		node.stop(['-m', 'immediate'])

		node.append_conf("postgresql.conf",
						 "orioledb.main_buffers = 64MB\n")
		node.start()
		node.safe_psql("SELECT * FROM o_checkpoint;")
		self.assertEqual(node.execute("SELECT COUNT(*) FROM o_checkpoint;")[0][0], 3736)
		node.safe_psql('postgres', "CHECKPOINT;")
		self.assertTrue(node.execute("SELECT orioledb_tbl_check('o_checkpoint'::regclass)")[0][0])
		node.stop()
```

```
Core was generated by `postgres: parallel worker for PID 21071                                       '.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50

Thread 1 (Thread 0x7fbd491fa740 (LWP 21075)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {4194304, 0, 0, 0, 0, 94285688213728, 4611686018427387904, 0, 0, 140450991551722, 0, 94285688213774, 128, 0, 140723484430832, 140450983953952}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007fbd4aedf859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7fbd4b072bf7, sa_sigaction = 0x7fbd4b072bf7}, sa_mask = {__val = {1, 140450984312862, 3, 140723484431012, 12, 140450984312866, 2, 3486689040302438777, 7291381884115105849, 140723484431120, 7291946156898434056, 0, 2058227453457658368, 140723484431104, 672, 21}}, sa_flags = -1119022320, sa_restorer = 0x7fbd48d0bc08}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x000055c0993e9c58 in ExceptionalCondition (conditionName=conditionName@entry=0x7fbd48d0bc08 "nextPage->status != OParallelScanPageInProgress", errorType=errorType@entry=0x7fbd48d08012 "FailedAssertion", fileName=fileName@entry=0x7fbd48d0b8e8 "src/btree/scan.c", lineNumber=lineNumber@entry=672) at assert.c:69
No locals.
#3  0x00007fbd48c91f52 in get_next_downlink (keyRangeHigh=0x55c09aa63f80, keyRangeLow=0x55c09aa634f0, downlink=0x7ffcbd4d16c8, scan=0x55c09aa58660) at src/btree/scan.c:672
        loaded = <optimized out>
        curPage = 0x7fbd39c921b0
        nextPage = 0x7fbd39c94c50
        loc = {chunkOffset = 0, itemOffset = 3, chunkItemsCount = 3, chunkSize = 5072, chunk = 0x7fbd39c95668}
        poscan = 0x7fbd39c921a0
        poscan = <optimized out>
        __func__ = "get_next_downlink"
        pageIsLoaded = <optimized out>
        curPage = <optimized out>
        nextPage = <optimized out>
        loc = {chunkOffset = <optimized out>, itemOffset = <optimized out>, chunkItemsCount = <optimized out>, chunkSize = <optimized out>, chunk = <optimized out>}
        loaded = <optimized out>
        loaded = <optimized out>
#4  iterate_internal_page (scan=scan@entry=0x55c09aa58660) at src/btree/scan.c:820
        downlink = 0
        __func__ = "iterate_internal_page"
#5  0x00007fbd48c92f5c in btree_seq_scan_getnext_internal (hint=0x7ffcbd4d17e0, tupleCsn=0x7ffcbd4d17d8, mctx=0x55c09aa2e4f0, scan=0x55c09aa58660) at src/btree/scan.c:1379
        tuple = {data = <optimized out>, formatFlags = <optimized out>}
        tuple = {data = <optimized out>, formatFlags = <optimized out>}
        __func__ = "btree_seq_scan_getnext_internal"
        histTuple = {data = <optimized out>, formatFlags = <optimized out>}
        leafHikey = {data = <optimized out>, formatFlags = <optimized out>}
        histHikey = {data = <optimized out>, formatFlags = <optimized out>}
        __item = <optimized out>
        leafHikey = {data = <optimized out>, formatFlags = <optimized out>}
        tuphdr = <optimized out>
        leafTuple = {data = <optimized out>, formatFlags = <optimized out>}
        cmp = <optimized out>
        __item = <optimized out>
        __errno_location = <optimized out>
#6  btree_seq_scan_getnext (scan=0x55c09aa58660, mctx=0x55c09aa2e4f0, tupleCsn=tupleCsn@entry=0x7ffcbd4d17d8, hint=hint@entry=0x7ffcbd4d17e0) at src/btree/scan.c:1438
        tuple = {data = <optimized out>, formatFlags = <optimized out>}
#7  0x00007fbd48cd9661 in orioledb_getnextslot (sscan=0x55c09a9d7938, direction=<optimized out>, slot=0x55c09aa2f590) at src/tableam/handler.c:1292
        tuple = {data = <optimized out>, formatFlags = <optimized out>}
        hint = {blkno = 3987, pageChangeCount = 0}
        tupleCsn = 4586
        scan = 0x55c09a9d7938
        descr = 0x55c09a967f80
        result = <optimized out>
#8  0x000055c099150da9 in table_scan_getnextslot (slot=0x55c09aa2f590, direction=ForwardScanDirection, sscan=<optimized out>) at ../../../src/include/access/tableam.h:1058
        __func__ = "table_scan_getnextslot"
        __errno_location = <optimized out>
#9  SeqNext (node=node@entry=0x55c09aa2f018) at nodeSeqscan.c:80
        scandesc = <optimized out>
        estate = <optimized out>
        direction = ForwardScanDirection
        slot = 0x55c09aa2f590
#10 0x000055c0991246e1 in ExecScanFetch (recheckMtd=0x55c099150d40 <SeqRecheck>, accessMtd=0x55c099150d50 <SeqNext>, node=0x55c09aa2f018) at execScan.c:133
        estate = 0x55c09aa2e610
        estate = <optimized out>
        epqstate = <optimized out>
        scanrelid = <optimized out>
        slot = <optimized out>
        slot = <optimized out>
        slot = <optimized out>
        slot = <optimized out>
#11 ExecScan (node=0x55c09aa2f018, accessMtd=0x55c099150d50 <SeqNext>, recheckMtd=0x55c099150d40 <SeqRecheck>) at execScan.c:182
        econtext = <optimized out>
        qual = 0x0
        projInfo = 0x0
#12 0x000055c09912cbf1 in ExecProcNode (node=0x55c09aa2f018) at ../../../src/include/executor/executor.h:259
No locals.
#13 fetch_input_tuple (aggstate=aggstate@entry=0x55c09aa2ead0) at nodeAgg.c:563
        slot = <optimized out>
#14 0x000055c099130387 in agg_retrieve_direct (aggstate=<optimized out>) at nodeAgg.c:2441
        econtext = 0x55c09aa2f2d8
        firstSlot = 0x55c09aa2f180
        numGroupingSets = <optimized out>
        node = 0x55c09a9d6f88
        tmpcontext = 0x55c09aa2eee8
        peragg = 0x55c09aa30420
        outerslot = <optimized out>
        nextSetSize = <optimized out>
        pergroups = 0x55c09aa3c5c8
        result = <optimized out>
        hasGroupingSets = false
        currentSet = <optimized out>
        numReset = 1
        i = <optimized out>
        node = <optimized out>
        econtext = <optimized out>
        tmpcontext = <optimized out>
        peragg = <optimized out>
        pergroups = <optimized out>
        outerslot = <optimized out>
        firstSlot = <optimized out>
        result = <optimized out>
        hasGroupingSets = <optimized out>
        numGroupingSets = <optimized out>
        currentSet = <optimized out>
        nextSetSize = <optimized out>
        numReset = <optimized out>
        i = <optimized out>
#15 ExecAgg (pstate=<optimized out>) at nodeAgg.c:2161
        node = <optimized out>
        result = 0x0
#16 0x000055c09911a643 in ExecProcNode (node=0x55c09aa2ead0) at ../../../src/include/executor/executor.h:259
No locals.
#17 ExecutePlan (execute_once=<optimized out>, dest=0x55c09a9d6e40, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x55c09aa2ead0, estate=0x55c09aa2e610) at execMain.c:1642
        slot = <optimized out>
        current_tuple_count = 0
        slot = <optimized out>
        current_tuple_count = <optimized out>
#18 standard_ExecutorRun (queryDesc=0x55c09a9d7788, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:363
        estate = 0x55c09aa2e610
        operation = CMD_SELECT
        dest = 0x55c09a9d6e40
        sendTuples = <optimized out>
        oldcontext = 0x55c09a9d6bd0
        __func__ = "standard_ExecutorRun"
#19 0x000055c09911ef24 in ParallelQueryMain (seg=0x55c09a97d7d8, toc=0x7fbd39c92000) at execParallel.c:1463
        fpes = 0x7fbd39cba140
        buffer_usage = <optimized out>
        wal_usage = <optimized out>
        receiver = 0x55c09a9d6e40
        queryDesc = 0x55c09a9d7788
        instrumentation = 0x0
        jit_instrumentation = 0x0
        instrument_options = <optimized out>
        area_space = <optimized out>
        area = <optimized out>
        pwcxt = {seg = 0x55c09a97d7d8, toc = 0x7fbd39c92000}
#20 0x000055c098ff0da7 in ParallelWorkerMain (main_arg=<optimized out>) at parallel.c:1495
        seg = 0x55c09a97d7d8
        toc = 0x7fbd39c92000
        fps = 0x7fbd39cc2940
        error_queue_space = <optimized out>
        mq = <optimized out>
        mqh = <optimized out>
        libraryspace = <optimized out>
        entrypointstate = <optimized out>
        library_name = <optimized out>
        function_name = <optimized out>
        entrypt = 0x55c09911ed10 <ParallelQueryMain>
        gucspace = <optimized out>
        combocidspace = <optimized out>
        tsnapspace = 0x0
        asnapspace = <optimized out>
        tstatespace = <optimized out>
        pendingsyncsspace = <optimized out>
        reindexspace = <optimized out>
        relmapperspace = <optimized out>
        uncommittedenumsspace = <optimized out>
        msgbuf = {data = 0x0, len = 8, maxlen = 1024, cursor = 75}
        session_dsm_handle_space = <optimized out>
        tsnapshot = <optimized out>
        asnapshot = 0x55c09a9d6cf0
        __func__ = "ParallelWorkerMain"
#21 0x000055c099217814 in StartBackgroundWorker () at bgworker.c:858
        local_sigjmp_buf = {{__jmpbuf = {94285715711344, 4008336339646964329, 0, 94285696466192, 94285715716080, 94285715711360, -4010171571819617687, -7196388355895172503}, __mask_was_saved = 1, __saved_mask = {__val = {18446744066192964099, 8192, 0, 94285715711360, 94285693258480, 94285696466192, 94285715467120, 94285715467120, 94285715475312, 94285696466192, 94285693286921, 94285715467344, 94285693258248, 94285696466192, 94285715711344, 0}}}}
        worker = 0x55c09a938e38
        entrypt = <optimized out>
        __func__ = "StartBackgroundWorker"
#22 0x000055c09921d3d3 in do_start_bgworker (rw=<optimized out>) at postmaster.c:5821
        worker_pid = <optimized out>
        worker_pid = <optimized out>
        __func__ = "do_start_bgworker"
        __errno_location = <optimized out>
        __errno_location = <optimized out>
#23 maybe_start_bgworkers () at postmaster.c:6045
        rw = <optimized out>
        num_launched = 0
        now = 0
        iter = {cur = 0x55c09a97a570, next = 0x55c09a97a320, prev = 0x55c0997325e0 <BackgroundWorkerList>}
#24 0x000055c09921ddbd in sigusr1_handler (postgres_signal_arg=<optimized out>) at postmaster.c:5210
        save_errno = 4
        __func__ = "sigusr1_handler"
#25 <signal handler called>
No locals.
#26 0x00007fbd4afd1f7a in __GI___select (nfds=nfds@entry=7, readfds=readfds@entry=0x7ffcbd4d22e0, writefds=writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0x7ffcbd4d2240) at ../sysdeps/unix/sysv/linux/select.c:41
        resultvar = 18446744073709551612
        sc_ret = <optimized out>
#27 0x000055c09921e47e in ServerLoop () at postmaster.c:1776
        timeout = {tv_sec = 59, tv_usec = 999931}
        rmask = {fds_bits = {96, 0 <repeats 15 times>}}
        selres = <optimized out>
        now = <optimized out>
        readmask = {fds_bits = {96, 0 <repeats 15 times>}}
        nSockets = 7
        last_lockfile_recheck_time = 1667917513
        last_touch_time = 1667917513
        __func__ = "ServerLoop"
#28 0x000055c0992200ab in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0x55c09a937d20) at postmaster.c:1484
        opt = <optimized out>
        status = <optimized out>
        userDoption = <optimized out>
        listen_addr_saved = <optimized out>
        i = <optimized out>
        output_config_variable = <optimized out>
        __func__ = "PostmasterMain"
#29 0x000055c098f40dc0 in main (argc=3, argv=0x55c09a937d20) at main.c:202
        do_check_root = <optimized out>
```

**Comment by homper** [comment]
Fixed on [fix_issue_113](https://github.com/orioledb/orioledb/tree/fix_issue_113)
