### ISSUE TITLE
Segfault: field->inputtype = opclass->inputtype

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#140]
sql/test.sql:

Tested on [github_issue_135](https://github.com/orioledb/orioledb/tree/github_issue_135)

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;

CREATE TABLE o_test_1(
	val_1 int
) USING orioledb;

CREATE INDEX o_test_1_ind_1
	ON o_test_1 (val_1, val_1) INCLUDE (val_1);
```

**Coredump**
```
#0  oFillFieldOpClassAndComparator (field=field@entry=0x562cdc51bf80, datoid=<optimized out>, opclassoid=0) at src/tableam/descr.c:985
985             field->inputtype = opclass->inputtype;
#0  oFillFieldOpClassAndComparator (field=field@entry=0x562cdc51bf80, datoid=<optimized out>, opclassoid=0) at src/tableam/descr.c:985
#1  0x00007fcda8295ee7 in o_index_fill_descr (descr=0x562cdc51bd90, oIndex=0x562cdc514c80) at src/catalog/o_indices.c:755
#2  0x00007fcda82b7985 in get_index_descr (ixOids=..., ixType=oIndexRegular, miss_ok=miss_ok@entry=false) at src/tableam/descr.c:844
#3  0x00007fcda82b7b05 in o_table_descr_fill_indices (table=0x562cdc5fbf10, descr=0x562cdc517750) at src/tableam/descr.c:907
#4  fill_table_descr (descr=0x562cdc517750, o_table=0x562cdc5fbf10) at src/tableam/descr.c:501
#5  0x00007fcda82b7f48 in recreate_table_descr (descr=descr@entry=0x562cdc517750) at src/tableam/descr.c:1317
#6  0x00007fcda82b98ce in recreate_table_descr_by_oids (oids=...) at src/tableam/descr.c:1338
#7  0x00007fcda8292111 in o_define_index (rel=rel@entry=0x7fcd993c2df8, indoid=indoid@entry=16440, reindex=<optimized out>, reindex@entry=false, skip_constraint_checks=skip_constraint_checks@entry=false, skip_build=skip_build@entry=false, context=context@entry=0x7fcda830aa6c <context>) at src/catalog/indices.c:720
#8  0x00007fcda82bbf79 in orioledb_define_index (rel=0x7fcd993c2df8, indoid=16440, reindex=<optimized out>, skip_constraint_checks=<optimized out>, skip_build=<optimized out>, arg=0x7fcda830aa6c <context>) at src/tableam/handler.c:1433
#9  0x0000562cdb18e1ad in table_extended_define_index (reindex=false, skip_constraint_checks=false, arg=<optimized out>, skip_build=false, indoid=16440, rel=0x7fcd993c2df8) at ../../../src/include/access/tableam.h:2338
#10 DefineIndex (relationId=relationId@entry=16435, stmt=stmt@entry=0x562cdc4ea1a8, indexRelationId=16440, indexRelationId@entry=0, parentIndexId=parentIndexId@entry=0, parentConstraintId=parentConstraintId@entry=0, is_alter_table=is_alter_table@entry=false, check_rights=true, check_not_in_use=true, skip_build=false, quiet=false) at indexcmds.c:1171
#11 0x0000562cdb384cc3 in ProcessUtilitySlow (pstate=0x562cdc61bdc0, pstmt=0x562cdc4ea558, queryString=0x562cdc4e9490 "CREATE INDEX o_test_1_ind_1\n\tON o_test_1 (val_1, val_1) INCLUDE (val_1);", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, qc=0x7ffe0dd43700, dest=<optimized out>) at utility.c:1542
#12 0x0000562cdb3840a1 in standard_ProcessUtility (pstmt=0x562cdc4ea558, queryString=0x562cdc4e9490 "CREATE INDEX o_test_1_ind_1\n\tON o_test_1 (val_1, val_1) INCLUDE (val_1);", readOnlyTree=<optimized out>, context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x562cdc4ea648, qc=0x7ffe0dd43700) at utility.c:1074
#13 0x0000562cdb3828bf in PortalRunUtility (portal=portal@entry=0x562cdc5780a0, pstmt=pstmt@entry=0x562cdc4ea558, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=0x562cdc4ea648, qc=0x7ffe0dd43700) at pquery.c:1158
#14 0x0000562cdb382a14 in PortalRunMulti (portal=portal@entry=0x562cdc5780a0, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x562cdc4ea648, altdest=altdest@entry=0x562cdc4ea648, qc=qc@entry=0x7ffe0dd43700) at pquery.c:1315
#15 0x0000562cdb3830a1 in PortalRun (portal=portal@entry=0x562cdc5780a0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x562cdc4ea648, altdest=altdest@entry=0x562cdc4ea648, qc=0x7ffe0dd43700) at pquery.c:791
#16 0x0000562cdb37ed92 in exec_simple_query (query_string=0x562cdc4e9490 "CREATE INDEX o_test_1_ind_1\n\tON o_test_1 (val_1, val_1) INCLUDE (val_1);") at postgres.c:1250
#17 0x0000562cdb380ade in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4544
#18 0x0000562cdb2e7d6a in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4510
#19 BackendStartup (port=<optimized out>) at postmaster.c:4238
#20 ServerLoop () at postmaster.c:1812
#21 0x0000562cdb2e8edb in PostmasterMain (argc=<optimized out>, argv=0x562cdc4e3c20) at postmaster.c:1484
#22 0x0000562cdb009760 in main (argc=8, argv=0x562cdc4e3c20) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by Tanyaevm** [comment]
sql/test.sql:

Tested on [github_issue_135](https://github.com/orioledb/orioledb/tree/github_issue_135)

Error with orioledb:

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;

CREATE TABLE o_test_1(
	val_1 int,
	val_2 int,
	val_3 int,
	val_4 int,
	val_5 int,
	val_6 int,
	val_7 int,
	val_8 int,
	val_9 int
) USING orioledb;

ALTER TABLE o_test_1 ADD PRIMARY KEY (val_6, val_7, val_8, val_9);

ALTER TABLE o_test_1 DROP COLUMN val_6;

CREATE INDEX o_test_1_ind_1
	ON o_test_1 (val_1, val_2, val_3, val_9, val_9) INCLUDE (val_8);

CREATE INDEX o_test_1_ind_2
	ON o_test_1 (val_1, val_2, val_4, val_9, val_9) INCLUDE (val_8, val_5);
```


**Coredump**
```
#0  oFillFieldOpClassAndComparator (field=field@entry=0x55aeed8ff610, datoid=<optimized out>, opclassoid=0) at src/tableam/descr.c:985
985             field->inputtype = opclass->inputtype;
#0  oFillFieldOpClassAndComparator (field=field@entry=0x55aeed8ff610, datoid=<optimized out>, opclassoid=0) at src/tableam/descr.c:985
#1  0x00007f4acf479ee7 in o_index_fill_descr (descr=0x55aeed8ff3c0, oIndex=0x55aeed8445d0) at src/catalog/o_indices.c:755
#2  0x00007f4acf49c203 in o_fill_tmp_table_descr (descr=descr@entry=0x7ffc8389abf0, o_table=o_table@entry=0x55aeed828c30) at src/tableam/descr.c:528
#3  0x00007f4acf476610 in o_define_index (rel=rel@entry=0x7f4ac05a4930, indoid=indoid@entry=16450, reindex=reindex@entry=false, skip_constraint_checks=skip_constraint_checks@entry=false, skip_build=skip_build@entry=false, context=context@entry=0x7f4acf4eea6c <context>) at src/catalog/indices.c:696
#4  0x00007f4acf49ff79 in orioledb_define_index (rel=0x7f4ac05a4930, indoid=16450, reindex=<optimized out>, skip_constraint_checks=<optimized out>, skip_build=<optimized out>, arg=0x7f4acf4eea6c <context>) at src/tableam/handler.c:1433
#5  0x000055aeec4cc1ad in table_extended_define_index (reindex=false, skip_constraint_checks=false, arg=<optimized out>, skip_build=false, indoid=16450, rel=0x7f4ac05a4930) at ../../../src/include/access/tableam.h:2338
#6  DefineIndex (relationId=relationId@entry=16435, stmt=stmt@entry=0x55aeed72f310, indexRelationId=16450, indexRelationId@entry=0, parentIndexId=parentIndexId@entry=0, parentConstraintId=parentConstraintId@entry=0, is_alter_table=is_alter_table@entry=false, check_rights=true, check_not_in_use=true, skip_build=false, quiet=false) at indexcmds.c:1171
#7  0x000055aeec6c2cc3 in ProcessUtilitySlow (pstate=0x55aeed860dc0, pstmt=0x55aeed72f6c0, queryString=0x55aeed72e490 "CREATE INDEX o_test_1_ind_1\n\tON o_test_1 (val_1, val_2, val_3, val_9, val_9) INCLUDE (val_8);", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, qc=0x7ffc8389b410, dest=<optimized out>) at utility.c:1542
#8  0x000055aeec6c20a1 in standard_ProcessUtility (pstmt=0x55aeed72f6c0, queryString=0x55aeed72e490 "CREATE INDEX o_test_1_ind_1\n\tON o_test_1 (val_1, val_2, val_3, val_9, val_9) INCLUDE (val_8);", readOnlyTree=<optimized out>, context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x55aeed72f7b0, qc=0x7ffc8389b410) at utility.c:1074
#9  0x000055aeec6c08bf in PortalRunUtility (portal=portal@entry=0x55aeed7bd0a0, pstmt=pstmt@entry=0x55aeed72f6c0, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=0x55aeed72f7b0, qc=0x7ffc8389b410) at pquery.c:1158
#10 0x000055aeec6c0a14 in PortalRunMulti (portal=portal@entry=0x55aeed7bd0a0, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x55aeed72f7b0, altdest=altdest@entry=0x55aeed72f7b0, qc=qc@entry=0x7ffc8389b410) at pquery.c:1315
#11 0x000055aeec6c10a1 in PortalRun (portal=portal@entry=0x55aeed7bd0a0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x55aeed72f7b0, altdest=altdest@entry=0x55aeed72f7b0, qc=0x7ffc8389b410) at pquery.c:791
#12 0x000055aeec6bcd92 in exec_simple_query (query_string=0x55aeed72e490 "CREATE INDEX o_test_1_ind_1\n\tON o_test_1 (val_1, val_2, val_3, val_9, val_9) INCLUDE (val_8);") at postgres.c:1250
#13 0x000055aeec6beade in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4544
#14 0x000055aeec625d6a in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4510
#15 BackendStartup (port=<optimized out>) at postmaster.c:4238
#16 ServerLoop () at postmaster.c:1812
#17 0x000055aeec626edb in PostmasterMain (argc=<optimized out>, argv=0x55aeed728c20) at postmaster.c:1484
#18 0x000055aeec347760 in main (argc=8, argv=0x55aeed728c20) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by homper** [comment]
Fixed on [github_issue_135](https://github.com/orioledb/orioledb/tree/github_issue_135)
