### ISSUE TITLE
Assert(!VARATT_IS_EXTERNAL(slot->tts_values[attindex])

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#143]
sql/test.sql:

Tested on [github_issue_135](https://github.com/orioledb/orioledb/tree/github_issue_135)

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;

CREATE TABLE o_test_1(
	val_1 text,
	val_2 text,
	val_3 text,
	val_4 text,
	val_5 text,
	val_6 text,
	val_7 text,
	val_8 text,
	val_9 text,
    UNIQUE (val_1, val_3,val_5, val_7,val_8, val_9)
)USING orioledb;

ALTER TABLE o_test_1 ADD COLUMN val_10 text;

INSERT INTO o_test_1
	SELECT 1 * 10 ^ v, 2 * 10 ^ v, 3 * 10 ^ v, 4 * 10 ^ v, 5 * 10 ^ v,
		   6 * 10 ^ v, 7 * 10 ^ v, 8 * 10 ^ v, 9 * 10 ^ v FROM
		   generate_series(0, 2) v;

ALTER TABLE o_test_1
  ADD CONSTRAINT o_test_1_ind
    PRIMARY KEY (val_1, val_3, val_10, val_7,val_8, val_9);
```

**Coredump**
```
#0  tts_orioledb_make_key (slot=slot@entry=0x55d87f80d6c0, descr=<optimized out>) at src/tuple/slot.c:139
139                                     Assert(!VARATT_IS_EXTERNAL(slot->tts_values[attindex]));
#0  tts_orioledb_make_key (slot=slot@entry=0x55d87f80d6c0, descr=<optimized out>) at src/tuple/slot.c:139
#1  0x00007f73026042bf in tts_orioledb_toast_sort_add (slot=slot@entry=0x55d87f80d6c0, descr=descr@entry=0x7ffd7a2b1450, sortstate=sortstate@entry=0x55d87f828fc0) at src/tuple/slot.c:1295
#2  0x00007f73025be0c0 in rebuild_indices (old_o_table=0x55d87f7e6320, old_descr=0x55d87f628750, o_table=0x55d87f7e76c0, descr=0x7ffd7a2b1450) at src/catalog/indices.c:1083
#3  0x00007f73025bf46e in o_define_index (rel=rel@entry=0x7f72f36f0ca0, indoid=indoid@entry=16442, reindex=reindex@entry=false, skip_constraint_checks=skip_constraint_checks@entry=false, skip_build=skip_build@entry=false, context=context@entry=0x7f7302637a6c <context>) at src/catalog/indices.c:691
#4  0x00007f73025e8f79 in orioledb_define_index (rel=0x7f72f36f0ca0, indoid=16442, reindex=<optimized out>, skip_constraint_checks=<optimized out>, skip_build=<optimized out>, arg=0x7f7302637a6c <context>) at src/tableam/handler.c:1433
#5  0x000055d87edfe1ad in table_extended_define_index (reindex=false, skip_constraint_checks=false, arg=<optimized out>, skip_build=false, indoid=16442, rel=0x7f72f36f0ca0) at ../../../src/include/access/tableam.h:2338
#6  DefineIndex (relationId=16435, stmt=stmt@entry=0x55d87f63f998, indexRelationId=16442, indexRelationId@entry=0, parentIndexId=parentIndexId@entry=0, parentConstraintId=parentConstraintId@entry=0, is_alter_table=is_alter_table@entry=true, check_rights=true, check_not_in_use=false, skip_build=false, quiet=false) at indexcmds.c:1171
#7  0x000055d87ee1590a in ATExecAddIndex (tab=tab@entry=0x55d87f723388, rel=rel@entry=0x7f72f36f0ca0, stmt=0x55d87f63f998, is_rebuild=<optimized out>, lockmode=8) at tablecmds.c:8623
#8  0x000055d87ee25374 in ATExecCmd (wqueue=0x7ffd7a2b1908, tab=0x55d87f723388, cmd=<optimized out>, lockmode=8, cur_pass=<optimized out>, context=0x7ffd7a2b1ac0) at tablecmds.c:5006
#9  0x000055d87ee26eab in ATRewriteCatalogs (context=0x7ffd7a2b1ac0, lockmode=8, wqueue=0x7ffd7a2b1908) at ../../../src/include/nodes/nodes.h:639
#10 ATController (parsetree=0x55d87f5fb3f8, rel=<optimized out>, cmds=<optimized out>, recurse=<optimized out>, lockmode=8, context=0x7ffd7a2b1ac0) at tablecmds.c:4456
#11 0x000055d87eff5b19 in ProcessUtilitySlow (pstate=0x55d87f723270, pstmt=0x55d87f5fb748, queryString=0x55d87f5fa490 "ALTER TABLE o_test_1\n  ADD CONSTRAINT o_test_1_ind\n    PRIMARY KEY (val_1, val_3, val_10, val_7,val_8, val_9);", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, qc=0x7ffd7a2b1fd0, dest=<optimized out>) at utility.c:1325
#12 0x000055d87eff40a1 in standard_ProcessUtility (pstmt=0x55d87f5fb748, queryString=0x55d87f5fa490 "ALTER TABLE o_test_1\n  ADD CONSTRAINT o_test_1_ind\n    PRIMARY KEY (val_1, val_3, val_10, val_7,val_8, val_9);", readOnlyTree=<optimized out>, context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x55d87f5fb838, qc=0x7ffd7a2b1fd0) at utility.c:1074
#13 0x000055d87eff28bf in PortalRunUtility (portal=portal@entry=0x55d87f6890a0, pstmt=pstmt@entry=0x55d87f5fb748, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=0x55d87f5fb838, qc=0x7ffd7a2b1fd0) at pquery.c:1158
#14 0x000055d87eff2a14 in PortalRunMulti (portal=portal@entry=0x55d87f6890a0, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x55d87f5fb838, altdest=altdest@entry=0x55d87f5fb838, qc=qc@entry=0x7ffd7a2b1fd0) at pquery.c:1315
#15 0x000055d87eff30a1 in PortalRun (portal=portal@entry=0x55d87f6890a0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x55d87f5fb838, altdest=altdest@entry=0x55d87f5fb838, qc=0x7ffd7a2b1fd0) at pquery.c:791
#16 0x000055d87efeed92 in exec_simple_query (query_string=0x55d87f5fa490 "ALTER TABLE o_test_1\n  ADD CONSTRAINT o_test_1_ind\n    PRIMARY KEY (val_1, val_3, val_10, val_7,val_8, val_9);") at postgres.c:1250
#17 0x000055d87eff0ade in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4544
#18 0x000055d87ef57d6a in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4510
#19 BackendStartup (port=<optimized out>) at postmaster.c:4238
#20 ServerLoop () at postmaster.c:1812
#21 0x000055d87ef58edb in PostmasterMain (argc=<optimized out>, argv=0x55d87f5f4c20) at postmaster.c:1484
#22 0x000055d87ec79760 in main (argc=8, argv=0x55d87f5f4c20) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by homper** [comment]
Fixed on [github_issue_135](https://github.com/orioledb/orioledb/tree/github_issue_135)
