### ISSUE TITLE
Segfault: invalid comparator

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#150]
sql/test.sql:

Tested on [github_issue_135](https://github.com/orioledb/orioledb/tree/github_issue_135)

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;
CREATE TABLE o_test_1(
    val_1 int, 
    val_2 int, 
    val_3 int, 
    val_4 box
)USING orioledb;
INSERT INTO o_test_1 SELECT x, 2*x, 3*x, box('1,1,1,1') 
    FROM generate_series(1,10) AS x;
CREATE UNIQUE INDEX ind_1 
    ON o_test_1 USING btree(val_1, val_2) 
        INCLUDE (val_3, val_4);
UPDATE o_test_1 SET val_2 = 2;
```

**Coredump**
```
#0  o_call_comparator (comparator=0x0, left=94662700281280, right=94662700386216) at src/tableam/descr.c:1215
1215            if (comparator->haveSortSupport)
#0  o_call_comparator (comparator=0x0, left=94662700281280, right=94662700386216) at src/tableam/descr.c:1215
#1  0x00007f0a964564cd in o_idx_cmp_value_bounds (bound1=bound1@entry=0x7ffeb19e12c0, bound2=bound2@entry=0x7ffeb19e15d0, field=field@entry=0x5618608e6fc0, equal=equal@entry=0x0) at src/tableam/tree.c:740
#2  0x00007f0a96456750 in o_idx_cmp (desc=desc@entry=0x5618608e6db0, p1=p1@entry=0x7ffeb19e1270, keyType1=keyType1@entry=BTreeKeyBound, p2=p2@entry=0x7ffeb19e1580, keyType2=keyType2@entry=BTreeKeyBound) at src/tableam/tree.c:864
#3  0x00007f0a96450542 in is_keys_eq (k2=0x7ffeb19e1580, k1=0x7ffeb19e1270, desc=0x5618608e6db0) at src/tableam/operations.c:1559
#4  o_update_secondary_indices (descr=descr@entry=0x5618608e2750, newSlot=newSlot@entry=0x561860a04630, oldSlot=oldSlot@entry=0x5618608e0b30, estate=estate@entry=0x5618609c95f0, oxid=oxid@entry=23, csn=29, update_all=false) at src/tableam/operations.c:678
#5  0x00007f0a96450d54 in o_tbl_indices_overwrite (arg=0x7ffeb19e1d70, hint=0x7ffeb19e1d48, csn=29, oxid=23, estate=0x5618609c95f0, newSlot=0x561860a04630, oldPkey=0x7ffeb19e1d50, descr=0x5618608e2750) at src/tableam/operations.c:787
#6  o_tbl_update (descr=descr@entry=0x5618608e2750, slot=slot@entry=0x561860a04630, estate=estate@entry=0x5618609c95f0, oldPkey=oldPkey@entry=0x7ffeb19e1dc0, rel=rel@entry=0x7f0a875507b0, oxid=23, csn=29, hint=0x7ffeb19e1d48, arg=0x7ffeb19e1d70) at src/tableam/operations.c:510
#7  0x00007f0a9644ca7a in orioledb_tuple_update (mstate=<optimized out>, rinfo=0x5618609c9a98, estate=0x5618609c95f0, tupleid=<optimized out>, slot=0x561860a04630, cid=<optimized out>, snapshot=0x5618608f7728, crosscheck=0x0, wait=true, tmfd=0x7ffeb19e2370, lockmode=0x7ffeb19e2254, update_indexes=0x7ffeb19e2251) at src/tableam/handler.c:564
#8  0x000056185fd72028 in table_extended_tuple_update (wait=true, update_indexes=0x7ffeb19e2251, lockmode=0x7ffeb19e2254, tmfd=0x7ffeb19e2370, crosscheck=<optimized out>, snapshot=<optimized out>, cid=<optimized out>, slot=0x561860a04630, tupleid=94662700319936, estate=0x5618609c95f0, resultRelInfo=0x5618609c9a98, mstate=<optimized out>) at ../../../src/include/access/tableam.h:2252
#9  ExecUpdateAct (context=0x7ffeb19e2340, resultRelInfo=0x5618609c9a98, tupleid=94662700319936, oldtuple=0x0, slot=0x561860a04630, canSetTag=<optimized out>, updateCxt=0x7ffeb19e2250) at nodeModifyTable.c:2020
#10 0x000056185fd70cd4 in ExecUpdate (context=0x7ffeb19e2340, resultRelInfo=0x5618609c9a98, tupleid=94662700319936, oldtuple=0x0, slot=0x561860a04630, canSetTag=<optimized out>) at nodeModifyTable.c:2249
#11 0x000056185fd728c0 in ExecModifyTable (pstate=<optimized out>) at nodeModifyTable.c:3820
#12 0x000056185fd404a3 in ExecProcNode (node=0x5618609c9880) at ../../../src/include/executor/executor.h:259
#13 ExecutePlan (execute_once=<optimized out>, dest=0x5618609ff588, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_UPDATE, use_parallel_mode=<optimized out>, planstate=0x5618609c9880, estate=0x5618609c95f0) at execMain.c:1642
#14 standard_ExecutorRun (queryDesc=0x5618609e6dc0, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:363
#15 0x00007f0a9641b02d in orioledb_ExecutorRun_hook (queryDesc=0x5618609e6dc0, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at src/catalog/ddl.c:666
#16 0x000056185fedefe0 in ProcessQuery (plan=<optimized out>, sourceText=0x5618608b4490 "UPDATE o_test_1 SET val_2 = 2;", params=0x0, queryEnv=0x0, dest=0x5618609ff588, qc=0x7ffeb19e2700) at pquery.c:160
#17 0x000056185fedfb22 in PortalRunMulti (portal=portal@entry=0x5618609430a0, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x5618609ff588, altdest=altdest@entry=0x5618609ff588, qc=qc@entry=0x7ffeb19e2700) at pquery.c:1277
#18 0x000056185fee00a1 in PortalRun (portal=portal@entry=0x5618609430a0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x5618609ff588, altdest=altdest@entry=0x5618609ff588, qc=0x7ffeb19e2700) at pquery.c:791
#19 0x000056185fedbd92 in exec_simple_query (query_string=0x5618608b4490 "UPDATE o_test_1 SET val_2 = 2;") at postgres.c:1250
#20 0x000056185feddade in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4544
#21 0x000056185fe44d6a in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4510
#22 BackendStartup (port=<optimized out>) at postmaster.c:4238
#23 ServerLoop () at postmaster.c:1812
#24 0x000056185fe45edb in PostmasterMain (argc=<optimized out>, argv=0x5618608aec20) at postmaster.c:1484
#25 0x000056185fb66760 in main (argc=8, argv=0x5618608aec20) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by rebelpower** [comment]
@Tanyaevm Can I get your help to reproduce this issue?

**Comment by Tanyaevm** [comment]
@rebelpower what were the problems?

**Comment by Tanyaevm** [comment]
Tested on [github_issue_135](https://github.com/orioledb/orioledb/tree/github_issue_135)

sql/test.sql:

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;
CREATE TABLE o_test_1(
    val_1 int,
    val_2 int,
    PRIMARY KEY (val_1) INCLUDE (val_2)
)USING orioledb;
INSERT INTO o_test_1 VALUES (1, 1);
UPDATE o_test_1 SET val_2 = 2 WHERE val_1 = 1;
```

**Coredump**
```
#0  o_call_comparator (comparator=0x0, left=1, right=2) at src/tableam/descr.c:1215
1215            if (comparator->haveSortSupport)
#0  o_call_comparator (comparator=0x0, left=1, right=2) at src/tableam/descr.c:1215
#1  0x00007fe5ccded8ed in o_idx_cmp_value_bounds (bound1=bound1@entry=0x7ffea9ec9200, bound2=bound2@entry=0x7ffea9ec8dd0, field=field@entry=0x561e7ecb35b0, equal=equal@entry=0x0) at src/tableam/tree.c:740
#2  0x00007fe5ccdedb70 in o_idx_cmp (desc=<optimized out>, p1=p1@entry=0x7ffea9ec91e0, keyType1=keyType1@entry=BTreeKeyBound, p2=p2@entry=0x7ffea9ec8db0, keyType2=keyType2@entry=BTreeKeyBound) at src/tableam/tree.c:864
#3  0x00007fe5ccde7a6b in is_keys_eq (k2=0x7ffea9ec8db0, k1=0x7ffea9ec91e0, desc=<optimized out>) at src/tableam/operations.c:1559
#4  o_tbl_update (descr=descr@entry=0x561e7ecae750, slot=slot@entry=0x561e7edc2630, estate=estate@entry=0x561e7eda2130, oldPkey=oldPkey@entry=0x7ffea9ec91e0, rel=rel@entry=0x7fe5bdee9be0, oxid=22, csn=28, hint=0x7ffea9ec9168, arg=0x7ffea9ec9190) at src/tableam/operations.c:508
#5  0x00007fe5ccde3c3a in orioledb_tuple_update (mstate=<optimized out>, rinfo=0x561e7eda25b8, estate=0x561e7eda2130, tupleid=<optimized out>, slot=0x561e7edc2630, cid=<optimized out>, snapshot=0x561e7ecc3728, crosscheck=0x0, wait=true, tmfd=0x7ffea9ec9790, lockmode=0x7ffea9ec9674, update_indexes=0x7ffea9ec9671) at src/tableam/handler.c:564
#6  0x0000561e7d868028 in table_extended_tuple_update (wait=true, update_indexes=0x7ffea9ec9671, lockmode=0x7ffea9ec9674, tmfd=0x7ffea9ec9790, crosscheck=<optimized out>, snapshot=<optimized out>, cid=<optimized out>, slot=0x561e7edc2630, tupleid=94688977364160, estate=0x561e7eda2130, resultRelInfo=0x561e7eda25b8, mstate=<optimized out>) at ../../../src/include/access/tableam.h:2252
#7  ExecUpdateAct (context=0x7ffea9ec9760, resultRelInfo=0x561e7eda25b8, tupleid=94688977364160, oldtuple=0x0, slot=0x561e7edc2630, canSetTag=<optimized out>, updateCxt=0x7ffea9ec9670) at nodeModifyTable.c:2020
#8  0x0000561e7d866cd4 in ExecUpdate (context=0x7ffea9ec9760, resultRelInfo=0x561e7eda25b8, tupleid=94688977364160, oldtuple=0x0, slot=0x561e7edc2630, canSetTag=<optimized out>) at nodeModifyTable.c:2249
#9  0x0000561e7d8688c0 in ExecModifyTable (pstate=<optimized out>) at nodeModifyTable.c:3820
#10 0x0000561e7d8364a3 in ExecProcNode (node=0x561e7eda23a0) at ../../../src/include/executor/executor.h:259
#11 ExecutePlan (execute_once=<optimized out>, dest=0x561e7edbeb80, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_UPDATE, use_parallel_mode=<optimized out>, planstate=0x561e7eda23a0, estate=0x561e7eda2130) at execMain.c:1642
#12 standard_ExecutorRun (queryDesc=0x561e7eda8570, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:363
#13 0x00007fe5ccdb2e2d in orioledb_ExecutorRun_hook (queryDesc=0x561e7eda8570, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at src/catalog/ddl.c:666
#14 0x0000561e7d9d4fe0 in ProcessQuery (plan=<optimized out>, sourceText=0x561e7ec80490 "UPDATE o_test_1 SET val_2 = 2 WHERE val_1 = 1;", params=0x0, queryEnv=0x0, dest=0x561e7edbeb80, qc=0x7ffea9ec9b20) at pquery.c:160
#15 0x0000561e7d9d5b22 in PortalRunMulti (portal=portal@entry=0x561e7ed0f0a0, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x561e7edbeb80, altdest=altdest@entry=0x561e7edbeb80, qc=qc@entry=0x7ffea9ec9b20) at pquery.c:1277
#16 0x0000561e7d9d60a1 in PortalRun (portal=portal@entry=0x561e7ed0f0a0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x561e7edbeb80, altdest=altdest@entry=0x561e7edbeb80, qc=0x7ffea9ec9b20) at pquery.c:791
#17 0x0000561e7d9d1d92 in exec_simple_query (query_string=0x561e7ec80490 "UPDATE o_test_1 SET val_2 = 2 WHERE val_1 = 1;") at postgres.c:1250
#18 0x0000561e7d9d3ade in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4544
#19 0x0000561e7d93ad6a in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4510
#20 BackendStartup (port=<optimized out>) at postmaster.c:4238
#21 ServerLoop () at postmaster.c:1812
#22 0x0000561e7d93bedb in PostmasterMain (argc=<optimized out>, argv=0x561e7ec7ac20) at postmaster.c:1484
#23 0x0000561e7d65c760 in main (argc=8, argv=0x561e7ec7ac20) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by homper** [comment]
Fixed on [github_issue_135](https://github.com/orioledb/orioledb/tree/github_issue_135)
