### ISSUE TITLE
Checkpoint blocks commit

### ISSUE THREAD

**Issue by ioxgrey** [orioledb/orioledb#16]
During pgbench setup run after data generation step pgbench backend stuck in commit
```
pgbench -i -s 200 postgres
dropping old tables...
creating tables...
generating data (client-side)...
20000000 of 20000000 tuples (100%) done (elapsed 47.60 s, remaining 0.00 s)
vacuuming...
creating primary keys...
done in 643.01 s (drop tables 0.05 s, create tables 0.01 s, client-side generate 619.78 s, vacuum 1.52 s, primary keys 21.65 s).
```
Compare "elapsed 47.60 s" to "client-side generate 619.78 s"

**Comment by ioxgrey** [comment]
Lock information
```
postgres=# select * from pg_locks where granted = 'f' OR (database IN (select database from pg_locks where granted = 'f'));
 locktype |  database  | relation | page | tuple | virtualxid | transactionid | classid | objid | objsubi
d | virtualtransaction |  pid  |        mode         | granted | fastpath |           waitstart          
 
----------+------------+----------+------+-------+------------+---------------+---------+-------+--------
--+--------------------+-------+---------------------+---------+----------+------------------------------
-
 userlock | 2147497624 |          |      |       |            |               |   16693 |     0 |        
0 | 3/0                | 36818 | AccessShareLock     | t       | f        | 
 userlock | 2147497624 |          |      |       |            |               |   16693 |     0 |        
0 | 6/0                | 53181 | AccessExclusiveLock | f       | f        | 2022-03-16 10:40:42.977295+03
(2 rows)

postgres=# 
```
backend backtrace
```
#0  0x00007f54fce489eb in epoll_wait () from /lib64/libc.so.6
#1  0x0000000000794602 in WaitEventSetWait ()
#2  0x0000000000794945 in WaitLatch ()
#3  0x00000000007ac617 in ProcSleep ()
#4  0x00000000007a1b3f in WaitOnLock ()
#5  0x00000000007a2c7d in LockAcquireExtended ()
#6  0x00007f54efb1435b in o_tables_rel_lock_extended () from /usr/local/pgsql/lib/orioledb.so
#7  0x00007f54efb08ed2 in btree_relnode_undo_callback () from /usr/local/pgsql/lib/orioledb.so
#8  0x00007f54efb354d6 in walk_undo_range () from /usr/local/pgsql/lib/orioledb.so
#9  0x00007f54efb355f1 in walk_undo_stack () from /usr/local/pgsql/lib/orioledb.so
#10 0x00007f54efb35974 in undo_xact_callback () from /usr/local/pgsql/lib/orioledb.so
#11 0x000000000057028c in CommitTransaction ()
#12 0x0000000000571395 in CommitTransactionCommand ()
#13 0x00000000007b28d5 in finish_xact_command ()
#14 0x00000000007b4a91 in exec_simple_query ()
#15 0x00000000007b60c4 in PostgresMain ()
#16 0x000000000073e9b3 in ServerLoop ()
#17 0x000000000073f748 in PostmasterMain ()
#18 0x00000000004eb8ad in main ()
```
Checkpointer backtrace
```
#0  0x00007f54fce401db in select () from /lib64/libc.so.6
#1  0x0000000000901d05 in pg_usleep ()
#2  0x0000000000732d6b in CheckpointWriteDelay ()
#3  0x00007f54efb17e1c in perform_writeback () from /usr/local/pgsql/lib/orioledb.so
#4  0x00007f54efb1c552 in checkpoint_ix () from /usr/local/pgsql/lib/orioledb.so
#5  0x00007f54efb1dc81 in checkpoint_tables_callback () from /usr/local/pgsql/lib/orioledb.so
#6  0x00007f54efb11507 in o_indices_foreach_oids () from /usr/local/pgsql/lib/orioledb.so
#7  0x00007f54efb1d3af in o_perform_checkpoint () from /usr/local/pgsql/lib/orioledb.so
#8  0x0000000000573169 in CheckPointGuts ()
#9  0x00000000005795b6 in CreateCheckPoint ()
#10 0x00000000007328df in CheckpointerMain ()
#11 0x0000000000587fdf in AuxiliaryProcessMain ()
#12 0x000000000073c2cf in StartChildProcess ()
#13 0x000000000073d5b2 in reaper ()
#14 <signal handler called>
#15 0x00007f54fce401db in select () from /lib64/libc.so.6
#16 0x000000000073def6 in ServerLoop ()
#17 0x000000000073f748 in PostmasterMain ()
#18 0x00000000004eb8ad in main ()
```
Non-default parameters
```
cat postgresql.auto.conf 
# Do not edit this file manually!
# It will be overwritten by the ALTER SYSTEM command.
shared_buffers = '2GB'
temp_buffers = '256MB'
work_mem = '256MB'
maintenance_work_mem = '1GB'
effective_io_concurrency = '16'
max_wal_size = '4GB'
random_page_cost = '1.2'
shared_preload_libraries = '"orioledb.so"'
orioledb.main_buffers = '2GB'
orioledb.free_tree_buffers = '128MB'
orioledb.checkpoint_completion_ratio = '0.5'
orioledb.max_io_concurrency = '64'
orioledb.bgwriter_num_workers = '2'
checkpoint_timeout = '30min'
orioledb.undo_buffers = '2GB'
default_table_access_method = 'orioledb'
synchronous_commit = 'off'
```
Looks like checkpointer try to hit checkpoint timeout. After that pgbench initial setup goes normal. 
During pgbench workload checkpoints are short and has a small influence on tps.

**Comment by akorotkov** [comment]
@ioxgrey, thank you very much for the report.
Could you please recheck this with 638df6444a?

**Comment by ioxgrey** [comment]
I did several tests with different pgbench scale factor. 
Generation elapsed time and client-side generate time are differ by fraction of second now.
OK!

**Comment by akorotkov** [comment]
Thank you for rechecking.
This will be merged to the next alpha release soon.

**Comment by akorotkov** [comment]
Should be fixed in alpha4.  Feel free to reopen if it's not.
