### ISSUE TITLE
Failure during writeback_put_extent()

### ISSUE THREAD

**Issue by akorotkov** [orioledb/orioledb#168]
https://github.com/orioledb/orioledb/actions/runs/4143392482/jobs/7165187722

```
Thread 1 (Thread 0x7fefd47d6740 (LWP 25301)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {4194304, 0, 0, 0, 0, 94592416019920, 4611686018427387904, 0, 0, 140668077978858, 0, 94592416019966, 128, 0, 140734909277840, 140668070495776}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007fefd64bb859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7fefd664ebf7, sa_sigaction = 0x7fefd664ebf7}, sa_mask = {__val = {1, 140668070854686, 3, 140734909278020, 12, 140668070854690, 2, 4048795666358541928, 7306586159289021232, 140734909278128, 7291948141156526717, 13726, 7675514287061315584, 140734909278112, 2107, 11}}, sa_flags = 1715890096, sa_restorer = 0x7fefd42e6a7d}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000560803a32168 in ExceptionalCondition (conditionName=conditionName@entry=0x7fefd42e6a7d "extent.len > 0", errorType=errorType@entry=0x7fefd42e5012 "FailedAssertion", fileName=fileName@entry=0x7fefd42e69d4 "src/btree/io.c", lineNumber=lineNumber@entry=2107) at assert.c:69
No locals.
#3  0x00007fefd4253d2c in writeback_put_extent (desc=desc@entry=0x56080571ddd0, downlink=downlink@entry=9223653511831486463, writeback=0x7fefd4346cb0 <io_writeback>) at src/btree/io.c:2107
        offset = {datoid = <optimized out>, relnode = <optimized out>, segno = <optimized out>, fileExtent = {len = <optimized out>, off = <optimized out>}, compressed = <optimized out>}
        blcksz = 0
        last_segno = <optimized out>
        extent = {len = 0, off = 281474976710655}
#4  0x00007fefd425772a in write_page (copy_blkno=false, evict=false, checkpoint_number=2, img=0x7fff6646c4b0 "$\004", blkno=2227, context=0x7fff66466c30) at src/btree/io.c:1408
        new_downlink = 9223653511831486463
        old_downlink = 0
        dirty_parent = true
        desc = 0x56080571ddd0
        parent_blkno = <optimized out>
        p = 0x7fefd2f1eb00 " \004"
        parent_loc = <optimized out>
        ionum = 294
        int_hdr = <optimized out>
        is_root = false
        context_index = <optimized out>
        page_desc = 0x7fefd35ce6f8
        parent_page = <optimized out>
        parent_change_count = 0
        desc = <optimized out>
        parent_blkno = <optimized out>
        parent_page = <optimized out>
        p = <optimized out>
        parent_loc = <optimized out>
        ionum = <optimized out>
        context_index = <optimized out>
        int_hdr = <optimized out>
        parent_change_count = <optimized out>
        page_desc = <optimized out>
        is_root = <optimized out>
        __func__ = "write_page"
        desc = <optimized out>
        ix_counter = <optimized out>
        new_downlink = <optimized out>
        old_downlink = <optimized out>
        dirty_parent = <optimized out>
        params = <optimized out>
        __errno_location = <optimized out>
        hikey = {data = <optimized out>, formatFlags = <optimized out>}
        __errno_location = <optimized out>
#5  walk_page (blkno=blkno@entry=2227, evict=evict@entry=false) at src/btree/io.c:1927
        page_desc = <optimized out>
        context = {desc = 0x56080571ddd0, img = "\260-\000\000\006\000\000\000\000\000\000\000\203\000\000\000\377\377\377\377\377\377\377?\003\000\000\000\000\000\000\000\377\377\377\377\377\377\377\377\001\000\000\000\b\000\001\000\001\000\003\000@\000\060\002\200\000\000\004", '\000' <repeats 452 times>..., parentImg = '\000' <repeats 6896 times>..., partial = {src = 0x7fefd2e2ab00 "\300-", isPartial = false, chunkIsLoaded = {true, false <repeats 37 times>}}, csn = 0, imgReadCsn = 0, imgUndoLoc = 4611686018427387903, index = 1, items = {{blkno = 2105, pageChangeCount = 0, locator = {chunkOffset = 0, itemOffset = 0, chunkItemsCount = 3, chunkSize = 48, chunk = 0x7fff66466e38}}, {blkno = 2537, pageChangeCount = 0, locator = {chunkOffset = 8, itemOffset = 9, chunkItemsCount = 12, chunkSize = 216, chunk = 0x7fefd318b3e0}}, {blkno = 0, pageChangeCount = 0, locator = {chunkOffset = 0, itemOffset = 0, chunkItemsCount = 0, chunkSize = 0, chunk = 0x0}} <repeats 30 times>}, lokey = {tuple = {data = 0x0, formatFlags = 0 '\000'}, fixedData = '\000' <repeats 2687 times>}, undoLokey = {tuple = {data = 0x0, formatFlags = 0 '\000'}, fixedData = '\000' <repeats 992 times>...}, flags = 1152}
        desc = <optimized out>
        p = <optimized out>
        parent_page = <optimized out>
        oids = {datoid = 13726, reloid = 16441, relnode = 16444}
        int_hdr = <optimized out>
        checkpoint_number = 2
        copy_blkno = false
        found = <optimized out>
        merge_tried = <optimized out>
        ionum = <optimized out>
        img = "$\004\000\000\003\000\000\000\000\000\000\000\004\000\000\000\030?p\002\000\000\000\000\[33](https://github.com/orioledb/orioledb/actions/runs/4143392482/jobs/7165187722#step:8:34)4\005\000\000\000\000\000\000\377\377\377\377\377\377\377\377\002\000\000\000\b\000\277\000\020\000\300\000\370\000\250\024@\000\200G\202\240\000H\304@\201H\006\[34](https://github.com/orioledb/orioledb/actions/runs/4143392482/jobs/7165187722#step:8:35)1\001IH\201\202I\212!\003J\314\301\203J\016b\004K\\\"\205K\262\362\005L\032\363\206L\202\363\aM\[35](https://github.com/orioledb/orioledb/actions/runs/4143392482/jobs/7165187722#step:8:36)2\[36](https://github.com/orioledb/orioledb/actions/runs/4143392482/jobs/7165187722#step:8:37)3\210MR\364\tN\256ԊN\020\305\vO\0[37](https://github.com/orioledb/orioledb/actions/runs/4143392482/jobs/7165187722#step:8:38)J\000\000\000\000\000\000)J\000\000\000\000\000\000\063J\000\000\000\000\000\000=J\000\000\000\000\000\000GJ\000\000\000\000\000\000QJ\000\000\000\000\000\000[J\000\000\000\000\000\000gJ\000\000\000\000\000\000tJ\000\000\000\000\000\000\204J\000\000\000\000\000\000\224"...
        is_root = <optimized out>
        retry = <optimized out>
#6  0x00007fefd42dd1e4 in ppool_run_clock (pool=pool@entry=0x7fefd434aa80 <page_pools>, evict=evict@entry=false, shutdown_requested=shutdown_requested@entry=0x7fefd434a61c <shutdown_requested>) at src/utils/page_pool.c:285
        blkno = 2227
        undoSize = 0
        haveRetainLoc = false
#7  0x00007fefd42dbc56 in bgwriter_main (main_arg=<optimized out>) at src/workers/bgwriter.c:149
        i = 2
        poolType = OPagePoolMain
        lastUsedLocation = <optimized out>
        writeInProgressLocation = <optimized out>
        _save_exception_stack = 0x7fff66470680
        _save_context_stack = 0x0
        _local_sigjmp_buf = {{__jmpbuf = {94592424031192, -91158309[38](https://github.com/orioledb/orioledb/actions/runs/4143392482/jobs/7165187722#step:8:39)640431848, 94592450847044, 9459242[39](https://github.com/orioledb/orioledb/actions/runs/4143392482/jobs/7165187722#step:8:40)26912, 94592451129456, 94592450871136, -3273881230617459432, -3264631954826312424}, __mask_was_saved = 0, __saved_mask = {__val = {1[40](https://github.com/orioledb/orioledb/actions/runs/4143392482/jobs/7165187722#step:8:41)734909318640, 14066807761[42](https://github.com/orioledb/orioledb/actions/runs/4143392482/jobs/7165187722#step:8:43)24, 140668077615961, 140668078080096, 94592451156440, 0, 14066807761[43](https://github.com/orioledb/orioledb/actions/runs/4143392482/jobs/7165187722#step:8:44)94, 94592450842480, 94592450847140, 94592451011024, 94592450847140, 94592420781306, 140668033677600, 94592451156[44](https://github.com/orioledb/orioledb/actions/runs/4143392482/jobs/7165187722#step:8:45)0, 9[45](https://github.com/orioledb/orioledb/actions/runs/4143392482/jobs/7165187722#step:8:46)92420904900, 1}}}}
        _do_rethrow = <optimized out>
        pool = 0x7fefd434aa80 <page_pools>
        rc = <optimized out>
        wake_events = 25
        need_eviction = false
        need_write = <optimized out>
        __func__ = "bgwriter_main"
#8  0x000056080386ddb7 in StartBackgroundWorker () at bgworker.c:875
        local_sigjmp_buf = {{__jmpbuf = {94592451016704, -9115830938630470376, 0, 94592423926912, 94592451129456, 94592450871136, -32738812306[46](https://github.com/orioledb/orioledb/actions/runs/4143392482/jobs/7165187722#step:8:47)819560, -9115815754695686888}, __mask_was_saved = 1, __saved_mask = {__val = {18446744066192964099, 8192, 0, 945924[50](https://github.com/orioledb/orioledb/actions/runs/4143392482/jobs/7165187722#step:8:51)871136, 94592420904544, 94592423926912, 94592450870688, 94592450870688, 94592450878880, 94592423926912, 94592420931929, 94592450870912, 94592420904312, 94592423926912, 945924[51](https://github.com/orioledb/orioledb/actions/runs/4143392482/jobs/7165187722#step:8:52)016704, 0}}}}
        worker = 0x5608056e6078
        entrypt = <optimized out>
        __func__ = "StartBackgroundWorker"
#9  0x000056080387a833 in do_start_bgworker (rw=<optimized out>) at postmaster.c:5872
        worker_pid = <optimized out>
        worker_pid = <optimized out>
        __func__ = "do_start_bgworker"
        __errno_location = <optimized out>
        __errno_location = <optimized out>
#10 maybe_start_bgworkers () at postmaster.c:6097
        rw = <optimized out>
        num_launched = 0
        now = 0
        iter = {cur = 0x56080570f800, next = 0x56080570e120, prev = 0x560803d4be20 <BackgroundWorkerList>}
#11 0x000056080387d4f6 in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0x5608056e4ec0) at postmaster.c:1421
        opt = <optimized out>
        status = <optimized out>
        userDoption = <optimized out>
        listen_addr_saved = true
        i = <optimized out>
        output_config_variable = <optimized out>
        __func__ = "PostmasterMain"
#12 0x00005608035af5[54](https://github.com/orioledb/orioledb/actions/runs/4143392482/jobs/7165187722#step:8:55) in main (argc=3, argv=0x[56](https://github.com/orioledb/orioledb/actions/runs/4143392482/jobs/7165187722#step:8:57)0[80](https://github.com/orioledb/orioledb/actions/runs/4143392482/jobs/7165187722#step:8:81)56e4ec0) at main.c:209
        do_check_root = <optimized out>
```

**Comment by akorotkov** [comment]
Assume we fix that in d050c43e4fb318919bc2f3571f3f2bc919f742eb.
