### ISSUE TITLE
Segfault: if (!scan->initialized)

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#188]
Tested on [main](https://github.com/orioledb/orioledb/tree/main)

sql/test.sql:

```sql
BEGIN;
SET LOCAL parallel_setup_cost = 0;
SET LOCAL parallel_tuple_cost = 0;
SET LOCAL min_parallel_table_scan_size = 0;
CREATE TABLE o_test_1 (
    val_1 int 
)USING orioledb;
EXPLAIN (ANALYZE) SELECT * FROM o_test_1;
COMMIT;
```

**Coredump**
```
#0  btree_seq_scan_getnext (scan=0x7f7f7f7f7f7f7f7f, mctx=0x55be64f0c490, tupleCsn=tupleCsn@entry=0x7ffeafb18978, hint=hint@entry=0x7ffeafb18980) at src/btree/scan.c:1465
1465            if (!scan->initialized)
#0  btree_seq_scan_getnext (scan=0x7f7f7f7f7f7f7f7f, mctx=0x55be64f0c490, tupleCsn=tupleCsn@entry=0x7ffeafb18978, hint=hint@entry=0x7ffeafb18980) at src/btree/scan.c:1465
#1  0x00007f14db123367 in orioledb_getnextslot (sscan=0x55be64ec9128, direction=<optimized out>, slot=0x55be64f0d348) at src/tableam/handler.c:1260
#2  0x000055be62c48b59 in table_scan_getnextslot (slot=0x55be64f0d348, direction=ForwardScanDirection, sscan=<optimized out>) at ../../../src/include/access/tableam.h:1058
#3  SeqNext (node=node@entry=0x55be64f0cfb8) at nodeSeqscan.c:80
#4  0x000055be62c1c0e1 in ExecScanFetch (recheckMtd=0x55be62c48af0 <SeqRecheck>, accessMtd=0x55be62c48b00 <SeqNext>, node=0x55be64f0cfb8) at execScan.c:133
#5  ExecScan (node=0x55be64f0cfb8, accessMtd=0x55be62c48b00 <SeqNext>, recheckMtd=0x55be62c48af0 <SeqRecheck>) at execScan.c:182
#6  0x000055be62c1934d in ExecProcNodeInstr (node=0x55be64f0cfb8) at execProcnode.c:480
#7  0x000055be62c12003 in ExecProcNode (node=0x55be64f0cfb8) at ../../../src/include/executor/executor.h:259
#8  ExecutePlan (execute_once=<optimized out>, dest=0x55be64ec88b8, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x55be64f0cfb8, estate=0x55be64f0c5b0) at execMain.c:1642
#9  standard_ExecutorRun (queryDesc=0x55be64ec8f78, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:363
#10 0x00007f14db0f269d in orioledb_ExecutorRun_hook (queryDesc=0x55be64ec8f78, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at src/catalog/ddl.c:666
#11 0x000055be62c168e4 in ParallelQueryMain (seg=0x55be64e6ef38, toc=0x7f14cc3b7000) at execParallel.c:1463
#12 0x000055be62ae47a7 in ParallelWorkerMain (main_arg=<optimized out>) at parallel.c:1495
#13 0x000055be62d0b284 in StartBackgroundWorker () at bgworker.c:858
#14 0x000055be62d10de3 in do_start_bgworker (rw=<optimized out>) at postmaster.c:5836
#15 maybe_start_bgworkers () at postmaster.c:6060
#16 0x000055be62d117cd in sigusr1_handler (postgres_signal_arg=<optimized out>) at postmaster.c:5217
#17 <signal handler called>
#18 0x00007f14dba79faa in __GI___select (nfds=nfds@entry=7, readfds=readfds@entry=0x7ffeafb19500, writefds=writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0x7ffeafb19460) at ../sysdeps/unix/sysv/linux/select.c:41
#19 0x000055be62d11e8e in ServerLoop () at postmaster.c:1776
#20 0x000055be62d13abb in PostmasterMain (argc=<optimized out>, argv=0x55be64e25c20) at postmaster.c:1484
#21 0x000055be62a34890 in main (argc=8, argv=0x55be64e25c20) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by Tanyaevm** [comment]
Tested on [main](https://github.com/orioledb/orioledb/tree/main)

sql/test.sql:

```sql
BEGIN;

SET LOCAL max_parallel_workers_per_gather TO 2;
SET LOCAL parallel_setup_cost TO 0;

CREATE TABLE o_test_1(
    val_1 int, 
    val_2 int, 
    val_3 text
)PARTITION BY RANGE(val_1);

CREATE TABLE o_test_2 
    PARTITION OF o_test_1 FOR VALUES FROM (0) TO (2);

CREATE TABLE o_test_3 
    PARTITION OF o_test_1 FOR VALUES FROM (2) TO (3) 
        PARTITION BY LIST (val_3);

CREATE TABLE o_test_4
    PARTITION OF o_test_3 FOR VALUES IN ('a', 'b', 'c');

CREATE TABLE o_test_5 
    PARTITION OF o_test_3 FOR VALUES IN ('d');

CREATE TABLE o_test_6(
    val_1 int,
    val_2 int, 
    val_3 text
)PARTITION BY RANGE (val_2);

CREATE TABLE o_test_7(
    val_1 int, 
    val_2 int,
    val_3 text
)USING orioledb;

CREATE TABLE o_test_8 
    PARTITION OF o_test_6 
        FOR VALUES FROM (4) TO (5);

ALTER TABLE o_test_6 
    ATTACH PARTITION o_test_7 
        FOR VALUES FROM (3) TO (4);

ALTER TABLE o_test_1 
    ATTACH PARTITION o_test_6 
        FOR VALUES FROM (6) TO (7);

INSERT INTO o_test_1 VALUES (1, 2, 'abc');

SELECT val_1 FROM o_test_1 GROUP BY val_1;

COMMIT;
```

**Coredump**
```
#0  0x00007f4b327d754f in free_btree_seq_scan (scan=0x7f7f7f7f7f7f7f7f) at src/btree/scan.c:1599
1599            BTreeDescr *desc = scan->desc;
#0  0x00007f4b327d754f in free_btree_seq_scan (scan=0x7f7f7f7f7f7f7f7f) at src/btree/scan.c:1599
#1  0x000055f6b19ba514 in ExecEndAppend (node=<optimized out>) at nodeAppend.c:398
#2  0x000055f6b19a8cb1 in ExecEndNode (node=<optimized out>) at execProcnode.c:596
#3  0x000055f6b19a2589 in ExecEndPlan (estate=0x55f6b34485f0, planstate=<optimized out>) at execMain.c:1481
#4  standard_ExecutorEnd (queryDesc=0x55f6b3447f78) at execMain.c:495
#5  0x000055f6b19a59b6 in ParallelQueryMain (seg=0x55f6b33a8f68, toc=0x7f4b23aa0000) at execParallel.c:1491
#6  0x000055f6b18737a7 in ParallelWorkerMain (main_arg=<optimized out>) at parallel.c:1495
#7  0x000055f6b1a9a284 in StartBackgroundWorker () at bgworker.c:858
#8  0x000055f6b1a9fde3 in do_start_bgworker (rw=<optimized out>) at postmaster.c:5836
#9  maybe_start_bgworkers () at postmaster.c:6060
#10 0x000055f6b1aa07cd in sigusr1_handler (postgres_signal_arg=<optimized out>) at postmaster.c:5217
#11 <signal handler called>
#12 0x00007f4b33163faa in __GI___select (nfds=nfds@entry=7, readfds=readfds@entry=0x7ffe7414a830, writefds=writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0x7ffe7414a790) at ../sysdeps/unix/sysv/linux/select.c:41
#13 0x000055f6b1aa0e8e in ServerLoop () at postmaster.c:1776
#14 0x000055f6b1aa2abb in PostmasterMain (argc=<optimized out>, argv=0x55f6b335fc20) at postmaster.c:1484
#15 0x000055f6b17c3890 in main (argc=8, argv=0x55f6b335fc20) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by homper** [comment]
Fixed on [github_issue_188](https://github.com/orioledb/orioledb/tree/github_issue_188)
