### ISSUE TITLE
EXPLAIN SIGSEGV

### ISSUE THREAD

**Issue by ioxgrey** [orioledb/orioledb#19]
I am start a transaction during pgbench initialization
```
pgbench -i -I gv -s 1000 postgres
generating data (client-side)...
100000000 of 100000000 tuples (100%) done (elapsed 223.70 s, remaining 0.00 s)
vacuuming...
done in 239.29 s (client-side generate 238.71 s, vacuum 0.58 s).
```
```
postgres=# begin;
BEGIN
postgres=*# select count(1) from pgbench_accounts;
   count
-----------
 100000000
(1 row)

postgres=*# explain (analyze, buffers) select * from pgbench_accounts ORDER BY aid DESC LIMIT 10;
                                                               QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.18..0.53 rows=10 width=97) (actual time=0.043..0.047 rows=10 loops=1)
   ->  Custom Scan (o_scan) on pgbench_accounts  (cost=0.18..196990.44 rows=5628364 width=97) (actual time=0.042..0.045 rows=20 loops=1)
         Backward index scan of: pgbench_accounts_pkey
         Primary pages: read=4
 Planning:
   Buffers: shared hit=30 dirtied=3
 Planning Time: 0.198 ms
 Execution Time: 0.067 ms
(8 rows)

postgres=*# explain (analyze, buffers) select count(1) from pgbench_accounts;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
postgres=#
```
```
nikor@orioledb:/db/14$ gdb postgres postgres.core
#0  0x00007fcd098c60d9 in find_tree_in_descr () from /usr/local/pgsql/lib/orioledb.so
(gdb) bt
#0  0x00007fcd098c60d9 in find_tree_in_descr () from /usr/local/pgsql/lib/orioledb.so
#1  0x00007fcd098a0586 in o_btree_read_page () from /usr/local/pgsql/lib/orioledb.so
#2  0x00007fcd0989215b in btree_find_read_page () from /usr/local/pgsql/lib/orioledb.so
#3  0x00007fcd09892f07 in find_page () from /usr/local/pgsql/lib/orioledb.so
#4  0x00007fcd098a41f4 in load_next_internal_page () from /usr/local/pgsql/lib/orioledb.so
#5  0x00007fcd098a5409 in make_btree_seq_scan_cb () from /usr/local/pgsql/lib/orioledb.so
#6  0x00007fcd098ca9b5 in orioledb_beginscan () from /usr/local/pgsql/lib/orioledb.so
#7  0x0000562f9b3ea762 in SeqNext ()
#8  0x0000562f9b3c4739 in ExecProcNodeInstr ()
#9  0x0000562f9b3cd841 in fetch_input_tuple ()
#10 0x0000562f9b3d02d6 in ExecAgg ()
#11 0x0000562f9b3c4739 in ExecProcNodeInstr ()
#12 0x0000562f9b3be842 in standard_ExecutorRun ()
#13 0x0000562f9b36ba9d in ExplainOnePlan ()
#14 0x0000562f9b36beac in ExplainOneQuery ()
#15 0x0000562f9b36c5a4 in ExplainQuery ()
#16 0x0000562f9b521569 in standard_ProcessUtility ()
#17 0x00007fcd098aa3db in orioledb_utility_command () from /usr/local/pgsql/lib/orioledb.so
#18 0x0000562f9b51fc9f in PortalRunUtility ()
#19 0x0000562f9b520037 in FillPortalStore ()
#20 0x0000562f9b5202fd in PortalRun ()
#21 0x0000562f9b51c593 in exec_simple_query ()
#22 0x0000562f9b51e410 in PostgresMain ()
#23 0x0000562f9b4a4251 in ServerLoop ()
#24 0x0000562f9b4a5082 in PostmasterMain ()
#25 0x0000562f9b248c00 in main ()
(gdb)
```

**Comment by akorotkov** [comment]
@ioxgrey, thank you for reporting.  Could you please post a PostgreSQL log?

**Comment by ioxgrey** [comment]
```2022-03-25 18:03:40.735 MSK [43464] LOG:  orioledb checkpoint 27 started
2022-03-25 18:04:02.045 MSK [43464] LOG:  orioledb checkpoint 27 complete
2022-03-25 18:04:40.401 MSK [43464] LOG:  orioledb checkpoint 28 started
2022-03-25 18:05:00.317 MSK [43464] LOG:  orioledb checkpoint 28 complete
2022-03-25 18:15:10.433 MSK [43458] LOG:  server process (PID 44158) was terminated by signal 11: Segmentation fault
2022-03-25 18:15:10.433 MSK [43458] DETAIL:  Failed process was running: explain (analyze, buffers) select count(1) from pgbench_accounts;
2022-03-25 18:15:10.433 MSK [43458] LOG:  terminating any other active server processes
2022-03-25 18:15:10.435 MSK [44183] FATAL:  the database system is in recovery mode
2022-03-25 18:15:10.452 MSK [43458] LOG:  all server processes terminated; reinitializing
```

**Comment by homper** [comment]
Could you, please, re-check on 0c26a09230f12a10127292e44c580c7ef7f37051.

**Comment by ioxgrey** [comment]
That's OK!
```
postgres=# BEGIN;
BEGIN
postgres=*# select count(1) from pgbench_accounts;
   count   
-----------
 100000000
(1 row)

postgres=*# explain (analyze, buffers) select * from pgbench_accounts ORDER BY aid DESC LIMIT 10;
                                                               QUERY PLAN                                
                                
---------------------------------------------------------------------------------------------------------
--------------------------------
 Limit  (cost=0.18..0.53 rows=10 width=97) (actual time=0.078..0.084 rows=10 loops=1)
   ->  Custom Scan (o_scan) on pgbench_accounts  (cost=0.18..196989.40 rows=5628364 width=97) (actual tim
e=0.076..0.081 rows=20 loops=1)
         Backward index scan of: pgbench_accounts_pkey
         Primary pages: read=4
 Planning:
   Buffers: shared hit=35 dirtied=1
 Planning Time: 0.280 ms
 Execution Time: 0.113 ms
(8 rows)

postgres=*# explain (analyze, buffers) select count(1) from pgbench_accounts;
                                                              QUERY PLAN                                 
                              
---------------------------------------------------------------------------------------------------------
------------------------------
 Aggregate  (cost=164157.55..164157.56 rows=1 width=8) (actual time=31169.927..31169.928 rows=1 loops=1)
   ->  Seq Scan on pgbench_accounts  (cost=0.00..150086.64 rows=5628364 width=0) (actual time=0.021..2545
2.934 rows=100000000 loops=1)
 Planning:
   Buffers: shared hit=1
 Planning Time: 0.154 ms
 Execution Time: 31169.969 ms
(6 rows)

postgres=*# 
```

**Comment by akorotkov** [comment]
The fix is released in alpha6.
