### ISSUE TITLE
Segfault: eacc->oids = descr->oids

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#213]
Tested on [pre_merge](https://github.com/orioledb/orioledb/tree/pre_merge)
Commit: a6c989848fac4f6c770b8452e534fb9664c89d5c

sql/test.sql:

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;

BEGIN;

SET LOCAL force_parallel_mode = on;

CREATE TABLE o_test_1(
    val_1 integer NOT NULL PRIMARY KEY
)USING orioledb;

EXPLAIN (ANALYZE, BUFFERS)
	SELECT * FROM o_test_1 ORDER BY val_1;

COMMIT;
```

**Coredump**
```
#0  eanalyze_counters_init (eacc=eacc@entry=0x5564a4497360, descr=0x0) at src/tableam/index_scan.c:409
409             eacc->oids = descr->oids;
#0  eanalyze_counters_init (eacc=eacc@entry=0x5564a4497360, descr=0x0) at src/tableam/index_scan.c:409
#1  0x00007fd47f4cfa7b in o_begin_custom_scan (node=0x5564a4497250, estate=0x5564a4496fe0, eflags=16) at src/tableam/scan.c:577
#2  0x00005564a203f947 in ExecInitCustomScan (cscan=cscan@entry=0x5564a4453430, estate=estate@entry=0x5564a4496fe0, eflags=eflags@entry=16) at nodeCustom.c:107
#3  0x00005564a202b2bf in ExecInitNode (node=node@entry=0x5564a4453430, estate=estate@entry=0x5564a4496fe0, eflags=eflags@entry=16) at execProcnode.c:290
#4  0x00005564a202461d in InitPlan (eflags=<optimized out>, queryDesc=<optimized out>) at execMain.c:944
#5  standard_ExecutorStart (queryDesc=<optimized out>, eflags=<optimized out>) at execMain.c:265
#6  0x00005564a202843b in ParallelQueryMain (seg=0x5564a43f9968, toc=0x7fd470776000) at execParallel.c:1432
#7  0x00005564a1ef6747 in ParallelWorkerMain (main_arg=<optimized out>) at parallel.c:1495
#8  0x00005564a211c894 in StartBackgroundWorker () at bgworker.c:858
#9  0x00005564a21223f3 in do_start_bgworker (rw=<optimized out>) at postmaster.c:5836
#10 maybe_start_bgworkers () at postmaster.c:6060
#11 0x00005564a2122ddd in sigusr1_handler (postgres_signal_arg=<optimized out>) at postmaster.c:5217
#12 <signal handler called>
#13 0x00007fd481addfaa in __GI___select (nfds=nfds@entry=7, readfds=readfds@entry=0x7ffcf6a63850, writefds=writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0x7ffcf6a637b0) at ../sysdeps/unix/sysv/linux/select.c:41
#14 0x00005564a212349e in ServerLoop () at postmaster.c:1776
#15 0x00005564a21250cb in PostmasterMain (argc=<optimized out>, argv=0x5564a43b0830) at postmaster.c:1484
#16 0x00005564a1e45bd0 in main (argc=8, argv=0x5564a43b0830) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by homper** [comment]
Fixed on [github_issue_214](https://github.com/orioledb/orioledb/tree/github_issue_214)
