### ISSUE TITLE
Segfault: index = index_open

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#220]
Tested on [main](https://github.com/orioledb/orioledb/tree/main)
Commit 293d24f660637eafac4925391e5bf04c996281a3

sql/test.sql:

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;

BEGIN;

SET LOCAL force_parallel_mode = ON;
SET enable_seqscan = OFF;

CREATE TABLE o_test_1(
	val_1 text,
	PRIMARY KEY(val_1)
)USING orioledb;

SELECT * FROM o_test_1;

COMMIT;
```

**Coredump**
```
#0  0x00007f2f27f24a05 in o_exec_custom_scan (node=0x5654fcf8b610) at src/tableam/scan.c:695
695                             Relation        index = index_open(ix_descr->oids.reloid,
#0  0x00007f2f27f24a05 in o_exec_custom_scan (node=0x5654fcf8b610) at src/tableam/scan.c:695
#1  0x00005654fbfe4ff3 in ExecProcNode (node=0x5654fcf8b610) at ../../../src/include/executor/executor.h:259
#2  ExecutePlan (execute_once=<optimized out>, dest=0x5654fcf476a8, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x5654fcf8b610, estate=0x5654fcf8b3a0) at execMain.c:1644
#3  standard_ExecutorRun (queryDesc=0x5654fcf48328, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:363
#4  0x00007f2f27eec855 in orioledb_ExecutorRun_hook (queryDesc=0x5654fcf48328, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at src/catalog/ddl.c:605
#5  0x00005654fbfe98c4 in ParallelQueryMain (seg=0x5654fceedd28, toc=0x7f2f191cb000) at execParallel.c:1463
#6  0x00005654fbeb7d77 in ParallelWorkerMain (main_arg=<optimized out>) at parallel.c:1495
#7  0x00005654fc0ddcb4 in StartBackgroundWorker () at bgworker.c:858
#8  0x00005654fc0e3813 in do_start_bgworker (rw=<optimized out>) at postmaster.c:5836
#9  maybe_start_bgworkers () at postmaster.c:6060
#10 0x00005654fc0e41fd in sigusr1_handler (postgres_signal_arg=<optimized out>) at postmaster.c:5217
#11 <signal handler called>
#12 0x00007f2f28874faa in __GI___select (nfds=nfds@entry=7, readfds=readfds@entry=0x7ffc02089560, writefds=writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0x7ffc020894c0) at ../sysdeps/unix/sysv/linux/select.c:41
#13 0x00005654fc0e48be in ServerLoop () at postmaster.c:1776
#14 0x00005654fc0e64eb in PostmasterMain (argc=<optimized out>, argv=0x5654fcea4c20) at postmaster.c:1484
#15 0x00005654fbe074f0 in main (argc=8, argv=0x5654fcea4c20) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by homper** [comment]
Fixed on [github_issue_214](https://github.com/orioledb/orioledb/tree/github_issue_214)
