### ISSUE TITLE
Segfault: if (attnum > slot->tts_nvalid)

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#223]
Tested on [main](https://github.com/orioledb/orioledb/tree/main)
Commit: 293d24f660637eafac4925391e5bf04c996281a3

sql/test.sql:

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;

CREATE TABLE o_test_1(
  a INT PRIMARY KEY, 
  b text
)PARTITION BY LIST (a);

CREATE TABLE o_test_2(
  a INT,
  CONSTRAINT fkey FOREIGN KEY (a) 
    REFERENCES o_test_1(a) ON UPDATE CASCADE ON DELETE CASCADE
)USING orioledb;

CREATE TABLE o_test_3
  PARTITION OF o_test_1 FOR VALUES IN (1, 2) 
    PARTITION BY LIST (a);

CREATE TABLE o_test_4 
  PARTITION OF o_test_1 FOR VALUES IN (3);

CREATE TABLE o_test_5 
  PARTITION OF o_test_1 FOR VALUES IN (4);

CREATE TABLE o_test_6(
  b text, 
  a int NOT NULL
)USING orioledb;

ALTER TABLE o_test_3 
  ATTACH PARTITION o_test_6 FOR VALUES IN (1);

CREATE TABLE o_test_7(
  b text, 
  a int NOT NULL
)USING orioledb;

ALTER TABLE o_test_3 
  ATTACH PARTITION o_test_7 FOR VALUES IN (2);

INSERT INTO o_test_1 
  VALUES (1, 'xxx'), (3, 'yyy');

UPDATE o_test_1 SET a = a + 1 RETURNING *;
```

**Coredump**
```
#0  slot_getattr (isnull=<synthetic pointer>, attnum=1, slot=0x0) at ../../../../src/include/executor/tuptable.h:386
386             if (attnum > slot->tts_nvalid)
#0  slot_getattr (isnull=<synthetic pointer>, attnum=1, slot=0x0) at ../../../../src/include/executor/tuptable.h:386
#1  ri_ExtractValues (slot=slot@entry=0x0, riinfo=riinfo@entry=0x5594254dfd10, rel_is_pk=<optimized out>, vals=<optimized out>, nulls=<optimized out>, rel=<optimized out>) at ri_triggers.c:2455
#2  0x0000559422fcacbd in ri_PerformCheck (riinfo=0x5594254dfd10, qkey=0x7ffd14f731a8, qplan=0x5594254fcdc0, fk_rel=0x7fa82cc94888, pk_rel=0x7fa82cc90fd8, oldslot=0x0, newslot=0x0, detectNewRows=true, expect_OK=9) at ri_triggers.c:2360
#3  0x0000559422fcc4e3 in RI_FKey_cascade_upd (fcinfo=<optimized out>) at ri_triggers.c:954
#4  0x0000559422d4ac0e in ExecCallTriggerFunc (trigdata=0x7ffd14f73710, tgindx=1, finfo=0x55942543f330, instr=0x0, per_tuple_context=0x5594254ee410) at trigger.c:2418
#5  0x0000559422d4bdc4 in AfterTriggerExecute (trigdesc=0x55942543f120, trigdesc=0x55942543f120, trig_tuple_slot2=0x0, trig_tuple_slot1=0x0, per_tuple_context=0x5594254ee410, instr=0x0, finfo=0x55942543f300, dst_relInfo=<optimized out>, src_relInfo=<optimized out>, relInfo=0x55942543ef08, event=0x5594254e0120, estate=0x55942543e230) at trigger.c:4530
#6  afterTriggerInvokeEvents (events=0x559425361b80, firing_id=1, estate=0x55942543e230, delete_ok=false) at trigger.c:4770
#7  0x0000559422d51c20 in AfterTriggerEndQuery (estate=estate@entry=0x55942543e230) at trigger.c:5125
#8  0x0000559422d722f0 in standard_ExecutorFinish (queryDesc=0x55942533f5c0) at execMain.c:438
#9  0x0000559422f0702e in ProcessQuery (plan=<optimized out>, sourceText=0x55942531e490 "UPDATE o_test_1 SET a = a + 1 RETURNING *;", params=0x0, queryEnv=0x0, dest=0x55942533f528, qc=0x7ffd14f738c0) at pquery.c:193
#10 0x0000559422f07b32 in PortalRunMulti (portal=portal@entry=0x5594253ad1b0, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=true, dest=dest@entry=0x55942533f528, altdest=0x559423338560 <donothingDR>, qc=qc@entry=0x7ffd14f738c0) at pquery.c:1277
#11 0x0000559422f07d5c in FillPortalStore (portal=0x5594253ad1b0, isTopLevel=<optimized out>) at pquery.c:1026
#12 0x0000559422f0810d in PortalRun (portal=portal@entry=0x5594253ad1b0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x5594254af3a8, altdest=altdest@entry=0x5594254af3a8, qc=0x7ffd14f73ad0) at pquery.c:763
#13 0x0000559422f03d62 in exec_simple_query (query_string=0x55942531e490 "UPDATE o_test_1 SET a = a + 1 RETURNING *;") at postgres.c:1250
#14 0x0000559422f05aec in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4593
#15 0x0000559422e7237a in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4517
#16 BackendStartup (port=<optimized out>) at postmaster.c:4245
#17 ServerLoop () at postmaster.c:1812
#18 0x0000559422e734eb in PostmasterMain (argc=<optimized out>, argv=0x559425318c20) at postmaster.c:1484
#19 0x0000559422b944f0 in main (argc=8, argv=0x559425318c20) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by homper** [comment]
Fixed on [github_issue_223](https://github.com/orioledb/orioledb/tree/github_issue_223)
