### ISSUE TITLE
very long shutdown checkpoint on a database contains compressed tables

### ISSUE THREAD

**Issue by vbp1** [orioledb/orioledb#24]
orioledb branch: fix_free_extents_vacated_bytes 

testing env: 2xCPU Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz  (72 cores), 256GB RAM, 4x1.6TB NVME INTEL SSDPEDMD016T4 RAID0 for pgdata, Altlinux c9f1
orioledb specific settings:
```
orioledb.main_buffers = 16GB
orioledb.free_tree_buffers = 1GB
orioledb.catalog_buffers = 256MB
orioledb.undo_buffers = 1GB
orioledb.recovery_pool_size = 4
orioledb.recovery_queue_size = 64MB
orioledb.checkpoint_completion_ratio = 0.9
orioledb.bgwriter_num_workers = 8
orioledb.max_io_concurrency = 64
```
steps to reproduce a problem:
1. fist of all we shoult create pgbench db containing compressed tables (in my case Scale factor = 75К)
2. then run pgbench --client=100 --jobs=100 --protocol=prepared --progress=10 --time=90 --username=pgbench --host=127.0.0.1 --port=5433 pgbench
3. then we should try to stop dbms: pg_ctl -D /pg_data stop

On my testing enviroinment, when db contains only uncompressed tables shutdown checkpoint takes 20-30 seconds, when db contains compressed tables shutdown checkpoint takes 15-30 minutes, sometimes it never finishes (at least I couldn't wait untill the end)

There is no errors or suspicious messages in the postgres log.
```
PID     USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
3531574 postgres  20   0   25.5g  20.2g  20.2g R 100.0   8.0   55:57.55 postgres: checkpointer performing shutdown checkpoint

perf top shows us:
Samples: 2K of event 'cycles', 99 Hz, Event count (approx.): 38390778263 lost: 0/0 drop: 0/0
Overhead  Shared Object                    Symbol
  39.95%  orioledb.so                      [.] get_extent
  10.53%  orioledb.so                      [.] btree_page_search
   8.18%  orioledb.so                      [.] find_page
   6.43%  orioledb.so                      [.] free_tree_len_off_cmp
   4.69%  orioledb.so                      [.] o_btree_read_page

# gdb -p 3531574 --ex bt --batch
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /lib64/libzstd.so.1
Try to install the hash file /usr/lib/debug/.build-id/5f/b21d91bc2846571353e13ad181b37f8dcbc9b4.debug
0x00007f95217071af in btree_page_search () from /usr/local/pgsql/lib/orioledb.so
#0  0x00007f95217071af in btree_page_search () from /usr/local/pgsql/lib/orioledb.so
#1  0x00007f9521707a76 in find_page () from /usr/local/pgsql/lib/orioledb.so
#2  0x00007f9521720a12 in get_extent () from /usr/local/pgsql/lib/orioledb.so
#3  0x00007f952170b364 in get_free_disk_extent () from /usr/local/pgsql/lib/orioledb.so
#4  0x00007f952170bf2b in perform_page_io () from /usr/local/pgsql/lib/orioledb.so
#5  0x00007f952173098c in checkpoint_ix () from /usr/local/pgsql/lib/orioledb.so
#6  0x00007f95217327cf in checkpoint_tables_callback () from /usr/local/pgsql/lib/orioledb.so
#7  0x00007f9521725587 in o_indices_foreach_oids () from /usr/local/pgsql/lib/orioledb.so
#8  0x00007f9521731eaf in o_perform_checkpoint () from /usr/local/pgsql/lib/orioledb.so
#9  0x0000000000572ae9 in CheckPointGuts ()
#10 0x0000000000579446 in CreateCheckPoint ()
#11 0x000000000073eac6 in CheckpointerMain ()
#12 0x000000000058864f in AuxiliaryProcessMain ()
#13 0x00000000007488bd in StartChildProcess ()
#14 0x0000000000749bf2 in reaper ()
#15 <signal handler called>
#16 0x00007f95218cb437 in __GI___select (nfds=9, readfds=0x7ffd45779210, writefds=0x0, exceptfds=0x0, timeout=0x7ffd45779160) at ../sysdeps/unix/sysv/linux/select.c:41
#17 0x000000000074a52d in ServerLoop ()
#18 0x000000000074bd98 in PostmasterMain ()
#19 0x00000000004e7a7d in main ()
[Inferior 1 (process 3531574) detached]
```

**Comment by akorotkov** [comment]
Could you please re-check this on https://github.com/orioledb/orioledb/commit/9aed798dbccb315b69e097a34659c1053fdd26b2?

**Comment by vbp1** [comment]
> Could you please re-check this on [9aed798](https://github.com/orioledb/orioledb/commit/9aed798dbccb315b69e097a34659c1053fdd26b2)?

https://github.com/orioledb/orioledb/issues/25#issuecomment-1116971233
