### ISSUE TITLE
Segfault: (VARATT_IS_COMPRESSED(datum) || VARATT_IS_EXTERNAL(datum)

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#263]
Tested on [main](https://github.com/orioledb/orioledb/tree/main)
Commit f409f97e6ac147b15808aae0478a3108cdd0730c

sql/test.sql:

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;

BEGIN;

CREATE TABLE o_test_1 (
  val_1 INT PRIMARY KEY,
  val_2 text
) USING orioledb;

INSERT INTO o_test_1 VALUES (1, 'a'), (2, 'b');

SET LOCAL enable_seqscan = off;
SET LOCAL enable_bitmapscan = off;

SELECT * FROM o_test_1 GROUP BY val_1;

COMMIT;
```

```
#0  pg_detoast_datum_packed (datum=0x0) at fmgr.c:1742
1742            if (VARATT_IS_COMPRESSED(datum) || VARATT_IS_EXTERNAL(datum))
#0  pg_detoast_datum_packed (datum=0x0) at fmgr.c:1742
#1  0x000055f90a9686c6 in text_to_cstring (t=0x0) at varlena.c:224
#2  0x000055f90a997554 in FunctionCall1Coll (flinfo=0x55f90c5d7880, collation=<optimized out>, arg1=<optimized out>) at fmgr.c:1124
#3  0x000055f90a503695 in printtup (slot=0x55f90c5d6fa8, self=0x55f90c59dea8) at printtup.c:357
#4  0x000055f90a6cd157 in ExecutePlan (execute_once=<optimized out>, dest=0x55f90c59dea8, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x55f90c5d5d88, estate=0x55f90c5d5b50) at execMain.c:1675
#5  standard_ExecutorRun (queryDesc=0x55f90c5b06f0, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:363
#6  0x00007f4566b5aec5 in orioledb_ExecutorRun_hook (queryDesc=0x55f90c5b06f0, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at src/catalog/ddl.c:1270
#7  0x000055f90a861aff in PortalRunSelect (portal=0x55f90c50a2b0, forward=<optimized out>, count=0, dest=<optimized out>) at pquery.c:924
#8  0x000055f90a8630d1 in PortalRun (portal=portal@entry=0x55f90c50a2b0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x55f90c59dea8, altdest=altdest@entry=0x55f90c59dea8, qc=0x7ffdbf734cb0) at pquery.c:768
#9  0x000055f90a85ee92 in exec_simple_query (query_string=0x55f90c479490 "SELECT * FROM o_test_1 GROUP BY val_1;") at postgres.c:1250
#10 0x000055f90a860c1c in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4593
#11 0x000055f90a7cd4aa in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4517
#12 BackendStartup (port=<optimized out>) at postmaster.c:4245
#13 ServerLoop () at postmaster.c:1812
#14 0x000055f90a7ce61b in PostmasterMain (argc=<optimized out>, argv=0x55f90c473c20) at postmaster.c:1484
#15 0x000055f90a4ef4f0 in main (argc=8, argv=0x55f90c473c20) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by homper** [comment]
Fixed on [github_issue_263](https://github.com/orioledb/orioledb/tree/github_issue_263)
