### ISSUE TITLE
ERROR:  unable to remove tuple from secondary index in "o_test_1"

### ISSUE THREAD

**Issue by qwerty1221o** [orioledb/orioledb#289]
Tested on [main](https://github.com/orioledb/orioledb/tree/main)
Commit b48b248641e911b55544acad4617a957768d4760

sql/test.sql:

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;

CREATE TEMP TABLE o_test_1(
	val_1 int
)USING orioledb;

INSERT INTO o_test_1(val_1)
	(SELECT val_1 - 5 FROM generate_series (1, 5) val_1);

CREATE INDEX ON o_test_1(val_1);

UPDATE o_test_1 SET val_1 = val_1 * 6;
```

**Error with orioledb**
```sql
ERROR:  unable to remove tuple from secondary index in "o_test_1"
DETAIL:  Unable to remove ('-24', '(0,1)') from index "o_test_1_val_1_idx"
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by Tanyaevm** [comment]
Tested on [main](https://github.com/orioledb/orioledb/tree/main)
Commit b48b248641e911b55544acad4617a957768d4760

t/example_test.py:

```py
def test_1(self):

		node = self.node
		node.start()
		
		with self.node as master:
			with self.getReplica().start() as replica:
				with master.connect() as con1:
					con1.begin()
					
					con1.execute("""

						CREATE EXTENSION IF NOT EXISTS orioledb;
						
						CREATE TEMP TABLE o_test_1(
							val_1 int PRIMARY KEY
						)USING orioledb;

						CREATE UNIQUE INDEX ind_1 ON o_test_1(val_1) INCLUDE (val_1);

						INSERT INTO o_test_1(val_1)
							(SELECT val_1 - 5 FROM generate_series (1, 5) val_1);
						
						CREATE TEMP TABLE o_test_2(
							LIKE o_test_1
						)USING orioledb;

					""")

					con1.execute("""
				

						DROP INDEX ind_1;

						DELETE FROM o_test_2 WHERE mod(val_1, 2) = 0;

						CREATE UNIQUE INDEX ON o_test_1(val_1) INCLUDE (val_1);

						CREATE UNIQUE INDEX ON o_test_2(val_1) INCLUDE (val_1);

						UPDATE o_test_1 SET val_1 = val_1 * 6 WHERE mod(val_1, 2) = 0;
									
					""")
				
					con1.commit()

					catchup_orioledb(replica)	
```

**Error with orioledb**
```sql
ERROR:  unable to remove tuple from secondary index in "o_test_1"
DETAIL:  Unable to remove ('-24') from index "o_test_1_val_1_val_11_idx"
```

**Stuck stack**
```
#0  0x00007f6919c9945a in epoll_wait (epfd=8, events=0x564920e73bc8, maxevents=1, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x000056491fcdf92d in WaitEventSetWaitBlock (nevents=1, occurred_events=0x7fffd8af4b50, cur_timeout=-1, set=0x564920e73b68) at latch.c:1489
#2  WaitEventSetWait (set=0x564920e73b68, timeout=-1, occurred_events=0x7fffd8af4b50, nevents=1, wait_event_info=<optimized out>) at latch.c:1435
#3  0x000056491fcdfd48 in WaitLatch (latch=<optimized out>, wakeEvents=wakeEvents@entry=33, timeout=timeout@entry=-1, wait_event_info=wait_event_info@entry=134217762) at latch.c:497
#4  0x000056491fcedf8f in ConditionVariableTimedSleep (wait_event_info=134217762, timeout=-1, cv=0x7f6913f85598) at condition_variable.c:163
#5  ConditionVariableTimedSleep (cv=0x7f6913f85598, timeout=-1, wait_event_info=134217762) at condition_variable.c:112
#6  0x00007f691930433d in _o_index_begin_parallel (isconcurrent=false, request=<optimized out>, buildstate=<synthetic pointer>) at src/catalog/indices.c:916
#7  build_secondary_index (o_table=o_table@entry=0x564920ebe290, descr=descr@entry=0x564920ebfd80, ix_num=<optimized out>, in_dedicated_recovery_worker=in_dedicated_recovery_worker@entry=true) at src/catalog/indices.c:1301
#8  0x00007f691932d968 in recovery_queue_process (id=<optimized out>, queue=<optimized out>) at src/recovery/worker.c:367
#9  recovery_worker_main (main_arg=<optimized out>) at src/recovery/worker.c:212
#10 0x000056491fc70494 in StartBackgroundWorker () at bgworker.c:858
#11 0x000056491fc760e9 in do_start_bgworker (rw=<optimized out>) at postmaster.c:5839
#12 maybe_start_bgworkers () at postmaster.c:6071
#13 0x000056491fc76a8d in sigusr1_handler (postgres_signal_arg=<optimized out>) at postmaster.c:5220
#14 <signal handler called>
#15 0x00007f6919c8efaa in __GI___select (nfds=nfds@entry=7, readfds=readfds@entry=0x7fffd8af5770, writefds=writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0x7fffd8af56d0) at ../sysdeps/unix/sysv/linux/select.c:41
#16 0x000056491fc7714e in ServerLoop () at postmaster.c:1777
#17 0x000056491fc78d7b in PostmasterMain (argc=<optimized out>, argv=0x564920e72ad0) at postmaster.c:1485
#18 0x000056491f9988d0 in main (argc=3, argv=0x564920e72ad0) at main.c:202
[Inferior 1 (process 702087) detached]
```

Doesn't always reproduced
Run as:
```
n=0; while [[ $n -lt 300 ]] && make USE_PGXS=1 testgrescheck_part_1 TESTGRESCHECKS_PART_1="t.example_test.TestClass.test_1"; do n=$((n+1)); done
```

Where:
- **t** - folder with python tests
- **example_test** - test file name
- **TestClass** - test class name
- **test_1** - test name
