### ISSUE TITLE
Test stuck with invalid data in assertEqual()

### ISSUE THREAD

**Issue by qwerty1221o** [orioledb/orioledb#290]
Tested on [main](https://github.com/orioledb/orioledb/tree/main)
Commit b48b248641e911b55544acad4617a957768d4760

t/example_test.py:

```py
def test_1(self):

		node = self.node
		node.start()
		
		with self.node as master:
			with self.getReplica().start() as replica:
				with master.connect() as con1:
					con1.begin()
					
					con1.execute("""

						CREATE EXTENSION IF NOT EXISTS orioledb;
						
						CREATE TABLE o_test_1(
							val_1 int, 
							val_2 int, 
							val_3 int
						)USING orioledb;

						INSERT INTO o_test_1(val_1, val_2, val_3)
							(SELECT val_1 + 10, val_1 - 4, val_1 FROM generate_series (1, 3) val_1);
						
						ALTER TABLE o_test_1 
							ADD PRIMARY KEY (val_1);

						CREATE INDEX ind_1 
							ON o_test_1 (val_3);
						CREATE INDEX ind_2 
							ON o_test_1 ((val_1 + val_3)) WHERE val_3 > 0;
						CREATE INDEX ind_3 
							ON o_test_1 ((val_3 + val_2)) WHERE val_3 > 1;
						CREATE INDEX ind_4 
							ON o_test_1 ((val_3 + val_3));

						ALTER TABLE o_test_1
							DROP CONSTRAINT o_test_1_pkey;	
						ALTER TABLE o_test_1 
							DROP COLUMN val_1, DROP COLUMN val_2;
					""")
				
					con1.commit()

					self.assertEqual([(1,), (2,), (3,1)], master.execute("""
									SELECT * FROM o_test_1;"""))

					catchup_orioledb(replica)	
```

**Expected result**
```sql
Lists differ: [(1,), (2,), (3, 1)] != [(1,), (2,), (3,)]
```
**Actual result**
```sql
Test  stack
```

**Stuck stack**
```
30      ../sysdeps/unix/sysv/linux/epoll_wait.c: No such file or directory.
#0  0x00007f52e8dc545a in epoll_wait (epfd=8, events=0x56494be2bbd8, maxevents=1, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x000056494b7ab92d in WaitEventSetWaitBlock (nevents=1, occurred_events=0x7ffd2dfc29d0, cur_timeout=-1, set=0x56494be2bb78) at latch.c:1489
#2  WaitEventSetWait (set=0x56494be2bb78, timeout=-1, occurred_events=0x7ffd2dfc29d0, nevents=1, wait_event_info=<optimized out>) at latch.c:1435
#3  0x000056494b7abd48 in WaitLatch (latch=<optimized out>, wakeEvents=wakeEvents@entry=33, timeout=timeout@entry=-1, wait_event_info=wait_event_info@entry=134217762) at latch.c:497
#4  0x000056494b7b9f8f in ConditionVariableTimedSleep (wait_event_info=134217762, timeout=-1, cv=0x7f52e30b1598) at condition_variable.c:163
#5  ConditionVariableTimedSleep (cv=0x7f52e30b1598, timeout=-1, wait_event_info=134217762) at condition_variable.c:112
#6  0x00007f52e843033d in _o_index_begin_parallel (isconcurrent=false, request=<optimized out>, buildstate=<synthetic pointer>) at src/catalog/indices.c:916
#7  build_secondary_index (o_table=o_table@entry=0x56494be762a0, descr=descr@entry=0x56494be77d90, ix_num=<optimized out>, in_dedicated_recovery_worker=in_dedicated_recovery_worker@entry=true) at src/catalog/indices.c:1301
#8  0x00007f52e8459968 in recovery_queue_process (id=<optimized out>, queue=<optimized out>) at src/recovery/worker.c:367
#9  recovery_worker_main (main_arg=<optimized out>) at src/recovery/worker.c:212
#10 0x000056494b73c494 in StartBackgroundWorker () at bgworker.c:858
#11 0x000056494b7420e9 in do_start_bgworker (rw=<optimized out>) at postmaster.c:5839
#12 maybe_start_bgworkers () at postmaster.c:6071
#13 0x000056494b742a8d in sigusr1_handler (postgres_signal_arg=<optimized out>) at postmaster.c:5220
#14 <signal handler called>
#15 0x00007f52e8dbafaa in __GI___select (nfds=nfds@entry=7, readfds=readfds@entry=0x7ffd2dfc3610, writefds=writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0x7ffd2dfc3570) at ../sysdeps/unix/sysv/linux/select.c:41
#16 0x000056494b74314e in ServerLoop () at postmaster.c:1777
#17 0x000056494b744d7b in PostmasterMain (argc=<optimized out>, argv=0x56494be2aae0) at postmaster.c:1485
#18 0x000056494b4648d0 in main (argc=3, argv=0x56494be2aae0) at main.c:202
[Inferior 1 (process 717757) detached]
```

Run as:
```
make USE_PGXS=1 testgrescheck_part_1 TESTGRESCHECKS_PART_1="t.example_test.TestClass.test_1"
```

Where:
- **t** - folder with python tests
- **example_test** - test file name
- **TestClass** - test class name
- **test_1** - test name

**Comment by za-arthur** [comment]
I can reproduce this. It seems a worker "postgres: startup recovering" gets stuck. Here is backtrace:
```
  * frame #0: 0x000000018d91ad04 libsystem_kernel.dylib`kevent + 8
    frame #1: 0x00000001011a44e0 postgres`WaitEventSetWait [inlined] WaitEventSetWaitBlock(set=0x0000000140809a10, cur_timeout=-1, occurred_events=0x000000016efaf008, nevents=1) at latch.c:1730:7 [opt]
    frame #2: 0x00000001011a4484 postgres`WaitEventSetWait(set=0x0000000140809a10, timeout=-1, occurred_events=<unavailable>, nevents=1, wait_event_info=<unavailable>) at latch.c:1516:8 [opt]
    frame #3: 0x00000001011a42b4 postgres`WaitLatch(latch=<unavailable>, wakeEvents=33, timeout=-1, wait_event_info=134217767) at latch.c:538:6 [opt]
    frame #4: 0x00000001011b18a0 postgres`ConditionVariableTimedSleep(cv=0x0000000110fe1d18, timeout=-1, wait_event_info=134217767) at condition_variable.c:163:10 [opt]
    frame #5: 0x00000001011b1774 postgres`ConditionVariableSleep(cv=<unavailable>, wait_event_info=<unavailable>) at condition_variable.c:98:9 [opt] [artificial]
    frame #6: 0x0000000101d7b618 orioledb.dylib`delay_if_queued_for_idxbuild at recovery.c:2909:3 [opt]
    frame #7: 0x0000000101d7c164 orioledb.dylib`recovery_finish_current_oxid(csn=9223372036854775806, ptr=50793945, worker_id=-1, sync=true) at recovery.c:1224:2 [opt]
    frame #8: 0x0000000101d79f54 orioledb.dylib`orioledb_redo [inlined] replay_container(startPtr="\U00000001&", endPtr="L\U00000001(\x97L\U00000001\x80\x96L\U00000001ؕL\U000000010\x95L\U00000001p\x94|\U00000001\xa8\x93\x90\U00000001\xe8\x92|\U00000001@\x92L\U00000001\x98\x91L\U00000001\xf0\x90L\U00000001H\x90L\U00000001\xa0\x8fL\U00000001\xf8\x8eL\U00000001P\x8eL\U00000001\xa8\x8dL\U00000001", single=false, xlogRecPtr=50793768) at recovery.c:2581:4 [opt]
    frame #9: 0x0000000101d79700 orioledb.dylib`orioledb_redo(record=<unavailable>) at recovery.c:676:3 [opt]
    frame #10: 0x0000000100f0876c postgres`PerformWalRecovery [inlined] ApplyWalRecord(xlogreader=0x0000000140828e38, record=0x0000000128038060, replayTLI=<unavailable>) at xlogrecovery.c:1993:2 [opt]
    frame #11: 0x0000000100f086a0 postgres`PerformWalRecovery at xlogrecovery.c:1822:4 [opt]
    frame #12: 0x0000000100ef97b0 postgres`StartupXLOG at xlog.c:5829:3 [opt]
    frame #13: 0x0000000101135e6c postgres`StartupProcessMain(startup_data=<unavailable>, startup_data_len=<unavailable>) at startup.c:263:2 [opt]
    frame #14: 0x000000010112f64c postgres`postmaster_child_launch(child_type=<unavailable>, startup_data=0x0000000000000000, startup_data_len=0, client_sock=0x0000000000000000) at launch_backend.c:277:3 [opt]
    frame #15: 0x00000001011319a8 postgres`StartChildProcess(type=B_STARTUP) at postmaster.c:3899:8 [opt]
    frame #16: 0x0000000101131620 postgres`PostmasterMain(argc=<unavailable>, argv=<unavailable>) at postmaster.c:1349:15 [opt]
    frame #17: 0x0000000101055cf4 postgres`main(argc=3, argv=0x0000600003914220) at main.c:197:3 [opt]
    frame #18: 0x000000018d5b6b98 dyld`start + 6076
```

**Comment by za-arthur** [comment]
Fixed by https://github.com/orioledb/orioledb/pull/493
