### ISSUE TITLE
Segfault: *index_tuples[0] = 0

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#295]
Tested on [main](https://github.com/orioledb/orioledb/tree/main)
Commit bd9ff8af842dab309e1cb3eaca38d43f322a9cbe

sql/test.sql:

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;

SET max_parallel_maintenance_workers = 0;

CREATE TEMP TABLE o_test_1(
    val_1 int,
    val_2 int
)USING orioledb;

INSERT INTO o_test_1(val_1) 
	VALUES(1);

CREATE INDEX ind_1 
	ON o_test_1 (val_2);
```

**Coredump**
```
#0  0x00007ff397008747 in build_secondary_index_worker_heap_scan (descr=descr@entry=0x5571e6062cd0, idx=idx@entry=0x5571e60673a8, poscan=poscan@entry=0x0, sortstates=sortstates@entry=0x5571e61711c8, heap_tuples=heap_tuples@entry=0x7ffe6a169dc0, index_tuples=index_tuples@entry=0x7ffe6a169dc8, progress=false) at src/catalog/indices.c:1239
1239            *index_tuples[0] = 0;
#0  0x00007ff397008747 in build_secondary_index_worker_heap_scan (descr=descr@entry=0x5571e6062cd0, idx=idx@entry=0x5571e60673a8, poscan=poscan@entry=0x0, sortstates=sortstates@entry=0x5571e61711c8, heap_tuples=heap_tuples@entry=0x7ffe6a169dc0, index_tuples=index_tuples@entry=0x7ffe6a169dc8, progress=false) at src/catalog/indices.c:1239
#1  0x00007ff39700949b in build_secondary_index (o_table=o_table@entry=0x5571e607c0e8, descr=descr@entry=0x5571e6062cd0, ix_num=ix_num@entry=0, in_dedicated_recovery_worker=in_dedicated_recovery_worker@entry=false) at src/catalog/indices.c:1330
#2  0x00007ff39700ad79 in o_define_index (rel=rel@entry=0x7ff387e2c128, indoid=indoid@entry=16444, reindex=<optimized out>, reindex@entry=false, skip_constraint_checks=skip_constraint_checks@entry=false, skip_build=skip_build@entry=false, context=context@entry=0x7ff39708cf24 <context>) at src/catalog/indices.c:685
#3  0x00007ff397039269 in orioledb_define_index (rel=0x7ff387e2c128, indoid=16444, reindex=<optimized out>, skip_constraint_checks=<optimized out>, skip_build=<optimized out>, arg=0x7ff39708cf24 <context>) at src/tableam/handler.c:1267
#4  0x00005571e4a1742c in table_define_index (arg=<optimized out>, skip_build=false, skip_constraint_checks=false, reindex=false, indoid=16444, rel=0x7ff387e2c128) at ../../../src/include/access/tableam.h:2164
#5  DefineIndex (relationId=relationId@entry=16439, stmt=stmt@entry=0x5571e60363f8, indexRelationId=16444, indexRelationId@entry=0, parentIndexId=parentIndexId@entry=0, parentConstraintId=parentConstraintId@entry=0, is_alter_table=is_alter_table@entry=false, check_rights=true, check_not_in_use=true, skip_build=false, quiet=false) at indexcmds.c:1168
#6  0x00005571e4c03b13 in ProcessUtilitySlow (pstate=0x5571e6161000, pstmt=0x5571e60367a8, queryString=0x5571e6035870 "CREATE INDEX ind_1 \n\tON o_test_1 (val_2);", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, qc=0x7ffe6a16a7a0, dest=<optimized out>) at utility.c:1542
#7  0x00005571e4c02ef1 in standard_ProcessUtility (pstmt=pstmt@entry=0x5571e60367a8, queryString=queryString@entry=0x5571e6035870 "CREATE INDEX ind_1 \n\tON o_test_1 (val_2);", readOnlyTree=<optimized out>, context=context@entry=PROCESS_UTILITY_TOPLEVEL, params=params@entry=0x0, queryEnv=queryEnv@entry=0x0, dest=0x5571e6036898, qc=0x7ffe6a16a7a0) at utility.c:1074
#8  0x00007ff39700481d in orioledb_utility_command (pstmt=0x5571e60367a8, queryString=0x5571e6035870 "CREATE INDEX ind_1 \n\tON o_test_1 (val_2);", readOnlyTree=<optimized out>, context=PROCESS_UTILITY_TOPLEVEL, params=0x0, env=0x0, dest=0x5571e6036898, qc=0x7ffe6a16a7a0) at src/catalog/ddl.c:1002
#9  0x00005571e4c0170f in PortalRunUtility (portal=portal@entry=0x5571e60c56e0, pstmt=pstmt@entry=0x5571e60367a8, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=0x5571e6036898, qc=0x7ffe6a16a7a0) at pquery.c:1158
#10 0x00005571e4c01864 in PortalRunMulti (portal=portal@entry=0x5571e60c56e0, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x5571e6036898, altdest=altdest@entry=0x5571e6036898, qc=qc@entry=0x7ffe6a16a7a0) at pquery.c:1315
#11 0x00005571e4c01ef1 in PortalRun (portal=portal@entry=0x5571e60c56e0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x5571e6036898, altdest=altdest@entry=0x5571e6036898, qc=0x7ffe6a16a7a0) at pquery.c:791
#12 0x00005571e4bfdae2 in exec_simple_query (query_string=0x5571e6035870 "CREATE INDEX ind_1 \n\tON o_test_1 (val_2);") at postgres.c:1250
#13 0x00005571e4bff8c2 in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4598
#14 0x00005571e4b6bc0a in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4528
#15 BackendStartup (port=<optimized out>) at postmaster.c:4256
#16 ServerLoop () at postmaster.c:1813
#17 0x00005571e4b6cd7b in PostmasterMain (argc=<optimized out>, argv=0x5571e6030be0) at postmaster.c:1485
#18 0x00005571e488c8d0 in main (argc=8, argv=0x5571e6030be0) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by Tanyaevm** [comment]
Tested on [main](https://github.com/orioledb/orioledb/tree/main)
Commit bd9ff8af842dab309e1cb3eaca38d43f322a9cbe

sql/test.sql:

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;

BEGIN;

SET LOCAL max_parallel_maintenance_workers = 0;

CREATE TABLE o_test_1(
  val_1 int4, 
  val_2 text
)USING orioledb;

CREATE UNIQUE INDEX ind_1 
  ON o_test_1(val_1);

INSERT INTO o_test_1 
  VALUES (1, 'a');

CREATE INDEX ind_2
  ON o_test_1(val_1, val_2);

COMMIT;
```

**Coredump**
```
#0  0x00007f5331e442f7 in build_secondary_index_worker_heap_scan (descr=descr@entry=0x5595dc57ccd0, idx=idx@entry=0x5595dc580d70, poscan=poscan@entry=0x0, sortstates=sortstates@entry=0x5595dc690130, heap_tuples=heap_tuples@entry=0x7ffcee002330, index_tuples=index_tuples@entry=0x7ffcee002338, progress=false) at src/catalog/indices.c:1237
1237            *index_tuples[0] = 0;
#0  0x00007f5331e442f7 in build_secondary_index_worker_heap_scan (descr=descr@entry=0x5595dc57ccd0, idx=idx@entry=0x5595dc580d70, poscan=poscan@entry=0x0, sortstates=sortstates@entry=0x5595dc690130, heap_tuples=heap_tuples@entry=0x7ffcee002330, index_tuples=index_tuples@entry=0x7ffcee002338, progress=false) at src/catalog/indices.c:1237
#1  0x00007f5331e4504b in build_secondary_index (o_table=o_table@entry=0x5595dc56fe00, descr=descr@entry=0x5595dc57ccd0, ix_num=ix_num@entry=1, in_dedicated_recovery_worker=in_dedicated_recovery_worker@entry=false) at src/catalog/indices.c:1328
#2  0x00007f5331e467fa in o_define_index (rel=rel@entry=0x7f5322c6d410, indoid=indoid@entry=16443, reindex=<optimized out>, reindex@entry=false, skip_constraint_checks=skip_constraint_checks@entry=false, skip_build=skip_build@entry=false, context=context@entry=0x7f5331ec7f04 <context>) at src/catalog/indices.c:684
#3  0x00007f5331e74aa9 in orioledb_define_index (rel=0x7f5322c6d410, indoid=16443, reindex=<optimized out>, skip_constraint_checks=<optimized out>, skip_build=<optimized out>, arg=0x7f5331ec7f04 <context>) at src/tableam/handler.c:1267
#4  0x00005595da1f642c in table_define_index (arg=<optimized out>, skip_build=false, skip_constraint_checks=false, reindex=false, indoid=16443, rel=0x7f5322c6d410) at ../../../src/include/access/tableam.h:2164
#5  DefineIndex (relationId=relationId@entry=16437, stmt=stmt@entry=0x5595dc550470, indexRelationId=16443, indexRelationId@entry=0, parentIndexId=parentIndexId@entry=0, parentConstraintId=parentConstraintId@entry=0, is_alter_table=is_alter_table@entry=false, check_rights=true, check_not_in_use=true, skip_build=false, quiet=false) at indexcmds.c:1168
#6  0x00005595da3e2b13 in ProcessUtilitySlow (pstate=0x5595dc685b20, pstmt=0x5595dc550820, queryString=0x5595dc54f870 "CREATE INDEX ind_2\n  ON o_test_1(val_1, val_2);", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, qc=0x7ffcee002d20, dest=<optimized out>) at utility.c:1542
#7  0x00005595da3e1ef1 in standard_ProcessUtility (pstmt=pstmt@entry=0x5595dc550820, queryString=queryString@entry=0x5595dc54f870 "CREATE INDEX ind_2\n  ON o_test_1(val_1, val_2);", readOnlyTree=<optimized out>, context=context@entry=PROCESS_UTILITY_TOPLEVEL, params=params@entry=0x0, queryEnv=queryEnv@entry=0x0, dest=0x5595dc550910, qc=0x7ffcee002d20) at utility.c:1074
#8  0x00007f5331e405ed in orioledb_utility_command (pstmt=0x5595dc550820, queryString=0x5595dc54f870 "CREATE INDEX ind_2\n  ON o_test_1(val_1, val_2);", readOnlyTree=<optimized out>, context=PROCESS_UTILITY_TOPLEVEL, params=0x0, env=0x0, dest=0x5595dc550910, qc=0x7ffcee002d20) at src/catalog/ddl.c:1002
#9  0x00005595da3e070f in PortalRunUtility (portal=portal@entry=0x5595dc5df6e0, pstmt=pstmt@entry=0x5595dc550820, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=0x5595dc550910, qc=0x7ffcee002d20) at pquery.c:1158
#10 0x00005595da3e0864 in PortalRunMulti (portal=portal@entry=0x5595dc5df6e0, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x5595dc550910, altdest=altdest@entry=0x5595dc550910, qc=qc@entry=0x7ffcee002d20) at pquery.c:1315
#11 0x00005595da3e0ef1 in PortalRun (portal=portal@entry=0x5595dc5df6e0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x5595dc550910, altdest=altdest@entry=0x5595dc550910, qc=0x7ffcee002d20) at pquery.c:791
#12 0x00005595da3dcae2 in exec_simple_query (query_string=0x5595dc54f870 "CREATE INDEX ind_2\n  ON o_test_1(val_1, val_2);") at postgres.c:1250
#13 0x00005595da3de8c2 in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4598
#14 0x00005595da34ac0a in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4528
#15 BackendStartup (port=<optimized out>) at postmaster.c:4256
#16 ServerLoop () at postmaster.c:1813
#17 0x00005595da34bd7b in PostmasterMain (argc=<optimized out>, argv=0x5595dc54abe0) at postmaster.c:1485
#18 0x00005595da06b8d0 in main (argc=8, argv=0x5595dc54abe0) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```
