### ISSUE TITLE
Segfault:  if (VARATT_IS_EXTENDED(datum))

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#311]
Tested on [main](https://github.com/orioledb/orioledb/tree/main)
Commit 63244571c15d8b59e73bc7caf201bd18c0c971bf

sql/test.sql:

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;
				 
BEGIN;

CREATE TABLE o_test_1(
	val_1 int
)USING orioledb;

CREATE OPERATOR FAMILY op_fam_1 USING btree;

CREATE OPERATOR <^ (
	LEFTARG = int4,
	RIGHTARG = int4,
	PROCEDURE = int4lt
);

CREATE OPERATOR =^ (
	LEFTARG = int4,
	RIGHTARG = int4,
	PROCEDURE = int4eq,
	COMMUTATOR = OPERATOR(=^)
);

CREATE FUNCTION func_1(a int, b int) RETURNS int
AS $$
	WITH s1 AS (
		select exists(select COUNT(*) from generate_series(1, 4)) vv, sum(v) OVER () vvv
			from generate_series(1, 4) v
	)
	SELECT a % COUNT(vv) - b % COUNT(vvv) FROM s1;
$$ LANGUAGE SQL IMMUTABLE;

CREATE OPERATOR CLASS op_class_1 FOR TYPE int
	USING btree FAMILY op_fam_1
	AS OPERATOR 1 <^, OPERATOR 3 =^,
	   FUNCTION 1 func_1(int, int);

CREATE INDEX ind_1 ON
	o_test_1(val_1 op_class_1);
	
INSERT INTO o_test_1 SELECT generate_series(1,10);

DROP OPERATOR CLASS op_class_1 USING btree CASCADE;

CREATE TYPE type_1 AS (arr char[]);

CREATE TYPE type_2 AS (
	val_1 int,
	val_2 type_1
);

ALTER TABLE o_test_1 ADD COLUMN rec_val type_2;

CREATE INDEX ind_2 ON o_test_1(rec_val);

EXPLAIN (COSTS OFF) SELECT * FROM o_test_1 ORDER BY rec_val
	USING OPERATOR(#<#);

COMMIT;
```

**Coredump**
```
#0  0x00005598d1a24867 in pg_detoast_datum (datum=0xa) at fmgr.c:1710
1710            if (VARATT_IS_EXTENDED(datum))
#0  0x00005598d1a24867 in pg_detoast_datum (datum=0xa) at fmgr.c:1710
#1  0x00005598d19b4870 in record_cmp (fcinfo=0x7ffd02a5a4f0) at rowtypes.c:808
#2  0x00005598d19b6c3d in btrecordcmp (fcinfo=<optimized out>) at rowtypes.c:1298
#3  0x00005598d1a2399e in FunctionCall2Coll (flinfo=flinfo@entry=0x5598d2832e38, collation=<optimized out>, arg1=arg1@entry=10, arg2=<optimized out>) at fmgr.c:1146
#4  0x00007f90b1efb77f in o_call_comparator (comparator=0x5598d2832e20, left=left@entry=10, right=<optimized out>) at src/tableam/descr.c:1289
#5  0x00007f90b1f0d6fc in o_idx_cmp_tuples (keyType2=BTreeKeyLeafTuple, tuple2=0x7ffd02a5a7c0, keyType1=2985350908, tuple1=0x7ffd02a5a7c0, id=0x5598d28303a8) at src/tableam/tree.c:660
#6  o_idx_cmp (desc=desc@entry=0x5598d28303c8, p1=p1@entry=0x7ffd02a5a7c0, keyType1=keyType1@entry=BTreeKeyNonLeafKey, p2=p2@entry=0x7ffd02a5a670, keyType2=keyType2@entry=BTreeKeyLeafTuple) at src/tableam/tree.c:873
#7  0x00007f90b1ea7dba in btree_page_search (desc=desc@entry=0x5598d28303c8, p=0x7f90adba2000 "\264", key=key@entry=0x7ffd02a5a7c0 "\270\001\246\002\375\177", keyType=keyType@entry=BTreeKeyNonLeafKey, partial=<optimized out>, locator=locator@entry=0x7ffd02a5a6f0) at src/btree/find.c:1263
#8  0x00007f90b1ea94f5 in refind_page (context=context@entry=0x7ffd02a5a7e0, key=key@entry=0x7ffd02a5a7c0, keyType=keyType@entry=BTreeKeyNonLeafKey, level=level@entry=0, _blkno=<optimized out>, _pageChangeCount=<optimized out>) at src/btree/find.c:762
#9  0x00007f90b1ec78cf in modify_undo_callback (location=33640, baseItem=0x7ffd02a60180, oxid=3, abort=<optimized out>, changeCountsValid=<optimized out>) at src/btree/undo.c:424
#10 0x00007f90b1f103cb in walk_undo_range (location=33640, toLoc=toLoc@entry=2305843009213693952, buf=buf@entry=0x7ffd02a60180, oxid=oxid@entry=3, abort_val=abort_val@entry=true, onCommitLocation=onCommitLocation@entry=0x7ffd02a60148, changeCountsValid=true) at src/transam/undo.c:537
#11 0x00007f90b1f1081b in walk_undo_stack (oxid=oxid@entry=3, toLocation=toLocation@entry=0x0, abortTrx=abortTrx@entry=true, changeCountsValid=changeCountsValid@entry=true) at /home/orioledb/pg15/include/postgresql/server/port/atomics.h:441
#12 0x00007f90b1f10931 in apply_undo_stack (oxid=oxid@entry=3, toLocation=toLocation@entry=0x0, changeCountsValid=changeCountsValid@entry=true) at src/transam/undo.c:684
#13 0x00007f90b1f10c8c in undo_xact_callback (event=XACT_EVENT_ABORT, arg=<optimized out>) at src/transam/undo.c:1186
#14 0x00005598d163632c in CallXactCallbacks (event=XACT_EVENT_ABORT) at xact.c:3684
#15 AbortTransaction () at xact.c:2842
#16 0x00005598d1636c95 in AbortCurrentTransaction () at xact.c:3359
#17 0x00005598d18ec249 in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4322
#18 0x00005598d1858c0a in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4528
#19 BackendStartup (port=<optimized out>) at postmaster.c:4256
#20 ServerLoop () at postmaster.c:1813
#21 0x00005598d1859d7b in PostmasterMain (argc=<optimized out>, argv=0x5598d27f9be0) at postmaster.c:1485
#22 0x00005598d15798d0 in main (argc=8, argv=0x5598d27f9be0) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by pashkinelfe** [comment]
This is reproducible at beta11.

First the error appear at EXPLAIN statement.
```
psql:test.sql:57: ERROR:  operator does not exist: type_2 #<# type_2
LINE 2:  USING OPERATOR(#<#);
               ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts. 

```
Then the whole transaction tries to roll back but op_class_1 that is used to create index is dropped at the time. I.e., DROP OPERATOR CLASS works in non-transactional way. 

https://github.com/orioledb/orioledb/issues/488
