### ISSUE TITLE
Segfault: o_emit_log_hook

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#352]
Tested on [pre_merge](https://github.com/orioledb/orioledb/tree/pre_merge)
Commit 96d2c957b6d4578e713a62f85e7ef4e477b15aad

sql/test.sql:

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;

BEGIN;

SET LOCAL force_parallel_mode = ON;
CREATE USER user_1;
CREATE TABLE o_test_1()USING orioledb;
ALTER TABLE o_test_1 OWNER TO user_1;
SET SESSION AUTHORIZATION user_1;
SELECT * FROM o_test_1;

COMMIT;
```

**Coredump**
```
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
65      ../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007f065810fd69 in o_emit_log_hook (edata=0x5588ca5a8260 <errordata>) at src/orioledb.c:856
#2  0x00005588ca269671 in EmitErrorReport () at elog.c:1533
#3  0x00005588ca137da9 in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4311
#4  0x00005588ca0a461a in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4531
#5  BackendStartup (port=<optimized out>) at postmaster.c:4259
#6  ServerLoop () at postmaster.c:1816
#7  0x00005588ca0a578b in PostmasterMain (argc=<optimized out>, argv=0x5588cb5babe0) at postmaster.c:1488
#8  0x00005588c9dc4b60 in main (argc=8, argv=0x5588cb5babe0) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by pashkinelfe** [comment]
Probably duplicate of #346  fixed at 66f171515fb14e
