### ISSUE TITLE
Regression test failed

### ISSUE THREAD

**Issue by TsinghuaLucky912** [orioledb/orioledb#363]
```shell
[postgres@localhost:~/orioledb/postgres/contrib/orioledb → main]$ make USE_PGXS=1 installcheck
/usr/bin/mkdir -p '/home/postgres/test/lib'
/usr/bin/mkdir -p '/home/postgres/test/share/extension'
/usr/bin/mkdir -p '/home/postgres/test/share/extension'
/usr/bin/install -c -m 755  orioledb.so '/home/postgres/test/lib/orioledb.so'
/usr/bin/install -c -m 644 .//orioledb.control '/home/postgres/test/share/extension/'
/usr/bin/install -c -m 644 .//orioledb--1.0.sql .//orioledb--1.0--1.1.sql .//orioledb--1.1--1.2.sql  '/home/postgres/test/share/extension/'
echo "# +++ regress check in  +++" && PATH="/tmp_install/home/postgres/test/bin:/home/postgres/orioledb/postgres/contrib/orioledb:$PATH" LD_LIBRARY_PATH="/tmp_install/home/postgres/test/lib:$LD_LIBRARY_PATH"  PGCTLTIMEOUT=900 /home/postgres/test/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --temp-instance=./tmp_check --inputdir=./ --bindir=     \
	--temp-config orioledb_regression.conf \
	--no-locale --encoding=UTF8 \
	btree_sys_check alter_type bitmap_scan btree_compression btree_print collate createas ddl explain foreign_keys generated getsomeattrs indices indices_build inherits ioc joins nulls opclass parallel_scan partial partition primary_key row_level_locks row_security subquery subtransactions tableam temp toast trigger types toast_column_compress
# +++ regress check in  +++
# using temp instance on port 61698 with PID 29594
...
# All 33 tests passed.
echo "# +++ isolation check in  +++" && PATH="/tmp_install/home/postgres/test/bin:/home/postgres/orioledb/postgres/contrib/orioledb:$PATH" LD_LIBRARY_PATH="/tmp_install/home/postgres/test/lib:$LD_LIBRARY_PATH"  PGCTLTIMEOUT=900 /home/postgres/test/lib/pgxs/src/makefiles/../../src/test/isolation/pg_isolation_regress --temp-instance=./tmp_check_iso --inputdir=./ --outputdir=output_iso --bindir=     \
	--temp-config orioledb_isolation.conf \
	--no-locale --encoding=UTF8 \
	bitmap_hist_scan btree_iterate btree_print_backend_id concurrent_update_delete fkeys included insert_fails ioc_deadlock ioc_lost_update isol_ddl isol_rc isol_rr isol_rr_bscan isol_rr_seqscan load_refind_page merge partition_move rightlink rll rll_deadlock rll_mix rll_subtrans table_lock_test uniq isol_merge
# +++ isolation check in  +++
# using temp instance on port 61698 with PID 33176
...
# All 25 tests passed.
PATH="/tmp_install/home/postgres/test/bin:/home/postgres/orioledb/postgres/contrib/orioledb:$PATH" LD_LIBRARY_PATH="/tmp_install/home/postgres/test/lib:$LD_LIBRARY_PATH"  PGCTLTIMEOUT=900 \
python3 -W ignore::DeprecationWarning -m unittest -v t/checkpointer_test.py
checkpointer_test (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: checkpointer_test (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: checkpointer_test
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/postgres/orioledb/postgres/contrib/orioledb/t/checkpointer_test.py", line 5, in <module>
    import testgres
ModuleNotFoundError: No module named 'testgres'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
make: *** [Makefile:207: t/checkpointer_test.py] Error 1
[postgres@localhost:~/orioledb/postgres/contrib/orioledb → main]$
```

```shell
[postgres@localhost:~/orioledb/postgres/contrib → patches16]$ git branch 
* patches16
[postgres@localhost:~/orioledb/postgres/contrib → patches16]$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

[postgres@localhost:~/orioledb/postgres/contrib → patches16]$ 
[postgres@localhost:~/orioledb/postgres/contrib → patches16]$ python3
python3     python3.6   python3.6m  
[postgres@localhost:~/orioledb/postgres/contrib → patches16]$ python3 --version
Python 3.6.8
[postgres@localhost:~/orioledb/postgres/contrib → patches16]$ 
```

**Comment by pashkinelfe** [comment]
Hi, @TsinghuaLucky912 !
> ModuleNotFoundError: No module named 'testgres'

Please  install prerequisites for  py test:
`pip3 install --upgrade psycopg2 six testgres==1.8.9 moto[s3] flask flask_cors boto3 pyOpenSSL`

You could consult on this in file https://github.com/orioledb/orioledb/blob/main/ci/prerequisites.sh
