### ISSUE TITLE
An error during recovery

### ISSUE THREAD

**Issue by akorotkov** [orioledb/orioledb#364]
Spotted here
https://github.com/orioledb/orioledb/actions/runs/9078106879/job/24944412826

```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140550468809856) at ./nptl/pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = 0x7fd474c4[34](https://github.com/orioledb/orioledb/actions/runs/9078106879/job/24944412826#step:8:35)80
        old_mask = {__val = {140728032826968, 140728032826976, 140728032826984, 140550470144554, 140728032827000, 94284859115253, 140728032818176, 140728032818168, 0, 140550459573926, 94284858011368, 838480695394304, 0, 112, 128, 140728032818368}}
        ret = <optimized out>
        pd = <optimized out>
        old_mask = <optimized out>
        ret = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
        resultvar = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        __private = <optimized out>
        __oldval = <optimized out>
        result = <optimized out>
#1  __pthread_kill_internal (signo=6, threadid=140550468809856) at ./nptl/pthread_kill.c:78
No locals.
#2  __GI___pthread_kill (threadid=140550468809856, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
No locals.
#3  0x00007fd474242476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#4  0x00007fd4742287f3 in __GI_abort () at ./stdlib/abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7ffdcc67f4ce, sa_sigaction = 0x7ffdcc67f4ce}, sa_mask = {__val = {2, 140550459989559, 1, 140550459996365, 3, 140728032818[35](https://github.com/orioledb/orioledb/actions/runs/9078106879/job/24944412826#step:8:36)6, 12, 140550459996[36](https://github.com/orioledb/orioledb/actions/runs/9078106879/job/24944412826#step:8:37)9, 2, 3486689038264434688, 3847822512380983094, 140728032818448, 3833236429663910835, 140728032818464, 782154486530283264, 140728032827000}}, sa_flags = 855, sa_restorer = 0x13}
        sigs = {__val = {32, 4, 1844674407[37](https://github.com/orioledb/orioledb/actions/runs/9078106879/job/24944412826#step:8:38)09551576, 140550470329056, 140728032831800, 94284857675776, 94284858047555, 94284859115216, 140728032831800, 37, 140550459983826, 1, 94284858047555, 6, 140550459996357, 3}}
#5  0x000055c067d38da8 in ExceptionalCondition (conditionName=conditionName@entry=0x7fd474574ac8 "!O_PAGE_IS(context->parentImg, LEAF)", errorType=errorType@entry=0x7fd474574012 "FailedAssertion", fileName=fileName@entry=0x7fd474574974 "src/btree/find.c", lineNumber=lineNumber@entry=855) at assert.c:69
No locals.
#6  0x00007fd4744b43b7 in find_right_page (context=context@entry=0x55c068711c00, hikey=hikey@entry=0x7ffdcc67f910) at src/btree/find.c:855
        __item = <optimized out>
        internalTuple = {data = 0x0, formatFlags = 0 '\000'}
        tuphdr = <optimized out>
        tup_loaded = <optimized out>
        desc = 0x7fd4745e4370 <sysTreesDescrs+432>
        loc = {chunkOffset = 0, itemOffset = 1, chunkItemsCount = 2, chunkSize = 48, chunk = 0x55c068711e08}
        parentItem = 0x55c068715c58
        item = 0x55c068715c70
        level = 0
        params = <optimized out>
        readCsn = 0x0
#7  0x00007fd4744c1675 in btree_iterator_check_load_next_page (it=it@entry=0x55c068711c00) at src/btree/iterator.c:733
        step_result = <optimized out>
        context = 0x55c068711c00
        img = 0x55c068711c08 "\020"
        hImg = 0x55c068717490 '\177' <repeats 200 times>...
        header = 0x55c068711c08
        desc = 0x7fd4745e4370 <sysTreesDescrs+432>
        key_buf = {tuple = {data = 0x7ffdcc67f920 "\005", formatFlags = 0 '\000'}, fixedData = "\005\000\000\000\070@\000\000B@\000\000\300\024\000\000\b", '\000' <repeats 487 times>...}
#8  0x00007fd4744c2d28 in o_btree_iterator_fetch_internal (tupleCsn=0x0, it=0x55c068711c00) at src/btree/iterator.c:633
        context = 0x55c068711c00
        img = 0x55c068711c08 "\020"
        itup = {data = 0x1000 <error: Cannot access memory at address 0x1000>, formatFlags = 53 '5'}
        desc = 0x7fd4745e4370 <sysTreesDescrs+432>
        leaf_item = <optimized out>
        hImg = 0x55c068717490 '\177' <repeats 200 times>...
        result = <optimized out>
        htup = {data = 0x55c06865eee0 '\177' <repeats 200 times>..., formatFlags = 0 '\000'}
        cmp = <optimized out>
        desc = <optimized out>
        context = <optimized out>
        leaf_item = <optimized out>
        img = <optimized out>
        hImg = <optimized out>
        result = <optimized out>
        itup = <optimized out>
        htup = <optimized out>
        cmp = <optimized out>
        __item = <optimized out>
        __item = <optimized out>
#9  o_btree_iterator_fetch (it=it@entry=0x55c068711c00, tupleCsn=tupleCsn@entry=0x0, end=end@entry=0x7fd4745e36d0 <nextKey.5>, endType=endType@entry=BTreeKeyBound, endIsIncluded=endIsIncluded@entry=false, hint=hint@entry=0x0) at src/btree/iterator.c:473
        desc = 0x7fd4745e4370 <sysTreesDescrs+432>
        result = {data = 0x55c06865eee0 '\177' <repeats 200 times>..., formatFlags = 0 '\000'}
#10 0x00007fd47455bd7c in generic_toast_get_any_common (api=api@entry=0x7fd4745b85c0 <oTablesToastAPI>, key=key@entry=0x7ffdcc680580 "\005", data_size=data_size@entry=0x7ffdcc680578, arg=arg@entry=0x7fd4745e4370 <sysTreesDescrs+432>, it=it@entry=0x55c068711c00, found_key=found_key@entry=0x7ffdcc680570, csn=1) at src/tuple/toast.c:773
        chunk_size = <optimized out>
        nextKey = <optimized out>
        tuple = <optimized out>
        str = {data = 0x55c0686bd220 "\005", len = 4816, maxlen = 8192, cursor = 0}
#11 0x00007fd47455e853 in generic_toast_get_any_with_key (api=api@entry=0x7fd4745b85c0 <oTablesToastAPI>, key=key@entry=0x7ffdcc680580, data_size=data_size@entry=0x7ffdcc680578, csn=csn@entry=1, arg=0x7fd4745e4370 <sysTreesDescrs+432>, found_key=found_key@entry=0x7ffdcc680570) at src/tuple/toast.c:841
        desc = <optimized out>
        it = 0x55c068711c00
        data = <optimized out>
#12 0x00007fd474503f68 in o_tables_get_by_oids_and_version (oids=..., version=version@entry=0x7fd46b405d88) at src/catalog/o_tables.c:1070
        key = {oids = {datoid = 5, reloid = 16440, relnode = 16450}, offset = 0, version = 4}
        found_key = 0x55c068660310
        result = <optimized out>
        dataLength = 4816
        oTable = <optimized out>
#13 0x00007fd474526e9d in recovery_queue_process (id=3, queue=0x55c06865e690) at src/recovery/worker.c:353
        msg = 0x7fd46b405d68
        o_table = <optimized out>
        old_o_table = 0x0
        tuple_len = <optimized out>
        finished = false
        oxid = <optimized out>
        oxid_csn_record = <optimized out>
        csn_record = <optimized out>
        descr = 0x0
        data = 0x7fd46b405d68 ""
        oids = {datoid = 0, reloid = 0, relnode = 0}
        recovery_header = 0x7fd46b405d68
        indexDescr = 0x0
        ix_type = <optimized out>
        data_size = 44
        data_pos = 0
        oxid_csn_record = <optimized out>
        csn_record = <optimized out>
        recovery_header = <optimized out>
        descr = <optimized out>
        indexDescr = <optimized out>
        data = <optimized out>
        ix_type = <optimized out>
        oids = <optimized out>
        tuple_len = <optimized out>
        data_size = <optimized out>
        data_pos = <optimized out>
        finished = <optimized out>
        oxid = <optimized out>
        __func__ = "recovery_queue_process"
        tuple = <optimized out>
        msg = <optimized out>
        o_table = <optimized out>
        old_o_table = <optimized out>
        o_descr = <optimized out>
        old_o_descr = <optimized out>
        msg = <optimized out>
        msg = <optimized out>
#14 recovery_worker_main (main_arg=3) at src/recovery/worker.c:209
        id = 3
        _save_exception_stack = 0x7ffdcc680790
        _save_context_stack = 0x0
        _local_sigjmp_buf = {{__jmpbuf = {0, -7631080635410296985, 94284873111812, 94284867463316, 94284873577312, 94284873577328, -4439497022092226713, -445[38](https://github.com/orioledb/orioledb/actions/runs/9078106879/job/24944412826#step:8:39)35121156698265}, __mask_was_saved = 0, __saved_mask = {__val = {782154486530283264, 1, 140550470326856, 0, 94284873111812, 94284873577312, 140550458640324, 41584, 94284873111812, 94284873273808, 94284873111812, 94284864033754, 94284864163515, 94284873589920, 1, 94284873585496}}}}
        _do_rethrow = false
        recovery_worker_queue = 0x55c06865e690
        __func__ = "recovery_worker_main"
#15 0x000055c067b66c82 in StartBackgroundWorker () at bgworker.c:858
        local_sigjmp_buf = {{__jmpbuf = {0, 4438337199125679975, 94284867345776, 94284867463316, 94284873577312, 94284873577328, -44[39](https://github.com/orioledb/orioledb/actions/runs/9078106879/job/24944412826#step:8:40)497022033506457, -7631090882606543001}, __mask_was_saved = 1, __saved_mask = {__val = {1844674[40](https://github.com/orioledb/orioledb/actions/runs/9078106879/job/24944412826#step:8:41)66192964099, 8192, 0, 94284873577328, 9428486[41](https://github.com/orioledb/orioledb/actions/runs/9078106879/job/24944412826#step:8:42)62080, 94284873561600, 9[42](https://github.com/orioledb/orioledb/actions/runs/9078106879/job/24944412826#step:8:43)84873134256, 94284873134256, 94284873142448, 94284867463316, 94284864190217, 94284873134480, 94284864161832, 94284873134256, 0, 0}}}}
        worker = 0x55c0685e97d8
        entrypt = <optimized out>
        __func__ = "StartBackgroundWorker"
#16 0x000055c067b6c975 in do_start_bgworker (rw=<optimized out>) at postmaster.c:5796
        worker_pid = <optimized out>
        worker_pid = <optimized out>
        __func__ = "do_start_bgworker"
        __errno_location = <optimized out>
        __errno_location = <optimized out>
#17 maybe_start_bgworkers () at postmaster.c:6028
        rw = <optimized out>
        num_launched = 0
        now = 0
        iter = {cur = 0x55c06865b360, next = 0x55c06865a240, prev = 0x55c06807d680 <BackgroundWorkerList>}
#18 0x000055c067b6d35d in sigusr1_handler (postgres_signal_arg=<optimized out>) at postmaster.c:5177
        save_errno = 4
        __func__ = "sigusr1_handler"
#19 <signal handler called>
No locals.
#20 0x00007fd47[43](https://github.com/orioledb/orioledb/actions/runs/9078106879/job/24944412826#step:8:44)1b59d in __GI___select (nfds=nfds@entry=7, readfds=readfds@entry=0x7ffdcc680fd0, writefds=writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0x7ffdcc680f30) at ../sysdeps/unix/sysv/linux/select.c:69
        sc_ret = -4
        sc_ret = <optimized out>
        s = <optimized out>
        us = <optimized out>
        ns = <optimized out>
        ts64 = {tv_sec = 59, tv_nsec = 999809553}
        pts64 = 0x7ffdcc680ea0
        r = <optimized out>
#21 0x000055c067b6da3a in ServerLoop () at postmaster.c:1758
        timeout = {tv_sec = 60, tv_usec = 0}
        rmask = {fds_bits = {96, 0 <repeats 15 times>}}
        selres = <optimized out>
        now = <optimized out>
        readmask = {fds_bits = {96, 0 <repeats 15 times>}}
        nSockets = 7
        last_lockfile_recheck_time = 1715684315
        last_touch_time = 1715684315
        __func__ = "ServerLoop"
#22 0x000055c067b6f59b in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0x55c0685e8580) at postmaster.c:1[46](https://github.com/orioledb/orioledb/actions/runs/9078106879/job/24944412826#step:8:47)6
        opt = <optimized out>
        status = <optimized out>
        userDoption = <optimized out>
        listen_addr_saved = <optimized out>
        i = <optimized out>
        output_config_variable = <optimized out>
        __func__ = "PostmasterMain"
#23 0x0000[55](https://github.com/orioledb/orioledb/actions/runs/9078106879/job/24944412826#step:8:56)c0678903af in main (argc=3, argv=0x55c0685e8580) at main.c:202
        do_check_root = <optimized out>
```

**Comment by pashkinelfe** [comment]
Not spotted anymore. Likely was fixed as of 8f940615c
