### ISSUE TITLE
Segfault when running SELECT

### ISSUE THREAD

**Issue by jasper-smit-servicenow** [orioledb/orioledb#383]
I ran into the following segfault:

```
#0  0x00000000008e3170 in pg_detoast_datum_packed ()
#1  0x00000000008b8019 in varstrfastcmp_c ()
#2  0x00007f47c37e0c80 in o_call_comparator () from orioledb.so
#3  0x00007f47c37f00a1 in o_idx_cmp_range_key_to_value () from orioledb.so
#4  0x00007f47c37f02cc in o_idx_cmp_key_bound_to_tuple () from orioledb.so
#5  0x00007f47c3796bf5 in btree_page_search () from orioledb.so
#6  0x00007f47c379749e in find_page () from orioledb.so
#7  0x00007f47c379f82f in o_btree_find_tuple_by_key_cb () from orioledb.so
#8  0x00007f47c379fb23 in o_btree_find_tuple_by_key () from orioledb.so
#9  0x00007f47c37e80ce in o_iterate_index () from orioledb.so
#10 0x00007f47c37e8641 in o_index_scan_getnext () from orioledb.so
#11 0x00007f47c37e8849 in o_exec_fetch () from orioledb.so
#12 0x00007f47c37ed1cf in o_exec_custom_scan () from orioledb.so
#13 0x000000000067cbe8 in ExecProcNodeInstr ()
#14 0x000000000069b870 in ExecMemoize ()
#15 0x000000000067cbe8 in ExecProcNodeInstr ()
#16 0x00000000006a29e6 in ExecNestLoop ()
#17 0x000000000067cbe8 in ExecProcNodeInstr ()
#18 0x00000000006a2a9f in ExecNestLoop ()
#19 0x000000000067cbe8 in ExecProcNodeInstr ()
#20 0x00000000006a4f7e in ExecSort ()
#21 0x000000000067cbe8 in ExecProcNodeInstr ()
#22 0x000000000068fe0b in gather_merge_readnext ()
#23 0x000000000069016d in ExecGatherMerge ()
#24 0x000000000067cbe8 in ExecProcNodeInstr ()
#25 0x00000000006860e1 in fetch_input_tuple ()
#26 0x0000000000689040 in ExecAgg ()
#27 0x000000000067cbe8 in ExecProcNodeInstr ()
#28 0x000000000067674b in standard_ExecutorRun ()
#29 0x00007f47c37b0d15 in orioledb_ExecutorRun_hook () from orioledb.so
#30 0x000000000061df22 in ExplainOnePlan ()
#31 0x000000000061e2f3 in ExplainOneQuery.part.22 ()
#32 0x000000000061e889 in ExplainQuery ()
#33 0x00000000007d0485 in standard_ProcessUtility ()
#34 0x00007f47c37b1159 in orioledb_utility_command () from orioledb.so
#35 0x00000000007cec8f in PortalRunUtility ()
#36 0x00000000007cf02f in FillPortalStore ()
#37 0x00000000007cf325 in PortalRun ()
#38 0x00000000007cb96f in exec_simple_query ()
#39 0x00000000007cc605 in PostgresMain ()
#40 0x00000000007546db in ServerLoop ()
#41 0x00000000007555db in PostmasterMain ()
#42 0x00000000004f16c9 in main ()
```

**Comment by pashkinelfe** [comment]
@jasper-smit-servicenow thanks for reporting this. What orioledb version or commit hash you have built? What was approximate queries that lead to segfault? Could you also show contents of your database (output of \d+ and \di+ in your psql prompt).

Thank you again!

**Comment by pashkinelfe** [comment]
Thank you! I certainly remember this type of segfault some time ago, after beta5 state. Most probably it is fixed already. Could you recheck it at https://github.com/orioledb/orioledb/commit/58537f5f15ab815acadecd2bd2ee0e2cc58d378d ?

**Comment by pashkinelfe** [comment]
I close the issue. It's unlikely it appears at the recent states of main branch. In case you find it after https://github.com/orioledb/orioledb/commit/58537f5f15ab815acadecd2bd2ee0e2cc58d378d please don't hesitate to reopen the issue.
