### ISSUE TITLE
Server crashes when executing LOOP with EXCEPTION

### ISSUE THREAD

**Issue by Update56** [orioledb/orioledb#388]
**Describe the bug**
Server crashes when executing the following SQL-script

**What data setup do we need to do?**
OrioleDB (master) with Oriole's PostgreSQL (patches16_32)

**What is the necessary configuration info needed?**
My PostgreSQL configuration:
```
./configure --enable-debug --enable-cassert --enable-tap-tests --with-icu
```

Сluster configuration:
Adding to _postgresql.conf_
```
shared_preload_libraries = 'orioledb.so'
```

**What is the command that caused the error?**

```
BEGIN;
DO $$
BEGIN
    FOR i IN 1..100 LOOP
        BEGIN
	    RAISE reading_sql_data_not_permitted;
	EXCEPTION WHEN reading_sql_data_not_permitted THEN END;
    END LOOP;
END;$$;
ROLLBACK;
```

**Backtrace**

```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x0000794d0fc4526e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x0000794d0fc288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x00006276c7334bff in ExceptionalCondition (conditionName=conditionName@entry=0x794d103cd024 "bit == (1 << bitnum)", 
    fileName=fileName@entry=0x794d103ccfde "src/transam/oxid.c", lineNumber=lineNumber@entry=265)
    at /home/up56/work/src/postgres/build001/../src/backend/utils/error/assert.c:66
#6  0x0000794d103b33d0 in acquire_logical_xid () at src/transam/oxid.c:265
#7  0x0000794d103b4999 in assign_subtransaction_logical_xid () at src/transam/oxid.c:327
#8  0x0000794d103b2b01 in undo_subxact_callback (event=<optimized out>, mySubid=<optimized out>, parentSubid=1, arg=<optimized out>)
    at src/transam/undo.c:1569
#9  0x00006276c6f16e4c in CallSubXactCallbacks (parentSubid=1, mySubid=33, event=SUBXACT_EVENT_START_SUB)
    at /home/up56/work/src/postgres/build001/../src/backend/access/transam/xact.c:3762
#10 StartSubTransaction () at /home/up56/work/src/postgres/build001/../src/backend/access/transam/xact.c:4943
#11 0x00006276c6f1a968 in CommitTransactionCommand () at /home/up56/work/src/postgres/build001/../src/backend/access/transam/xact.c:3301
#12 0x00006276c6f1ab5a in BeginInternalSubTransaction (name=<optimized out>)
    at /home/up56/work/src/postgres/build001/../src/backend/access/transam/xact.c:4606
#13 0x0000794cfc9a7c22 in exec_stmt_block (estate=estate@entry=0x7ffc44bdaf20, block=block@entry=0x6276c927ae30)
    at /home/up56/work/src/postgres/build001/../src/pl/plpgsql/src/pl_exec.c:1777
#14 0x0000794cfc9a5a84 in exec_stmts (estate=estate@entry=0x7ffc44bdaf20, stmts=0x6276c927ae80)
    at /home/up56/work/src/postgres/build001/../src/pl/plpgsql/src/pl_exec.c:2016
#15 0x0000794cfc9a90cf in exec_stmt_fori (estate=estate@entry=0x7ffc44bdaf20, stmt=stmt@entry=0x6276c927a870)
    at /home/up56/work/src/postgres/build001/../src/pl/plpgsql/src/pl_exec.c:2784
#16 0x0000794cfc9a56ec in exec_stmts (estate=estate@entry=0x7ffc44bdaf20, stmts=0x6276c927aed0)
    at /home/up56/work/src/postgres/build001/../src/pl/plpgsql/src/pl_exec.c:2052
#17 0x0000794cfc9a805a in exec_stmt_block (estate=estate@entry=0x7ffc44bdaf20, block=block@entry=0x6276c927af20)
    at /home/up56/work/src/postgres/build001/../src/pl/plpgsql/src/pl_exec.c:1943
#18 0x0000794cfc9a816d in exec_toplevel_block (estate=estate@entry=0x7ffc44bdaf20, block=0x6276c927af20)
    at /home/up56/work/src/postgres/build001/../src/pl/plpgsql/src/pl_exec.c:1634
#19 0x0000794cfc9a8a71 in plpgsql_exec_function (func=func@entry=0x6276c9276310, fcinfo=fcinfo@entry=0x7ffc44bdb0e0, 
    simple_eval_estate=simple_eval_estate@entry=0x6276c927bca8, simple_eval_resowner=simple_eval_resowner@entry=0x6276c91ddcb8, 
    procedure_resowner=procedure_resowner@entry=0x6276c91ddcb8, atomic=<optimized out>)
    at /home/up56/work/src/postgres/build001/../src/pl/plpgsql/src/pl_exec.c:623
#20 0x0000794cfc9b320c in plpgsql_inline_handler (fcinfo=<optimized out>) at /home/up56/work/src/postgres/build001/../src/pl/plpgsql/src/pl_handler.c:368
#21 0x00006276c733ef41 in FunctionCall1Coll (arg1=108262319773224, collation=0, flinfo=0x7ffc44bdb200)
    at /home/up56/work/src/postgres/build001/../src/backend/utils/fmgr/fmgr.c:1110
#22 OidFunctionCall1Coll (functionId=<optimized out>, collation=collation@entry=0, arg1=108262319773224, arg1@entry=0)
    at /home/up56/work/src/postgres/build001/../src/backend/utils/fmgr/fmgr.c:1388
#23 0x00006276c6fdb315 in ExecuteDoStmt (pstate=0x1620000000000, pstate@entry=0x6276c91cd518, stmt=stmt@entry=0x6276c913f3c8, atomic=false, 
    atomic@entry=true) at /home/up56/work/src/postgres/build001/../src/backend/commands/functioncmds.c:2145
#24 0x00006276c71fd032 in standard_ProcessUtility (pstmt=0x6276c913f468, 
    queryString=0x6276c913e738 "DO $$\nBEGIN\n    FOR i IN 1..100 LOOP\n        BEGIN\n\t    RAISE reading_sql_data_not_permitted;\n\tEXCEPTION WHEN reading_sql_data_not_permitted THEN END;\n    END LOOP;\nEND;$$;", readOnlyTree=<optimized out>, context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, 
    dest=0x6276c913f728, qc=0x7ffc44bdb6e0) at /home/up56/work/src/postgres/build001/../src/backend/tcop/utility.c:714
#25 0x0000794d1035bca3 in orioledb_utility_command (pstmt=<optimized out>, 
    queryString=0x6276c913e738 "DO $$\nBEGIN\n    FOR i IN 1..100 LOOP\n        BEGIN\n\t    RAISE reading_sql_data_not_permitted;\n\tEXCEPTION WHEN reading_sql_data_not_permitted THEN END;\n    END LOOP;\nEND;$$;", readOnlyTree=false, context=PROCESS_UTILITY_TOPLEVEL, params=0x0, env=0x0, 
    dest=0x6276c913f728, qc=0x7ffc44bdb6e0) at src/catalog/ddl.c:1227
#26 0x00006276c71fb1ff in PortalRunUtility (portal=portal@entry=0x6276c921fe88, pstmt=pstmt@entry=0x6276c913f468, isTopLevel=isTopLevel@entry=true, 
    setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x6276c913f728, qc=qc@entry=0x7ffc44bdb6e0)
    at /home/up56/work/src/postgres/build001/../src/backend/tcop/pquery.c:1158
#27 0x00006276c71fb33d in PortalRunMulti (portal=portal@entry=0x6276c921fe88, isTopLevel=isTopLevel@entry=true, 
    setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x6276c913f728, altdest=altdest@entry=0x6276c913f728, qc=qc@entry=0x7ffc44bdb6e0)
    at /home/up56/work/src/postgres/build001/../src/backend/tcop/pquery.c:1315
#28 0x00006276c71fb8bd in PortalRun (portal=portal@entry=0x6276c921fe88, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, 
    run_once=run_once@entry=true, dest=dest@entry=0x6276c913f728, altdest=altdest@entry=0x6276c913f728, qc=0x7ffc44bdb6e0)
    at /home/up56/work/src/postgres/build001/../src/backend/tcop/pquery.c:791
#29 0x00006276c71f7826 in exec_simple_query (
    query_string=0x6276c913e738 "DO $$\nBEGIN\n    FOR i IN 1..100 LOOP\n        BEGIN\n\t    RAISE reading_sql_data_not_permitted;\n\tEXCEPTION WHEN reading_sql_data_not_permitted THEN END;\n    END LOOP;\nEND;$$;") at /home/up56/work/src/postgres/build001/../src/backend/tcop/postgres.c:1278
#30 0x00006276c71f920e in PostgresMain (dbname=<optimized out>, username=<optimized out>)
    at /home/up56/work/src/postgres/build001/../src/backend/tcop/postgres.c:4701
#31 0x00006276c715fa2e in BackendRun (port=0x6276c91d1bc0) at /home/up56/work/src/postgres/build001/../src/backend/postmaster/postmaster.c:4450
#32 BackendStartup (port=0x6276c91d1bc0) at /home/up56/work/src/postgres/build001/../src/backend/postmaster/postmaster.c:4178
#33 ServerLoop () at /home/up56/work/src/postgres/build001/../src/backend/postmaster/postmaster.c:1767
#34 0x00006276c7160a60 in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0x6276c9138aa0)
    at /home/up56/work/src/postgres/build001/../src/backend/postmaster/postmaster.c:1451
#35 0x00006276c6e66abe in main (argc=3, argv=0x6276c9138aa0) at /home/up56/work/src/postgres/build001/../src/backend/main/main.c:198

```

**Expected behavior**
Expected ERROR to be shown or sql query to be successfully executed

**Notes**
If you reduce the number of iterations to 31 (1..31) then the code is executed successfully

Best regards,
Ilya Cherdakov
Postgres Professional: https://postgrespro.com/

**Comment by Update56** [comment]
Here is another case where the server crashes with the same assert
```
DO $$
DECLARE
    objtype text;
    names   text[];
    args    text[];
BEGIN
    FOR objtype IN VALUES
        ('table'), ('index'), ('sequence'), ('view'),
        ('materialized view'), ('foreign table')
    LOOP
        FOR names IN VALUES ('{eins}'), ('{addr_nsp, zwei}'), ('{eins, zwei, drei}')
        LOOP
            FOR args IN VALUES ('{}'), ('{integer}')
            LOOP
                BEGIN
                EXCEPTION WHEN OTHERS THEN
                    RAISE WARNING 'error for %,%,%: %', objtype, names, args, sqlerrm;
                END;
            END LOOP;
        END LOOP;
    END LOOP;
END;
$$;
```

**Comment by homper** [comment]
Fixed by https://github.com/orioledb/orioledb/commit/b3555db35a5e5dea9f19b4c772ba32877c67db29
