### ISSUE TITLE
Do we write control file atomically?

### ISSUE THREAD

**Issue by akorotkov** [orioledb/orioledb#405]
https://github.com/orioledb/orioledb/actions/runs/12431219895/job/34708220777?pr=403

```
======================================================================
ERROR: test_checkpoint_by_time (test.t.checkpointer_test.CheckpointerTest.test_checkpoint_by_time)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/orioledb/orioledb/python3-venv/lib/python3.12/site-packages/testgres/node.py", line 751, in start
    exit_status, out, error = execute_utility(_params, self.utils_log_file, verbose=True)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/orioledb/orioledb/python3-venv/lib/python3.12/site-packages/testgres/utils.py", line 67, in execute_utility
    exit_status, out, error = tconf.os_ops.exec_command(args, verbose=True)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/orioledb/orioledb/python3-venv/lib/python3.12/site-packages/testgres/operations/local_ops.py", line 119, in exec_command
    self._raise_exec_exception('Utility exited with non-zero code. Error `{}`', cmd, process.returncode, error or output)
  File "/home/runner/work/orioledb/orioledb/python3-venv/lib/python3.12/site-packages/testgres/operations/local_ops.py", line 53, in _raise_exec_exception
    raise ExecUtilException(message=message.format(output),
testgres.exceptions.ExecUtilException: Utility exited with non-zero code. Error `b'pg_ctl: could not start server\nExamine the log output.\n'`
Command: /home/runner/work/orioledb/orioledb/pgsql/bin/pg_ctl -D /tmp/checkpointer-checkpoint_by_time_tgsn_v8bsghkf/data -l /tmp/checkpointer-checkpoint_by_time_tgsn_v8bsghkf/logs/postgresql.log -w start
Exit code: 1
----
b'pg_ctl: could not start server\nExamine the log output.\n'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/orioledb/orioledb/orioledb/test/t/checkpointer_test.py", line 53, in test_checkpoint_by_time
    node.start()
  File "/home/runner/work/orioledb/orioledb/python3-venv/lib/python3.12/site-packages/testgres/node.py", line [76](https://github.com/orioledb/orioledb/actions/runs/12431219895/job/34708220777?pr=403#step:8:77)9, in start
    raise_from(StartNodeException(msg, files), e)
  File "<string>", line 3, in raise_from
testgres.exceptions.StartNodeException: Cannot start node
/tmp/checkpointer-checkpoint_by_time_tgsn_v8bsghkf/data/postgresql.conf
----
b"\nfsync = off\nmax_worker_processes = 10\nlog_statement = 'all'\nlisten_addresses = '127.0.0.1'\nport = 20020\n\nmax_replication_slots = 10\nmax_wal_senders = 10\n\nhot_standby = on\nwal_keep_size = 320\nwal_level = 'replica'\nshared_preload_libraries = orioledb\n\norioledb.debug_checkpoint_timeout = 2s\norioledb.enable_stopevents = true\n\n"

/tmp/checkpointer-checkpoint_by_time_tgsn_v8bsghkf/data/postgresql.auto.conf
----
b'# Do not edit this file manually!\n# It will be overwritten by the ALTER SYSTEM command.\n'

/tmp/checkpointer-checkpoint_by_time_tgsn_v8bsghkf/data/pg_hba.conf
----
b'local   all             all                                     trust\nhost    all             all             127.0.0.1/32            trust\nhost    all             all             ::1/128                 trust\nlocal   replication     all                                     trust\nhost    replication     all             127.0.0.1/32            trust\nhost    replication     all             ::1/128                 trust\nlocal\treplication\tall\t\t\ttrust\nhost\treplication\tall\t127.0.0.1/32\ttrust\nhost\treplication\tall\t::1/128\t\ttrust\nhost\treplication\tall\t127.0.0.0/24\t\ttrust\nhost\tall\tall\t127.0.0.0/24\t\ttrust\nhost\tall\tall\tall\ttrust\nhost\treplication\tall\tall\ttrust\n'

/tmp/checkpointer-checkpoint_by_time_tgsn_v8bsghkf/logs/postgresql.log
----
b'\t\t\t\t\t\t\t\t FROM pg_stopevents() se\n\t\t\t\t\t\t\t\t WHERE se.waiter_pids @> ARRAY[14022]\n\t\t\t\t\t\t\t  );\n2024-12-20 12:17:12.836 GMT [14[78](https://github.com/orioledb/orioledb/actions/runs/12431219895/job/34708220777?pr=403#step:8:79)5] LOG:  statement: SELECT EXISTS(\n\t\t\t\t\t\t\t\t SELECT se.*\n\t\t\t\t\t\t\t\t FROM pg_stopevents() se\n\t\t\t\t\t\t\t\t WHERE se.waiter_pids @> ARRAY[14022]\n\t\t\t\t\t\t\t  );\n2024-12-20 12:17:12.886 GMT [14022] LOG:  orioledb checkpoint 1 started\n2024-12-20 12:17:12.940 GMT [14[81](https://github.com/orioledb/orioledb/actions/runs/12431219895/job/34708220777?pr=403#step:8:82)4] LOG:  statement: SELECT EXISTS(\n\t\t\t\t\t\t\t\t SELECT se.*\n\t\t\t\t\t\t\t\t FROM pg_stopevents() se\n\t\t\t\t\t\t\t\t WHERE se.waiter_pids @> ARRAY[14022]\n\t\t\t\t\t\t\t  );\n2024-12-20 12:17:12.941 GMT [14041] LOG:  statement: SELECT pg_stopevent_reset(\'checkpoint_step\')\n2024-12-20 12:17:12.944 GMT [14006] LOG:  received immediate shutdown request\n2024-12-20 12:17:12.962 GMT [14006] LOG:  database system is shut down\n2024-12-20 12:17:13.061 GMT [14837] LOG:  registered custom resource manager "OrioleDB resource manager" with ID 129\n2024-12-20 12:17:13.0[82](https://github.com/orioledb/orioledb/actions/runs/12431219895/job/34708220777?pr=403#step:8:83) GMT [14837] FATAL:  could not read data from control file "orioledb_data/control"\n2024-12-20 12:17:13.086 GMT [14837] LOG:  database system is shut down\n'
```

**Comment by homper** [comment]
If I understand correctly it is fixed by https://github.com/orioledb/orioledb/commit/c23855dee59194481f72c33bd3e8686edfa54a42
