### ISSUE TITLE
FailedAssertion("state->defvals_exprstate", File: "src/tuple/format.c")

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#49]
sql/test.sql:

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;

CREATE TABLE o_test_1 (
    val_1 text,
    val_2 text GENERATED ALWAYS AS (val_1 || '+' || val_1) STORED
)USING orioledb;

INSERT INTO o_test_1 (val_1) VALUES ('a'), ('b'), ('c'), (NULL);

SELECT * FROM o_test_1;
```

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;

CREATE TABLE o_test_1 (
  val_1 int DEFAULT 1,
  val_2 text DEFAULT 'a',
  val_3 float8 DEFAULT 1.1
)USING orioledb;

INSERT INTO o_test_1 VALUES (2, null, 2.0);

SELECT * FROM o_test_1;
```

```log
TRAP: FailedAssertion("state->defvals_exprstate", File: "src/tuple/format.c", Line: 145, PID: 111945)
postgres: orioledb regression [local] SELECT(ExceptionalCondition+0x99)[0x556cf7bf9179]
/home/orioledb/pg15/lib/postgresql/orioledb.so(o_tuple_read_next_field+0x22e)[0x7f9c341b01ce]
/home/orioledb/pg15/lib/postgresql/orioledb.so(+0x91f56)[0x7f9c341b6f56]
postgres: orioledb regression [local] SELECT(slot_getsomeattrs_int+0x2e)[0x556cf793812e]
postgres: orioledb regression [local] SELECT(+0x1749b0)[0x556cf77659b0]
postgres: orioledb regression [local] SELECT(standard_ExecutorRun+0x147)[0x556cf792a9a7]
postgres: orioledb regression [local] SELECT(+0x4d7ebf)[0x556cf7ac8ebf]
postgres: orioledb regression [local] SELECT(PortalRun+0x191)[0x556cf7aca491]
postgres: orioledb regression [local] SELECT(+0x4d5292)[0x556cf7ac6292]
postgres: orioledb regression [local] SELECT(PostgresMain+0x178e)[0x556cf7ac7fde]
postgres: orioledb regression [local] SELECT(+0x43e26a)[0x556cf7a2f26a]
postgres: orioledb regression [local] SELECT(PostmasterMain+0xe8b)[0x556cf7a303db]
postgres: orioledb regression [local] SELECT(main+0x220)[0x556cf77516a0]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f9c34a020b3]
postgres: orioledb regression [local] SELECT(_start+0x2e)[0x556cf77519ee]
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by Tanyaevm** [comment]
sql/test.sql:

Error with orioledb:

```sql
CREATE TEMP TABLE o_test_1(
    val_1 int NOT NULL PRIMARY KEY ,
    val_2 text,
    val_3 text,
    val_4 text,
    val_5 text,
    val_6 int NOT NULL DEFAULT 0
)USING orioledb;

CREATE TEMP TABLE o_test_2(
    key int NOT NULL PRIMARY KEY,
    val_1 int NOT NULL,
    val_2 text
)USING orioledb;

CREATE FUNCTION func_1() RETURNS trigger AS
$$
begin
  DELETE FROM o_test_2 WHERE val_1 = old.val_1;
  RETURN old;
end;
$$LANGUAGE plpgsql;

CREATE TRIGGER trig_1 BEFORE DELETE ON o_test_1
  FOR EACH ROW EXECUTE PROCEDURE func_1();

CREATE FUNCTION func_2() RETURNS trigger AS
$$
begin
  UPDATE o_test_1 SET val_6 = val_6 - 1 WHERE val_1 = old.val_1;
  RETURN old;
end;
$$LANGUAGE plpgsql;

CREATE TRIGGER child_del_trig AFTER DELETE ON o_test_2
  FOR EACH ROW EXECUTE PROCEDURE func_2();

INSERT INTO o_test_1 VALUES (1, 'a', 'a', 'a', 'a', 0);
INSERT INTO o_test_2 VALUES (10, 1, 'b');

CREATE OR REPLACE FUNCTION func_1() RETURNS trigger AS
$$
begin
  DELETE FROM o_test_2 WHERE val_1 = old.val_1;
  if found THEN
    DELETE FROM o_test_1 WHERE val_1 = old.val_1;
    RETURN NULL;
  end if;
  RETURN old;
end;
$$LANGUAGE plpgsql;

DELETE FROM o_test_1 WHERE val_1 = 1;

--ERROR:  tuple to be deleted was already modified by an operation triggered by the current command
--HINT:  Consider using an AFTER trigger instead of a BEFORE trigger to propagate changes to other rows.
--CONTEXT:  SQL statement "DELETE FROM o_test_1 WHERE aid = old.aid"
--PL/pgSQL function func_1() line 5 at SQL statement

SELECT * FROM o_test_1; 
```

```
TRAP: FailedAssertion("state->defvals_exprstate", File: "src/tuple/format.c", Line: 145, PID: 215253)
postgres: orioledb regression [local] SELECT(ExceptionalCondition+0x99)[0x56173d6e8169]
/home/orioledb/pg15/lib/postgresql/orioledb.so(o_tuple_read_next_field+0x22e)[0x7fcc55bd592e]
/home/orioledb/pg15/lib/postgresql/orioledb.so(+0x885ce)[0x7fcc55bdb5ce]
postgres: orioledb regression [local] SELECT(slot_getsomeattrs_int+0x2e)[0x56173d42711e]
postgres: orioledb regression [local] SELECT(+0x1749b0)[0x56173d2549b0]
postgres: orioledb regression [local] SELECT(standard_ExecutorRun+0x147)[0x56173d419997]
postgres: orioledb regression [local] SELECT(+0x4d7eaf)[0x56173d5b7eaf]
postgres: orioledb regression [local] SELECT(PortalRun+0x191)[0x56173d5b9481]
postgres: orioledb regression [local] SELECT(+0x4d5282)[0x56173d5b5282]
postgres: orioledb regression [local] SELECT(PostgresMain+0x178e)[0x56173d5b6fce]
postgres: orioledb regression [local] SELECT(+0x43e25a)[0x56173d51e25a]
postgres: orioledb regression [local] SELECT(PostmasterMain+0xe8b)[0x56173d51f3cb]
postgres: orioledb regression [local] SELECT(main+0x220)[0x56173d2406a0]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7fcc564230b3]
postgres: orioledb regression [local] SELECT(_start+0x2e)[0x56173d2409ee]
```

**Coredump:**
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fcc56421859 in __GI_abort () at abort.c:79
#2  0x000056173d6e8188 in ExceptionalCondition (conditionName=conditionName@entry=0x7fcc55bf34d2 "state->defvals_exprstate", errorType=errorType@entry=0x7fcc55be704a "FailedAssertion", fileName=fileName@entry=0x7fcc55bf349d "src/tuple/format.c", lineNumber=lineNumber@entry=145) at assert.c:69
#3  0x00007fcc55bd592e in o_tuple_read_next_field (state=state@entry=0x56173ebcfc68, isnull=isnull@entry=0x56173ebcfcdd) at src/tuple/format.c:145
#4  0x00007fcc55bdb5ce in tts_orioledb_getsomeattrs (slot=0x56173ebcfbd0, __natts=<optimized out>) at src/tuple/slot.c:240
#5  0x000056173d42711e in slot_getsomeattrs_int (slot=slot@entry=0x56173ebcfbd0, attnum=6) at execTuples.c:1912
#6  0x000056173d2549b0 in slot_getsomeattrs (attnum=<optimized out>, slot=0x56173ebcfbd0) at ../../../../src/include/executor/tuptable.h:344
#7  slot_getallattrs (slot=0x56173ebcfbd0) at ../../../../src/include/executor/tuptable.h:356
#8  printtup (slot=0x56173ebcfbd0, self=0x56173ebbb108) at printtup.c:315
#9  0x000056173d419997 in ExecutePlan (execute_once=<optimized out>, dest=0x56173ebbb108, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x56173ebcf9c8, estate=0x56173ebcf790) at execMain.c:1673
#10 standard_ExecutorRun (queryDesc=0x56173eb62810, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:363
#11 0x000056173d5b7eaf in PortalRunSelect (portal=0x56173eac7f60, forward=<optimized out>, count=0, dest=<optimized out>) at pquery.c:924
#12 0x000056173d5b9481 in PortalRun (portal=portal@entry=0x56173eac7f60, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x56173ebbb108, altdest=altdest@entry=0x56173ebbb108, qc=0x7ffd4af94db0) at pquery.c:768
#13 0x000056173d5b5282 in exec_simple_query (query_string=0x56173ea3d490 "SELECT * FROM o_test_1;") at postgres.c:1250
#14 0x000056173d5b6fce in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4544
#15 0x000056173d51e25a in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4510
#16 BackendStartup (port=<optimized out>) at postmaster.c:4238
#17 ServerLoop () at postmaster.c:1812
#18 0x000056173d51f3cb in PostmasterMain (argc=<optimized out>, argv=0x56173ea37c20) at postmaster.c:1484
#19 0x000056173d2406a0 in main (argc=8, argv=0x56173ea37c20) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by Tanyaevm** [comment]
sql/test.sql:

Error for postgres:

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;
CREATE TABLE o_test_1 (
	val_1	int DEFAULT 1,
	val_2	text DEFAULT 'a'
)USING orioledb;

CREATE VIEW test_view_1 
  AS SELECT * FROM o_test_1;

CREATE rule test_view_1 AS
	ON INSERT TO test_view_1
	  DO INSTEAD INSERT INTO o_test_1 SELECT new.*;

ALTER TABLE test_view_1 
  ALTER column val_1 SET DEFAULT 2;

INSERT INTO test_view_1 
  DEFAULT VALUES;

SELECT * FROM test_view_1;
```

```
TRAP: FailedAssertion("state->defvals_exprstate", File: "src/tuple/format.c", Line: 145, PID: 49057)
postgres: orioledb regression [local] SELECT(ExceptionalCondition+0x99)[0x558247647169]
/home/orioledb/pg15/lib/postgresql/orioledb.so(o_tuple_read_next_field+0x22e)[0x7f2e0896d92e]
/home/orioledb/pg15/lib/postgresql/orioledb.so(+0x885ce)[0x7f2e089735ce]
postgres: orioledb regression [local] SELECT(slot_getsomeattrs_int+0x2e)[0x55824738611e]
postgres: orioledb regression [local] SELECT(+0x1749b0)[0x5582471b39b0]
postgres: orioledb regression [local] SELECT(standard_ExecutorRun+0x147)[0x558247378997]
postgres: orioledb regression [local] SELECT(+0x4d7eaf)[0x558247516eaf]
postgres: orioledb regression [local] SELECT(PortalRun+0x191)[0x558247518481]
postgres: orioledb regression [local] SELECT(+0x4d5282)[0x558247514282]
postgres: orioledb regression [local] SELECT(PostgresMain+0x178e)[0x558247515fce]
postgres: orioledb regression [local] SELECT(+0x43e25a)[0x55824747d25a]
postgres: orioledb regression [local] SELECT(PostmasterMain+0xe8b)[0x55824747e3cb]
postgres: orioledb regression [local] SELECT(main+0x220)[0x55824719f6a0]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f2e091bb0b3]
postgres: orioledb regression [local] SELECT(_start+0x2e)[0x55824719f9ee]
```

**Coredump**
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f2f0ace1859 in __GI_abort () at abort.c:79
#2  0x000055b6c3837188 in ExceptionalCondition (conditionName=conditionName@entry=0x7f2f0a4b34d2 "state->defvals_exprstate", errorType=errorType@entry=0x7f2f0a4a704a "FailedAssertion", fileName=fileName@entry=0x7f2f0a4b349d "src/tuple/format.c", lineNumber=lineNumber@entry=145) at assert.c:69
#3  0x00007f2f0a49592e in o_tuple_read_next_field (state=state@entry=0x55b6c5909360, isnull=isnull@entry=0x55b6c59093b1) at src/tuple/format.c:145
#4  0x00007f2f0a49b5ce in tts_orioledb_getsomeattrs (slot=0x55b6c59092c8, __natts=<optimized out>) at src/tuple/slot.c:240
#5  0x000055b6c357611e in slot_getsomeattrs_int (slot=slot@entry=0x55b6c59092c8, attnum=2) at execTuples.c:1912
#6  0x000055b6c33a39b0 in slot_getsomeattrs (attnum=<optimized out>, slot=0x55b6c59092c8) at ../../../../src/include/executor/tuptable.h:344
#7  slot_getallattrs (slot=0x55b6c59092c8) at ../../../../src/include/executor/tuptable.h:356
#8  printtup (slot=0x55b6c59092c8, self=0x55b6c5939ca0) at printtup.c:315
#9  0x000055b6c3568997 in ExecutePlan (execute_once=<optimized out>, dest=0x55b6c5939ca0, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x55b6c59090c0, estate=0x55b6c5908e70) at execMain.c:1673
#10 standard_ExecutorRun (queryDesc=0x55b6c593e810, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:363
#11 0x000055b6c3706eaf in PortalRunSelect (portal=0x55b6c58a3f60, forward=<optimized out>, count=0, dest=<optimized out>) at pquery.c:924
#12 0x000055b6c3708481 in PortalRun (portal=portal@entry=0x55b6c58a3f60, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x55b6c5939ca0, altdest=altdest@entry=0x55b6c5939ca0, qc=0x7ffca10c0150) at pquery.c:768
#13 0x000055b6c3704282 in exec_simple_query (query_string=0x55b6c5819490 "SELECT * FROM test_view_1;") at postgres.c:1250
#14 0x000055b6c3705fce in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4544
#15 0x000055b6c366d25a in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4510
#16 BackendStartup (port=<optimized out>) at postmaster.c:4238
#17 ServerLoop () at postmaster.c:1812
#18 0x000055b6c366e3cb in PostmasterMain (argc=<optimized out>, argv=0x55b6c5813c20) at postmaster.c:1484
#19 0x000055b6c338f6a0 in main (argc=8, argv=0x55b6c5813c20) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```
