### ISSUE TITLE
Segfault: transformCreateStmt: wrong elements

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#55]
sql/test.sql:

Error with postgres and orioledb
```sql
CREATE EXTENSION IF NOT EXISTS orioledb;

CREATE FUNCTION func_1(int) RETURNS int AS $$
DECLARE TOTAL int;
BEGIN
	CREATE TEMP TABLE o_test_1(val_1 int)USING orioledb;
	INSERT INTO o_test_1 VALUES($1);
	INSERT INTO o_test_1 VALUES(11);
	INSERT INTO o_test_1 VALUES(12);
	INSERT INTO o_test_1 VALUES(13);
	SELECT sum(val_1) INTO total FROM o_test_1;
	DROP TABLE o_test_1;
	RETURN total;
end
$$ language plpgsql;

SELECT func_1(1);
SELECT func_1(2);
SELECT func_1(3);
```
**Coredump**
```
#0  0x0000561ce7f4fa64 in transformCreateStmt (stmt=stmt@entry=0x561ce8eedd68, queryString=queryString@entry=0x561ce8ef8fa8 "CREATE TEMP TABLE o_test_1(val_1 int)USING orioledb") at parse_utilcmd.c:265
265                     Node       *element = lfirst(elements);
#0  0x0000561ce7f4fa64 in transformCreateStmt (stmt=stmt@entry=0x561ce8eedd68, queryString=queryString@entry=0x561ce8ef8fa8 "CREATE TEMP TABLE o_test_1(val_1 int)USING orioledb") at parse_utilcmd.c:265
#1  0x00007fc78e10b7a5 in orioledb_utility_command (pstmt=0x561ce8eedcd0, queryString=0x561ce8ef8fa8 "CREATE TEMP TABLE o_test_1(val_1 int)USING orioledb", readOnlyTree=<optimized out>, context=PROCESS_UTILITY_QUERY, params=0x0, env=0x0, dest=0x561ce85cbb80 <spi_printtupDR>, qc=0x7ffd5266ceb0) at src/catalog/ddl.c:985
#2  0x0000561ce8022a31 in _SPI_execute_plan (plan=<optimized out>, options=0x7ffd5266cf20, snapshot=<optimized out>, crosscheck_snapshot=<optimized out>, fire_triggers=<optimized out>) at spi.c:2693
#3  0x0000561ce8023626 in SPI_execute_plan_with_paramlist (plan=0x561ce8ee9800, params=0x0, read_only=<optimized out>, tcount=0) at spi.c:749
#4  0x00007fc77f20a087 in exec_stmt_execsql (estate=0x7ffd5266d380, stmt=0x561ce8eeb9c8) at pl_exec.c:4271
#5  0x00007fc77f20bc2b in exec_stmts (estate=0x7ffd5266d380, stmts=0x561ce8eeba20) at pl_exec.c:2081
#6  0x00007fc77f20de38 in exec_stmt_block (estate=0x7ffd5266d380, block=0x561ce8ead850) at pl_exec.c:1932
#7  0x00007fc77f20df1d in exec_toplevel_block (estate=estate@entry=0x7ffd5266d380, block=0x561ce8ead850) at pl_exec.c:1623
#8  0x00007fc77f20e7e0 in plpgsql_exec_function (func=func@entry=0x561ce8e0a660, fcinfo=fcinfo@entry=0x561ce8ea71d8, simple_eval_estate=simple_eval_estate@entry=0x0, simple_eval_resowner=simple_eval_resowner@entry=0x0, procedure_resowner=procedure_resowner@entry=0x0, atomic=<optimized out>) at pl_exec.c:612
#9  0x00007fc77f217e7b in plpgsql_call_handler (fcinfo=0x561ce8ea71d8) at pl_handler.c:277
#10 0x0000561ce7fd9dc3 in ExecInterpExpr (state=0x561ce8ea70f0, econtext=0x561ce8ea6df0, isnull=<optimized out>) at execExprInterp.c:737
#11 0x0000561ce8014742 in ExecEvalExprSwitchContext (isNull=0x7ffd5266d687, econtext=0x561ce8ea6df0, state=0x561ce8ea70f0) at ../../../src/include/executor/executor.h:343
#12 ExecProject (projInfo=0x561ce8ea70e8) at ../../../src/include/executor/executor.h:377
#13 ExecResult (pstate=<optimized out>) at nodeResult.c:136
#14 0x0000561ce7fde973 in ExecProcNode (node=0x561ce8ea6cd8) at ../../../src/include/executor/executor.h:259
#15 ExecutePlan (execute_once=<optimized out>, dest=0x561ce8ef1408, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x561ce8ea6cd8, estate=0x561ce8ea6aa0) at execMain.c:1642
#16 standard_ExecutorRun (queryDesc=0x561ce8ee67f0, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:363
#17 0x0000561ce817cebf in PortalRunSelect (portal=0x561ce8e4bf40, forward=<optimized out>, count=0, dest=<optimized out>) at pquery.c:924
#18 0x0000561ce817e491 in PortalRun (portal=portal@entry=0x561ce8e4bf40, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x561ce8ef1408, altdest=altdest@entry=0x561ce8ef1408, qc=0x7ffd5266d920) at pquery.c:768
#19 0x0000561ce817a292 in exec_simple_query (query_string=0x561ce8dc1490 "SELECT func_1(3);") at postgres.c:1250
#20 0x0000561ce817bfde in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4544
#21 0x0000561ce80e326a in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4510
#22 BackendStartup (port=<optimized out>) at postmaster.c:4238
#23 ServerLoop () at postmaster.c:1812
#24 0x0000561ce80e43db in PostmasterMain (argc=<optimized out>, argv=0x561ce8dbbc20) at postmaster.c:1484
#25 0x0000561ce7e056a0 in main (argc=8, argv=0x561ce8dbbc20) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by homper** [comment]
Fixed on branch [github_issue_55](/orioledb/orioledb/tree/github_issue_55)

**Comment by homper** [comment]
Fix merged to [main](https://github.com/orioledb/orioledb)
