### ISSUE TITLE
Segfault: internalGetUpdateNewTuple: wrong newProj

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#63]
specs/test.spec:

```sql
setup
{
	CREATE EXTENSION IF NOT EXISTS orioledb;

	CREATE TABLE o_test_1 (
		val_1 int PRIMARY KEY,
		val_2 int,
		val_3 int
	)USING orioledb;

	INSERT INTO o_test_1
		VALUES (1, 2, 3);

}

teardown
{
	DROP TABLE o_test_1;
}

session "s1"

step "begin_1" { BEGIN;}

step "delete_1" { DELETE FROM o_test_1 WHERE val_1 = 1; }

step "merge_delete_1" { MERGE INTO o_test_1 t
					USING (SELECT 1 AS val_1) s
					ON s.val_1 = t.val_1
					WHEN MATCHED THEN DELETE; }

step "merge_update_1" {MERGE INTO o_test_1 t
					USING (SELECT 1 AS val_1) s
					ON s.val_1 = t.val_1
					WHEN MATCHED AND val_3 = 3 THEN
					UPDATE SET val_3 = 33; }

step "commit_1" { COMMIT; }

session "s2"

step "begin_2" { BEGIN; }

step "delete_2" { DELETE FROM o_test_1 WHERE val_1 = 1; }

step "update_2" { UPDATE o_test_1 SET val_2 = val_2 + 10; }

step "merge_2" { MERGE INTO o_test_1 t
			   USING (SELECT 1 AS val_1) s
			   ON s.val_1 = t.val_1
			   WHEN MATCHED THEN
			   UPDATE SET val_1 = t.val_1 + 1; }

step "commit_2" { COMMIT; }

permutation "begin_1" "begin_2"
"update_2" "merge_update_1"
"commit_2" "commit_1"
```

**Coredump**
```
#0  internalGetUpdateNewTuple (relaction=0x0, oldSlot=0x55c64f9f6198, planSlot=0x55c64fa039b0, relinfo=0x55c64f9c0550) at nodeModifyTable.c:681
681             econtext = newProj->pi_exprContext;
#0  internalGetUpdateNewTuple (relaction=0x0, oldSlot=0x55c64f9f6198, planSlot=0x55c64fa039b0, relinfo=0x55c64f9c0550) at nodeModifyTable.c:681
#1  ExecGetUpdateNewTuple (relinfo=relinfo@entry=0x55c64f9c0550, planSlot=0x55c64fa039b0, oldSlot=0x55c64f9f6198) at nodeModifyTable.c:666
#2  0x00007fcd983d992d in orioledb_tuple_update (mstate=<optimized out>, rinfo=0x55c64f9c0550, estate=<optimized out>, tupleid=<optimized out>, slot=<optimized out>, cid=<optimized out>, snapshot=<optimized out>, crosscheck=<optimized out>, wait=<optimized out>, tmfd=<optimized out>, lockmode=<optimized out>, update_indexes=<optimized out>) at src/tableam/handler.c:561
#3  0x000055c64e325528 in table_extended_tuple_update (wait=true, update_indexes=0x7ffe46d53309, lockmode=0x7ffe46d5330c, tmfd=0x7ffe46d53360, crosscheck=<optimized out>, snapshot=<optimized out>, cid=<optimized out>, slot=0x55c64f9dcf88, tupleid=94310227729800, estate=0x55c64f9c00b0, resultRelInfo=0x55c64f9c0550, mstate=<optimized out>) at ../../../src/include/access/tableam.h:2280
#4  ExecUpdateAct (context=0x7ffe46d53330, resultRelInfo=0x55c64f9c0550, tupleid=94310227729800, oldtuple=0x0, slot=0x55c64f9dcf88, canSetTag=<optimized out>, updateCxt=0x7ffe46d53308) at nodeModifyTable.c:2025
#5  0x000055c64e3267a8 in ExecMergeMatched (canSetTag=true, tupleid=<optimized out>, resultRelInfo=<optimized out>, context=0x7ffe46d53330) at nodeModifyTable.c:2838
#6  ExecMerge (canSetTag=true, tupleid=<optimized out>, resultRelInfo=<optimized out>, context=0x7ffe46d53330) at nodeModifyTable.c:2697
#7  ExecModifyTable (pstate=<optimized out>) at nodeModifyTable.c:3835
#8  0x000055c64e2f3973 in ExecProcNode (node=0x55c64f9c0338) at ../../../src/include/executor/executor.h:259
#9  ExecutePlan (execute_once=<optimized out>, dest=0x55c64f9e48b8, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_MERGE, use_parallel_mode=<optimized out>, planstate=0x55c64f9c0338, estate=0x55c64f9c00b0) at execMain.c:1642
#10 standard_ExecutorRun (queryDesc=0x55c64f8f1510, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:363
#11 0x000055c64e4924e0 in ProcessQuery (plan=<optimized out>, sourceText=0x55c64f8d04b0 "MERGE INTO o_test_1 t\n", '\t' <repeats 13 times>, "USING (SELECT 1 AS val_1) s\n", '\t' <repeats 13 times>, "ON s.val_1 = t.val_1\n", '\t' <repeats 12 times>, "WHEN MATCHED AND val_3 = 3 THEN\n", '\t' <repeats 13 times>, "UPDATE SET val_3 = 33;", params=0x0, queryEnv=0x0, dest=0x55c64f9e48b8, qc=0x7ffe46d536a0) at pquery.c:160
#12 0x000055c64e493022 in PortalRunMulti (portal=portal@entry=0x55c64f95b070, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x55c64f9e48b8, altdest=altdest@entry=0x55c64f9e48b8, qc=qc@entry=0x7ffe46d536a0) at pquery.c:1277
#13 0x000055c64e4935a1 in PortalRun (portal=portal@entry=0x55c64f95b070, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x55c64f9e48b8, altdest=altdest@entry=0x55c64f9e48b8, qc=0x7ffe46d536a0) at pquery.c:791
#14 0x000055c64e48f292 in exec_simple_query (query_string=0x55c64f8d04b0 "MERGE INTO o_test_1 t\n", '\t' <repeats 13 times>, "USING (SELECT 1 AS val_1) s\n", '\t' <repeats 13 times>, "ON s.val_1 = t.val_1\n", '\t' <repeats 12 times>, "WHEN MATCHED AND val_3 = 3 THEN\n", '\t' <repeats 13 times>, "UPDATE SET val_3 = 33;") at postgres.c:1250
#15 0x000055c64e490fde in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4544
#16 0x000055c64e3f826a in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4510
#17 BackendStartup (port=<optimized out>) at postmaster.c:4238
#18 ServerLoop () at postmaster.c:1812
#19 0x000055c64e3f93db in PostmasterMain (argc=<optimized out>, argv=0x55c64f8cac30) at postmaster.c:1484
#20 0x000055c64e11a6a0 in main (argc=8, argv=0x55c64f8cac30) at main.c:202
```

Run as:
```
make USE_PGXS=1 isolationcheck ISOLATIONCHECKS="test"
```

**Comment by homper** [comment]
Fixed on [github_issue_63](https://github.com/orioledb/orioledb/tree/github_issue_63)
