### ISSUE TITLE
Assert: "(attnum) > 0": o_fill_secondary_key_bound

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#81]
specs/test.spec:

```sql

setup
{
    CREATE EXTENSION IF NOT EXISTS orioledb;

    CREATE TABLE o_test_1(
      val_1 text not null,
      val_2 text
    )USING orioledb;

    CREATE UNIQUE INDEX ON o_test_1(lower(val_1));
}

teardown
{
  DROP TABLE o_test_1;
}

session s1
step "begin_1" { BEGIN ISOLATION LEVEL READ COMMITTED; }
step "insert_1" { INSERT INTO o_test_1(val_1, val_2)
                  VALUES('Aa', 'b1'); }
step "commit_1" { COMMIT; }

session s2
step "begin_2" { BEGIN ISOLATION LEVEL READ COMMITTED; }
step "insert_2" { INSERT INTO o_test_1(val_1, val_2)
                  VALUES('AA', 'b2')
                  ON CONFLICT (lower(val_1))
                  DO UPDATE set val_1 = EXCLUDED.val_1, val_2 = o_test_1.val_2; }
step "select_2" { SELECT * FROM o_test_1; }
step "commit_2" { COMMIT; }

permutation "begin_1" "begin_2" "insert_1" "insert_2" "commit_1" "select_2" "commit_2"
```

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f78390ae859 in __GI_abort () at abort.c:79
#2  0x0000555593182198 in ExceptionalCondition (conditionName=<optimized out>, errorType=<optimized out>, fileName=<optimized out>, lineNumber=lineNumber@entry=492) at assert.c:69
#3  0x00007f783885cfed in o_fill_secondary_key_bound (primary=primary@entry=0x0, secondary=<optimized out>, secondary@entry=0x5555951693c0, tuple=..., bound=bound@entry=0x7fff89e64cb0) at src/tableam/tree.c:492
#4  0x00007f783885910a in o_tbl_insert_on_conflict (mstate=<optimized out>, estate=<optimized out>, estate@entry=0x55559522c0c0, rinfo=<optimized out>, rinfo@entry=0x55559522c560, descr=<optimized out>, descr@entry=0x555595164760, slot=<optimized out>, slot@entry=0x555595252cc0, on_conflict=<optimized out>, conflict_ix=<optimized out>) at src/tableam/operations.c:370
#5  0x00007f7838855262 in orioledb_tuple_insert_on_conflict (mstate=0x55559522c348, estate=0x55559522c0c0, rinfo=0x55559522c560, slot=<optimized out>) at src/tableam/handler.c:388
#6  0x0000555592ee4fb5 in table_extended_tuple_insert_on_conflict (slot=0x555595252cc0, rinfo=0x55559522c560, estate=0x55559522c0c0, mstate=0x55559522c348) at ../../../src/include/access/tableam.h:2220
#7  ExecInsert (context=0x7fff89e651c0, resultRelInfo=0x55559522c560, slot=0x555595252cc0, canSetTag=<optimized out>, inserted_tuple=0x0, insert_destrel=0x0) at nodeModifyTable.c:1062
#8  0x0000555592ee5f8c in ExecModifyTable (pstate=<optimized out>) at nodeModifyTable.c:3789
#9  0x0000555592eb3973 in ExecProcNode (node=0x55559522c348) at ../../../src/include/executor/executor.h:259
#10 ExecutePlan (execute_once=<optimized out>, dest=0x55559524cd48, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_INSERT, use_parallel_mode=<optimized out>, planstate=0x55559522c348, estate=0x55559522c0c0) at execMain.c:1642
#11 standard_ExecutorRun (queryDesc=0x55559521b580, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:363
#12 0x00005555930524e0 in ProcessQuery (plan=<optimized out>, sourceText=0x55559513a4b0 "INSERT INTO o_test_1(val_1, val_2)\n", ' ' <repeats 18 times>, "VALUES('AA', 'b2')\n", ' ' <repeats 18 times>, "ON CONFLICT (lower(val_1))\n", ' ' <repeats 18 times>, "DO UPDATE set val_1 = EXCLUDED.val_1, val_2 = o_test_1.val_2;", params=0x0, queryEnv=0x0, dest=0x55559524cd48, qc=0x7fff89e65530) at pquery.c:160
#13 0x0000555593053022 in PortalRunMulti (portal=portal@entry=0x5555951c5070, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x55559524cd48, altdest=altdest@entry=0x55559524cd48, qc=qc@entry=0x7fff89e65530) at pquery.c:1277
#14 0x00005555930535a1 in PortalRun (portal=portal@entry=0x5555951c5070, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x55559524cd48, altdest=altdest@entry=0x55559524cd48, qc=0x7fff89e65530) at pquery.c:791
#15 0x000055559304f292 in exec_simple_query (query_string=0x55559513a4b0 "INSERT INTO o_test_1(val_1, val_2)\n", ' ' <repeats 18 times>, "VALUES('AA', 'b2')\n", ' ' <repeats 18 times>, "ON CONFLICT (lower(val_1))\n", ' ' <repeats 18 times>, "DO UPDATE set val_1 = EXCLUDED.val_1, val_2 = o_test_1.val_2;") at postgres.c:1250
#16 0x0000555593050fde in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4544
#17 0x0000555592fb826a in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4510
#18 BackendStartup (port=<optimized out>) at postmaster.c:4238
#19 ServerLoop () at postmaster.c:1812
#20 0x0000555592fb93db in PostmasterMain (argc=<optimized out>, argv=0x555595134c30) at postmaster.c:1484
#21 0x0000555592cda6a0 in main (argc=8, argv=0x555595134c30) at main.c:202
```

Run as:
```
make USE_PGXS=1 isolationcheck ISOLATIONCHECKS="test"
```

**Comment by homper** [comment]
Just for the note: Fixed on [github_issue_135](https://github.com/orioledb/orioledb/tree/github_issue_135)
Need to add a test

**Comment by homper** [comment]
Fixed on [github_issue_135](https://github.com/orioledb/orioledb/tree/github_issue_135)
Test already present
