### ISSUE TITLE
Segfault: orioledb_tuple_insert_on_conflict: state is NULL

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#86]
sql/test.sql:

```sql
CREATE TABLE o_test_1 (
    a int unique, 
    b char
)PARTITION BY LIST (a);

CREATE TABLE o_test_2 (
    b char, 
    a int unique
)USING orioledb;

ALTER TABLE o_test_1 
    ATTACH PARTITION o_test_2 
    FOR VALUES IN (3);

INSERT INTO o_test_1 
    VALUES (3, 'a') ON CONFLICT (a) 
    DO UPDATE SET b = excluded.b;
```
**Coredump**
```
#0  orioledb_tuple_insert_on_conflict (mstate=0x55f47efe6dc8, estate=0x55f47efe6b40, rinfo=0x55f47efb03b0, slot=0x55f47effb1b8) at src/tableam/handler.c:391
391                                                                             get_ix_num_by_oid(descr, state->conflictIxOid));
#0  orioledb_tuple_insert_on_conflict (mstate=0x55f47efe6dc8, estate=0x55f47efe6b40, rinfo=0x55f47efb03b0, slot=0x55f47effb1b8) at src/tableam/handler.c:391
#1  0x000055f47e518fb5 in table_extended_tuple_insert_on_conflict (slot=0x55f47effb1b8, rinfo=0x55f47efb03b0, estate=0x55f47efe6b40, mstate=0x55f47efe6dc8) at ../../../src/include/access/tableam.h:2220
#2  ExecInsert (context=0x7ffc85f243d0, resultRelInfo=0x55f47efb03b0, slot=0x55f47effb1b8, canSetTag=<optimized out>, inserted_tuple=0x0, insert_destrel=0x0) at nodeModifyTable.c:1062
#3  0x000055f47e519f8c in ExecModifyTable (pstate=<optimized out>) at nodeModifyTable.c:3789
#4  0x000055f47e4e7973 in ExecProcNode (node=0x55f47efe6dc8) at ../../../src/include/executor/executor.h:259
#5  ExecutePlan (execute_once=<optimized out>, dest=0x55f47efeda48, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_INSERT, use_parallel_mode=<optimized out>, planstate=0x55f47efe6dc8, estate=0x55f47efe6b40) at execMain.c:1642
#6  standard_ExecutorRun (queryDesc=0x55f47efd9c50, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:363
#7  0x000055f47e6864e0 in ProcessQuery (plan=<optimized out>, sourceText=0x55f47eeb5490 "INSERT INTO o_test_1 \n    VALUES (3, 'a') ON CONFLICT (a) \n    DO UPDATE SET b = excluded.b;", params=0x0, queryEnv=0x0, dest=0x55f47efeda48, qc=0x7ffc85f24740) at pquery.c:160
#8  0x000055f47e687022 in PortalRunMulti (portal=portal@entry=0x55f47ef3ff40, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x55f47efeda48, altdest=altdest@entry=0x55f47efeda48, qc=qc@entry=0x7ffc85f24740) at pquery.c:1277
#9  0x000055f47e6875a1 in PortalRun (portal=portal@entry=0x55f47ef3ff40, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x55f47efeda48, altdest=altdest@entry=0x55f47efeda48, qc=0x7ffc85f24740) at pquery.c:791
#10 0x000055f47e683292 in exec_simple_query (query_string=0x55f47eeb5490 "INSERT INTO o_test_1 \n    VALUES (3, 'a') ON CONFLICT (a) \n    DO UPDATE SET b = excluded.b;") at postgres.c:1250
#11 0x000055f47e684fde in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4544
#12 0x000055f47e5ec26a in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4510
#13 BackendStartup (port=<optimized out>) at postmaster.c:4238
#14 ServerLoop () at postmaster.c:1812
#15 0x000055f47e5ed3db in PostmasterMain (argc=<optimized out>, argv=0x55f47eeafc20) at postmaster.c:1484
#16 0x000055f47e30e6a0 in main (argc=8, argv=0x55f47eeafc20) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by Tanyaevm** [comment]
sql/test.sql:

Error for postgres:

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;

CREATE TABLE o_test_1(
  val_1 int, 
  val_2 text, 
  val_3 int
)PARTITION BY RANGE(val_1);

CREATE TABLE o_test_2(
  val_1 int,
  val_2 text,
  val_3 int
)USING orioledb;

CREATE UNIQUE INDEX ON o_test_1 (val_1, val_2);

ALTER TABLE o_test_1 
  ATTACH PARTITION o_test_2 FOR VALUES FROM (0) TO (1000);

INSERT INTO o_test_1 VALUES (1, 'abc', 2)
  ON CONFLICT (val_1, val_2) DO UPDATE SET (val_1, val_2, val_3) = ROW(excluded.*);

```

**Coredump**
```
#0  0x00007f4f68289c40 in o_tuple_compute_data_size (natts=<optimized out>, to_toast=<optimized out>, isnull=<optimized out>, values=<optimized out>, iptr=<optimized out>, tupleDesc=<optimized out>) at src/tuple/format.c:445
445                             if (to_toast != NULL && to_toast[i - off])
#0  0x00007f4f68289c40 in o_tuple_compute_data_size (natts=<optimized out>, to_toast=<optimized out>, isnull=<optimized out>, values=<optimized out>, iptr=<optimized out>, tupleDesc=<optimized out>) at src/tuple/format.c:445
#1  o_new_tuple_size (tupleDesc=<optimized out>, spec=<optimized out>, iptr=0x555b22e17db8, version=<optimized out>, values=0x555b22e17dd0, isnull=0x555b22e17de8, to_toast=<optimized out>) at src/tuple/format.c:537
#2  0x00007f4f68291949 in expected_tuple_len (descr=0x555b22d27650, slot=0x555b22e17d88) at src/tuple/slot.c:941
#3  tts_orioledb_toast (slot=slot@entry=0x555b22e17d88, descr=descr@entry=0x555b22d27650) at src/tuple/slot.c:994
#4  0x00007f4f68279c13 in orioledb_tuple_insert_on_conflict (mstate=0x555b22e17258, estate=0x555b22e16fd0, rinfo=0x555b22e18b40, slot=0x555b22e17d88) at src/tableam/handler.c:392
#5  0x0000555b221f00c5 in table_extended_tuple_insert_on_conflict (slot=0x555b22e17d88, rinfo=0x555b22e18b40, estate=0x555b22e16fd0, mstate=0x555b22e17258) at ../../../src/include/access/tableam.h:2220
#6  ExecInsert (context=0x7ffe21e60380, resultRelInfo=0x555b22e18b40, slot=0x555b22e17d88, canSetTag=<optimized out>, inserted_tuple=0x0, insert_destrel=0x0) at nodeModifyTable.c:1062
#7  0x0000555b221f109c in ExecModifyTable (pstate=<optimized out>) at nodeModifyTable.c:3789
#8  0x0000555b221bea83 in ExecProcNode (node=0x555b22e17258) at ../../../src/include/executor/executor.h:259
#9  ExecutePlan (execute_once=<optimized out>, dest=0x555b22df7288, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_INSERT, use_parallel_mode=<optimized out>, planstate=0x555b22e17258, estate=0x555b22e16fd0) at execMain.c:1642
#10 standard_ExecutorRun (queryDesc=0x555b22e21f10, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:363
#11 0x0000555b2235d5f0 in ProcessQuery (plan=<optimized out>, sourceText=0x555b22cfd490 "INSERT INTO o_test_1 VALUES (1, 'abc', 2)\n  ON CONFLICT (val_1, val_2) DO UPDATE SET (val_1, val_2, val_3) = ROW(excluded.*);", params=0x0, queryEnv=0x0, dest=0x555b22df7288, qc=0x7ffe21e606f0) at pquery.c:160
#12 0x0000555b2235e132 in PortalRunMulti (portal=portal@entry=0x555b22d87f60, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x555b22df7288, altdest=altdest@entry=0x555b22df7288, qc=qc@entry=0x7ffe21e606f0) at pquery.c:1277
#13 0x0000555b2235e6b1 in PortalRun (portal=portal@entry=0x555b22d87f60, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x555b22df7288, altdest=altdest@entry=0x555b22df7288, qc=0x7ffe21e606f0) at pquery.c:791
#14 0x0000555b2235a3a2 in exec_simple_query (query_string=0x555b22cfd490 "INSERT INTO o_test_1 VALUES (1, 'abc', 2)\n  ON CONFLICT (val_1, val_2) DO UPDATE SET (val_1, val_2, val_3) = ROW(excluded.*);") at postgres.c:1250
#15 0x0000555b2235c0ee in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4544
#16 0x0000555b222c337a in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4510
#17 BackendStartup (port=<optimized out>) at postmaster.c:4238
#18 ServerLoop () at postmaster.c:1812
#19 0x0000555b222c44eb in PostmasterMain (argc=<optimized out>, argv=0x555b22cf7c20) at postmaster.c:1484
#20 0x0000555b21fe56e0 in main (argc=8, argv=0x555b22cf7c20) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by homper** [comment]
Fixed on [main](https://github.com/orioledb/orioledb)
Test already present
