### ISSUE TITLE
Segfault: o_tuple_read_next_field: attrdef_state is NULL

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#88]
sql/test.sql:

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;

CREATE TABLE o_test_1 
    USING orioledb 
    AS SELECT * FROM generate_series(1,10) id;

ALTER TABLE o_test_1 ADD val_1 int 
    DEFAULT (random() * 10)::int;
```

```
#0  ExecEvalExpr (state=0x80, econtext=0x55a9c2a06208, isNull=0x55a9c2a63061) at /home/orioledb/pg15/include/postgresql/server/executor/executor.h:324
324             return state->evalfunc(state, econtext, isNull);
#0  ExecEvalExpr (state=0x80, econtext=0x55a9c2a06208, isNull=0x55a9c2a63061) at /home/orioledb/pg15/include/postgresql/server/executor/executor.h:324
#1  o_tuple_read_next_field (state=0x55a9c2a63010, isnull=0x55a9c2a63061) at src/tuple/format.c:150
#2  0x00007f5393a8e840 in tts_orioledb_getsomeattrs (slot=0x55a9c2a62f78, __natts=<optimized out>) at src/tuple/slot.c:237
#3  0x000055a9c0f3912e in slot_getsomeattrs_int (slot=slot@entry=0x55a9c2a62f78, attnum=2) at execTuples.c:1912
#4  0x00007f5393a4ccda in slot_getsomeattrs (slot=0x55a9c2a62f78, attnum=2, attnum@entry=-1030526792) at /home/orioledb/pg15/include/postgresql/server/executor/tuptable.h:344
#5  slot_getallattrs (slot=<optimized out>) at /home/orioledb/pg15/include/postgresql/server/executor/tuptable.h:356
#6  rebuild_indices (old_o_table=<optimized out>, old_descr=<optimized out>, old_descr@entry=0x55a9c2931630, o_table=<optimized out>, o_table@entry=0x55a9c2948d20, descr=<optimized out>, descr@entry=0x7ffffeb8dc98) at src/catalog/indices.c:649
#7  0x00007f5393a791c0 in orioledb_rewrite_table (old_rel=<optimized out>) at src/tableam/handler.c:1419
#8  0x000055a9c0effb37 in table_extended_rewrite_table (old_rel=0x7f5384b879c8) at ../../../src/include/access/tableam.h:2354
#9  ATRewriteTables (context=0x7ffffeb8df68, lockmode=8, wqueue=0x7ffffeb8dd98, parsetree=0x55a9c2908680) at tablecmds.c:5537
#10 ATController (parsetree=0x55a9c2908680, rel=<optimized out>, cmds=<optimized out>, recurse=<optimized out>, lockmode=8, context=0x7ffffeb8df68) at tablecmds.c:4458
#11 0x00007f5393a47c21 in orioledb_utility_command (pstmt=<optimized out>, queryString=<optimized out>, readOnlyTree=<optimized out>, context=<optimized out>, params=<optimized out>, env=<optimized out>, dest=<optimized out>, qc=<optimized out>) at src/catalog/ddl.c:924
#12 0x000055a9c10cadbf in PortalRunUtility (portal=portal@entry=0x55a9c2991f40, pstmt=pstmt@entry=0x55a9c29089d0, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=0x55a9c2908ac0, qc=0x7ffffeb8e280) at pquery.c:1158
#13 0x000055a9c10caf14 in PortalRunMulti (portal=portal@entry=0x55a9c2991f40, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x55a9c2908ac0, altdest=altdest@entry=0x55a9c2908ac0, qc=qc@entry=0x7ffffeb8e280) at pquery.c:1315
#14 0x000055a9c10cb5a1 in PortalRun (portal=portal@entry=0x55a9c2991f40, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x55a9c2908ac0, altdest=altdest@entry=0x55a9c2908ac0, qc=0x7ffffeb8e280) at pquery.c:791
#15 0x000055a9c10c7292 in exec_simple_query (query_string=0x55a9c2907490 "ALTER TABLE o_test_1 ADD val_1 int \n    DEFAULT (random() * 10)::int;") at postgres.c:1250
#16 0x000055a9c10c8fde in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4544
#17 0x000055a9c103026a in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4510
#18 BackendStartup (port=<optimized out>) at postmaster.c:4238
#19 ServerLoop () at postmaster.c:1812
#20 0x000055a9c10313db in PostmasterMain (argc=<optimized out>, argv=0x55a9c2901c20) at postmaster.c:1484
#21 0x000055a9c0d526a0 in main (argc=8, argv=0x55a9c2901c20) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by Tanyaevm** [comment]
sql/test.sql:

Error with orioledb:

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;

CREATE TABLE o_test_1(
  val_1 int PRIMARY KEY
)USING orioledb;

INSERT INTO o_test_1 
  VALUES (3), (4);

ALTER TABLE o_test_1 ADD COLUMN val_2 int 
  GENERATED ALWAYS AS (val_1 * 3) STORED;
```

```Coredump 
#0  ExecEvalExpr (isNull=<optimized out>, econtext=0x563eb4793d78, state=0x0) at /home/orioledb/pg15/include/postgresql/server/executor/executor.h:324
324             return state->evalfunc(state, econtext, isNull);
#0  ExecEvalExpr (isNull=<optimized out>, econtext=0x563eb4793d78, state=0x0) at /home/orioledb/pg15/include/postgresql/server/executor/executor.h:324
#1  o_tuple_read_next_field (state=state@entry=0x563eb47b6a58, isnull=isnull@entry=0x563eb47b6aa9) at src/tuple/format.c:150
#2  0x00007fd3bebc05ce in tts_orioledb_getsomeattrs (slot=0x563eb47b69c0, __natts=<optimized out>) at src/tuple/slot.c:240
#3  0x0000563eb3e2e11e in slot_getsomeattrs_int (slot=slot@entry=0x563eb47b69c0, attnum=2) at execTuples.c:1912
#4  0x00007fd3beb7fbca in slot_getsomeattrs (slot=0x563eb47b69c0, attnum=-1267122824, attnum@entry=-1268182352) at /home/orioledb/pg15/include/postgresql/server/executor/tuptable.h:344
#5  slot_getallattrs (slot=<optimized out>) at /home/orioledb/pg15/include/postgresql/server/executor/tuptable.h:356
#6  rebuild_indices (old_o_table=<optimized out>, old_descr=<optimized out>, old_descr@entry=0x563eb468c650, o_table=<optimized out>, o_table@entry=0x563eb47962c0, descr=<optimized out>, descr@entry=0x7ffc750cec08) at src/catalog/indices.c:649
#7  0x00007fd3bebac0b0 in orioledb_rewrite_table (old_rel=<optimized out>) at src/tableam/handler.c:1419
#8  0x0000563eb3df4b37 in table_extended_rewrite_table (old_rel=0x7fd3afcbb478) at ../../../src/include/access/tableam.h:2354
#9  ATRewriteTables (context=0x7ffc750cef20, lockmode=8, wqueue=0x7ffc750ced08, parsetree=0x563eb4663528) at tablecmds.c:5537
#10 ATController (parsetree=0x563eb4663528, rel=<optimized out>, cmds=<optimized out>, recurse=<optimized out>, lockmode=8, context=0x7ffc750cef20) at tablecmds.c:4458
#11 0x00007fd3beb7c784 in orioledb_utility_command (pstmt=<optimized out>, queryString=<optimized out>, readOnlyTree=<optimized out>, context=<optimized out>, params=<optimized out>, env=<optimized out>, dest=<optimized out>, qc=<optimized out>) at src/catalog/ddl.c:924
#12 0x0000563eb3fbfdaf in PortalRunUtility (portal=portal@entry=0x563eb46ecf60, pstmt=pstmt@entry=0x563eb4663878, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=0x563eb4663968, qc=0x7ffc750cf200) at pquery.c:1158
#13 0x0000563eb3fbff04 in PortalRunMulti (portal=portal@entry=0x563eb46ecf60, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x563eb4663968, altdest=altdest@entry=0x563eb4663968, qc=qc@entry=0x7ffc750cf200) at pquery.c:1315
#14 0x0000563eb3fc0591 in PortalRun (portal=portal@entry=0x563eb46ecf60, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x563eb4663968, altdest=altdest@entry=0x563eb4663968, qc=0x7ffc750cf200) at pquery.c:791
#15 0x0000563eb3fbc282 in exec_simple_query (query_string=0x563eb4662490 "ALTER TABLE o_test_1 ADD COLUMN val_2 int \n  GENERATED ALWAYS AS (val_1 * 3) STORED;") at postgres.c:1250
#16 0x0000563eb3fbdfce in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4544
#17 0x0000563eb3f2525a in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4510
#18 BackendStartup (port=<optimized out>) at postmaster.c:4238
#19 ServerLoop () at postmaster.c:1812
#20 0x0000563eb3f263cb in PostmasterMain (argc=<optimized out>, argv=0x563eb465cc20) at postmaster.c:1484
#21 0x0000563eb3c476a0 in main (argc=8, argv=0x563eb465cc20) at main.c:202
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```
